/**
 * The labels of the facts an alarm carries (which device, which address, which port...) and the words of the alarm controls, in the seven languages.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
 */
import { cataloguesFromRows, type Row } from "./catalogueRows";

const ROWS: Record<string, Row> = {
  alarmDetails: ["Details", "Detalles", "Details", "Détails", "Dettagli", "詳細", "详情"],
  alarmHideDetails: ["Hide details", "Ocultar detalles", "Details ausblenden", "Masquer les détails", "Nascondi dettagli", "詳細を隠す", "隐藏详情"],
  alarmNoDetails: ["This alarm carries no further details.", "Esta alarma no trae más detalles.", "Dieser Alarm enthält keine weiteren Details.", "Cette alarme ne contient pas d'autres détails.", "Questo allarme non contiene altri dettagli.", "このアラームに追加の詳細はありません。", "此警报没有更多详情。"],
  alarmDelete: ["Delete", "Borrar", "Löschen", "Supprimer", "Elimina", "削除", "删除"],
  alarmDeleteTitle: ["Delete this alarm", "Borrar esta alarma", "Diesen Alarm löschen", "Supprimer cette alarme", "Elimina questo allarme", "このアラームを削除", "删除此警报"],
  alarmDeleteQuestion: ["Delete this alarm from the list? If its cause is still going on it comes back only when it happens again.", "¿Borrar esta alarma de la lista? Si su causa sigue, solo volverá a aparecer cuando vuelva a ocurrir.", "Diesen Alarm aus der Liste löschen? Dauert die Ursache an, kommt er erst wieder, wenn sie erneut eintritt.", "Supprimer cette alarme de la liste ? Si sa cause continue, elle ne reviendra que lorsqu'elle se reproduira.", "Eliminare questo allarme dall'elenco? Se la causa continua, tornerà solo quando si ripresenterà.", "このアラームを一覧から削除しますか？原因が続いていても、再発したときにだけ再び表示されます。", "从列表中删除此警报？如果原因仍在持续，只有再次发生时才会重新出现。"],
  alarmClearQuestion: ["Delete every alarm that has been acknowledged (ended or not)? The ones nobody has seen stay.", "¿Borrar todas las alarmas que ya se han reconocido (hayan terminado o no)? Las que nadie ha visto se quedan.", "Alle quittierten Alarme löschen (beendet oder nicht)? Die, die niemand gesehen hat, bleiben.", "Supprimer toutes les alarmes déjà acquittées (terminées ou non) ? Celles que personne n'a vues restent.", "Eliminare tutti gli allarmi già confermati (terminati o no)? Quelli che nessuno ha visto restano.", "確認済みのアラームをすべて削除しますか（終了済みかどうかに関係なく）？誰も見ていないものは残ります。", "删除所有已确认的警报（无论是否已结束）？无人查看过的会保留。"],
  alarmCleared: ["alarms removed", "alarmas eliminadas", "Alarme entfernt", "alarmes supprimées", "allarmi rimossi", "件のアラームを削除しました", "条警报已删除"],
  alarmFailedWhy: ["The action could not be done: ", "No se ha podido hacer la acción: ", "Die Aktion ließ sich nicht ausführen: ", "L'action n'a pas pu être faite : ", "Non è stato possibile eseguire l'azione: ", "操作を実行できませんでした：", "无法完成该操作："],
  alarmFilterAll: ["All", "Todas", "Alle", "Toutes", "Tutte", "すべて", "全部"],
  alarmFilterSource: ["Source", "Origen", "Quelle", "Source", "Origine", "発生元", "来源"],
  alarmFilterSeverity: ["Severity", "Gravedad", "Schweregrad", "Gravité", "Gravità", "重大度", "严重程度"],
  alarmSearch: ["Search an alarm, a device, an address…", "Buscar una alarma, un dispositivo, una dirección…", "Alarm, Gerät, Adresse suchen…", "Chercher une alarme, un appareil, une adresse…", "Cerca un allarme, un dispositivo, un indirizzo…", "アラーム、デバイス、アドレスを検索…", "搜索警报、设备、地址…"],
  alarmShowing: ["showing", "mostrando", "angezeigt", "affichées", "visualizzati", "表示中", "显示"],
  alarmMarkKnown: ["Mark the device as known", "Marcar el dispositivo como conocido", "Gerät als bekannt markieren", "Marquer l'appareil comme connu", "Segna il dispositivo come noto", "デバイスを既知にする", "将设备标记为已知"],
  alarmMarkedKnown: ["The device is marked as known.", "El dispositivo está marcado como conocido.", "Das Gerät ist als bekannt markiert.", "L'appareil est marqué comme connu.", "Il dispositivo è segnato come noto.", "デバイスを既知にしました。", "设备已标记为已知。"],
  alarmYes: ["yes", "sí", "ja", "oui", "sì", "はい", "是"],
  alarmNo: ["no", "no", "nein", "non", "no", "いいえ", "否"],
  source_node: ["Radar nodes", "Nodos de radar", "Radarknoten", "Nœuds radar", "Nodi radar", "レーダーノード", "雷达节点"],
  source_camera: ["Cameras", "Cámaras", "Kameras", "Caméras", "Telecamere", "カメラ", "摄像头"],
  source_device: ["Devices", "Dispositivos", "Geräte", "Appareils", "Dispositivi", "デバイス", "设备"],
  source_solar: ["Solar", "Solar", "Solar", "Solaire", "Solare", "ソーラー", "太阳能"],
  source_electrical: ["Electrical", "Eléctrico", "Elektrik", "Électrique", "Elettrico", "電気", "电气"],
  source_network: ["Network", "Red", "Netzwerk", "Réseau", "Rete", "ネットワーク", "网络"],
  fact_node: ["Monitor node", "Nodo que vigila", "Überwachender Knoten", "Nœud qui surveille", "Nodo che monitora", "監視ノード", "监控节点"],
  fact_interface: ["Interface", "Interfaz", "Schnittstelle", "Interface", "Interfaccia", "インターフェース", "接口"],
  fact_router: ["Router", "Router", "Router", "Routeur", "Router", "ルーター", "路由器"],
  fact_latency_ms: ["Latency", "Latencia", "Latenz", "Latence", "Latenza", "遅延", "延迟"],
  fact_loss_percent: ["Packet loss", "Pérdida de paquetes", "Paketverlust", "Perte de paquets", "Perdita di pacchetti", "パケット損失", "丢包"],
  fact_since: ["Since", "Desde", "Seit", "Depuis", "Da", "開始", "自"],
  fact_failing: ["What fails", "Qué falla", "Was ausfällt", "Ce qui échoue", "Cosa non risponde", "失敗している項目", "失败项"],
  fact_router_answers: ["The router answers", "El router responde", "Der Router antwortet", "Le routeur répond", "Il router risponde", "ルーターは応答", "路由器有响应"],
  fact_device: ["Device", "Dispositivo", "Gerät", "Appareil", "Dispositivo", "デバイス", "设备"],
  fact_ip: ["Address (IP)", "Dirección (IP)", "Adresse (IP)", "Adresse (IP)", "Indirizzo (IP)", "アドレス（IP）", "地址（IP）"],
  fact_mac: ["MAC", "MAC", "MAC", "MAC", "MAC", "MAC", "MAC"],
  fact_vendor: ["Maker", "Fabricante", "Hersteller", "Fabricant", "Produttore", "メーカー", "厂商"],
  fact_hostname: ["Name it announces", "Nombre que anuncia", "Angekündigter Name", "Nom annoncé", "Nome annunciato", "通知している名前", "其公布的名称"],
  fact_kind: ["Kind", "Tipo", "Art", "Type", "Tipo", "種類", "类型"],
  fact_os: ["System", "Sistema", "System", "Système", "Sistema", "システム", "系统"],
  fact_online: ["On the network now", "En la red ahora", "Jetzt im Netzwerk", "Sur le réseau maintenant", "In rete ora", "現在ネットワーク上", "当前在网络中"],
  fact_open_ports: ["Open ports", "Puertos abiertos", "Offene Ports", "Ports ouverts", "Porte aperte", "開いているポート", "开放端口"],
  fact_first_seen: ["First seen", "Visto por primera vez", "Zum ersten Mal gesehen", "Vu pour la première fois", "Visto per la prima volta", "初めて確認", "首次发现"],
  fact_port: ["Port that opened", "Puerto que se abrió", "Geöffneter Port", "Port ouvert", "Porta aperta", "開いたポート", "新开放的端口"],
  fact_risky: ["A port a house rarely wants open", "Un puerto que una casa rara vez quiere abierto", "Ein Port, den ein Haus selten offen will", "Un port qu'une maison veut rarement ouvert", "Una porta che una casa raramente vuole aperta", "家庭では通常開けたくないポート", "家庭很少希望开放的端口"],
  fact_opened_at: ["Opened at", "Abierto a las", "Geöffnet um", "Ouvert à", "Aperto alle", "開いた時刻", "开放时间"],
  fact_mac_now: ["MAC that answers now", "MAC que responde ahora", "MAC, die jetzt antwortet", "MAC qui répond maintenant", "MAC che risponde ora", "現在応答している MAC", "现在应答的 MAC"],
  fact_mac_before: ["MAC that answered before", "MAC que respondía antes", "MAC, die zuvor antwortete", "MAC qui répondait avant", "MAC che rispondeva prima", "以前応答していた MAC", "此前应答的 MAC"],
  fact_what_happened: ["What happened", "Qué pasó", "Was geschah", "Ce qui s'est passé", "Cos'è successo", "発生した内容", "发生了什么"],
};
export const alarmDetailCatalogues = cataloguesFromRows(ROWS);
