/**
 * Interface text of the Electrical Designer, one row per phrase: English, Spanish, German, French, Italian, Japanese, Chinese.
 * `el_<kind>` names the kinds of element, `elc_<category>` their groups, `elp_<key>` their properties, `eli_<code>` what the checks say
 * (with {0}, {1} ... for the figures) and `elerr_<code>` why two ports cannot be joined.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
 */
import { cataloguesFromRows, type Row, type RowCatalogues } from "./catalogueRows";

const ROWS: Record<string, Row> = {
  // menu and headings
  electricalDesigner: ["Electrical Designer", "Diseñador eléctrico", "Elektroplaner", "Concepteur électrique", "Progettista elettrico", "電気設計", "电气设计器"],
  electricalDesignerTitle: ["The house's electrical diagram: AC and DC", "El esquema eléctrico de la casa: AC y DC", "Der Stromlaufplan des Hauses: AC und DC", "Le schéma électrique de la maison : AC et DC", "Lo schema elettrico della casa: AC e DC", "住宅の電気回路図：AC と DC", "住宅电气图：交流与直流"],
  electricalDesignerHelp: ["Draw the supply, the solar system, the protections, the switches and the loads, join their ports with wires and let the checks read the drawing. It is a drawing: nothing here switches or measures anything yet.", "Dibuja la acometida, la instalación solar, las protecciones, los interruptores y las cargas, une sus puertos con cables y deja que las comprobaciones lean el dibujo. Es un dibujo: de momento nada de aquí maniobra ni mide.", "Zeichnen Sie Netz, Solaranlage, Schutzorgane, Schalter und Verbraucher, verbinden Sie ihre Anschlüsse mit Leitungen und lassen Sie die Prüfungen die Zeichnung lesen. Es ist eine Zeichnung: hier schaltet oder misst noch nichts.", "Dessinez l'alimentation, l'installation solaire, les protections, les interrupteurs et les charges, reliez leurs ports par des câbles et laissez les contrôles lire le dessin. C'est un dessin : rien ici ne commande ni ne mesure encore.", "Disegna la fornitura, l'impianto solare, le protezioni, gli interruttori e i carichi, collega le loro porte con i cavi e lascia che i controlli leggano il disegno. È un disegno: per ora nulla qui comanda o misura.", "供給、太陽光システム、保護機器、開閉器、負荷を描き、ポートを電線でつなぐと、チェックが図面を読みます。これは図面です。ここでは今のところ何も開閉も計測もしません。", "绘制供电、光伏系统、保护装置、开关和负载，用导线连接端口，检查功能会读取图纸。这只是一张图：这里目前不会控制或测量任何设备。"],
  electrical: ["Electrical", "Eléctrico", "Elektrik", "Électrique", "Elettrico", "電気", "电气"],
  electricalLiveHelp: ["What the ARMOR-ELECTRICAL nodes measure, live: the grid, the lines and the transfer switches. Read only.", "Lo que miden los nodos ARMOR-ELECTRICAL, en directo: la red, las líneas y los conmutadores. Solo lectura.", "Was die ARMOR-ELECTRICAL-Knoten live messen: das Netz, die Leitungen und die Umschalter. Nur Lesen.", "Ce que mesurent les nœuds ARMOR-ELECTRICAL, en direct : le réseau, les lignes et les commutateurs. Lecture seule.", "Ciò che misurano i nodi ARMOR-ELECTRICAL, in diretta: la rete, le linee e i commutatori. Sola lettura.", "ARMOR-ELECTRICAL ノードの計測値をリアルタイムで表示：系統、回線、切替器。読み取り専用。", "ARMOR-ELECTRICAL 节点的实时测量：电网、线路和转换开关。只读。"],
  elLiveGrid: ["Grid power", "Potencia de red", "Netzleistung", "Puissance réseau", "Potenza di rete", "系統電力", "电网功率"],
  elLiveEnergy: ["Grid energy", "Energía de red", "Netzenergie", "Énergie réseau", "Energia di rete", "系統電力量", "电网电量"],
  elLiveNodes: ["Nodes reporting", "Nodos que informan", "Meldende Knoten", "Nœuds en liaison", "Nodi in linea", "報告中のノード", "上报的节点"],
  elLiveAlarms: ["Alarms", "Alarmas", "Alarme", "Alarmes", "Allarmi", "アラーム", "报警"],
  elLiveUnreachable: ["The server does not answer the electrical readings.", "El servidor no responde con las lecturas eléctricas.", "Der Server liefert die elektrischen Messwerte nicht.", "Le serveur ne répond pas pour les mesures électriques.", "Il server non risponde con le letture elettriche.", "サーバーが電気の計測値に応答しません。", "服务器没有返回电气读数。"],
  elLiveRole: ["The electrical nodes and the diagram", "Los nodos eléctricos y el esquema", "Die Elektroknoten und der Plan", "Les nœuds électriques et le schéma", "I nodi elettrici e lo schema", "電気ノードと回路図", "电气节点与原理图"],
  elLiveRoleText: ["An electrical node is the ESP32 in the panel that measures the lines and reads the switches. Here you see what it measures; in the Electrical Designer you draw where it is in the diagram of the house, and the node takes its place there.", "Un nodo eléctrico es el ESP32 del cuadro que mide las líneas y lee los conmutadores. Aquí ves lo que mide; en el Diseñador eléctrico dibujas dónde está en el esquema de la casa, y el nodo ocupa su sitio allí.", "Ein Elektroknoten ist der ESP32 im Schaltschrank, der die Leitungen misst und die Umschalter liest. Hier sehen Sie, was er misst; im Elektroplaner zeichnen Sie, wo er im Plan des Hauses sitzt.", "Un nœud électrique est l'ESP32 du tableau qui mesure les lignes et lit les commutateurs. Ici vous voyez ce qu'il mesure ; dans le Concepteur électrique vous dessinez où il se trouve dans le schéma de la maison.", "Un nodo elettrico è l'ESP32 nel quadro che misura le linee e legge i commutatori. Qui vedi ciò che misura; nel Progettista elettrico disegni dove si trova nello schema della casa.", "電気ノードは分電盤内の ESP32 で、回線を計測し切替器を読み取ります。ここでは計測値を、電気設計では家の回路図のどこにあるかを描きます。", "电气节点是配电箱内的 ESP32，测量线路并读取转换开关。这里查看它的测量值；在电气设计中绘制它在住宅原理图中的位置。"],
  elLiveOpenDesigner: ["Open the Electrical Designer", "Abrir el Diseñador eléctrico", "Elektroplaner öffnen", "Ouvrir le Concepteur électrique", "Apri il Progettista elettrico", "電気設計を開く", "打开电气设计"],
  elLiveNone: ["No electrical node has reported yet", "Ningún nodo eléctrico ha informado aún", "Noch kein Elektroknoten hat gemeldet", "Aucun nœud électrique n'a encore rapporté", "Nessun nodo elettrico ha ancora riferito", "報告した電気ノードはまだありません", "还没有电气节点上报"],
  elLiveNoneHelp: ["Power on an ARMOR-ELECTRICAL node on this network: look for it above and open its panel to point it to this server.", "Enciende un nodo ARMOR-ELECTRICAL en esta red: búscalo arriba y abre su panel para apuntarlo a este servidor.", "Schalten Sie einen ARMOR-ELECTRICAL-Knoten in diesem Netzwerk ein: Suchen Sie ihn oben und öffnen Sie sein Panel, um ihn auf diesen Server zu richten.", "Allumez un nœud ARMOR-ELECTRICAL sur ce réseau : cherchez-le ci-dessus et ouvrez son panneau pour le pointer vers ce serveur.", "Accendi un nodo ARMOR-ELECTRICAL in questa rete: cercalo qui sopra e apri il suo pannello per puntarlo a questo server.", "このネットワークで ARMOR-ELECTRICAL ノードを起動し、上で検索してパネルを開き、このサーバーを指定してください。", "在此网络中启动 ARMOR-ELECTRICAL 节点：在上方搜索并打开其面板，指向本服务器。"],
  elLiveDrawn: ["in the diagram", "en el esquema", "im Plan", "dans le schéma", "nello schema", "回路図にあり", "已在原理图中"],
  elLiveNotDrawn: ["not in the diagram yet", "aún no está en el esquema", "noch nicht im Plan", "pas encore dans le schéma", "non ancora nello schema", "回路図にまだありません", "尚未在原理图中"],
  elLiveSwitchingOff: ["switching disabled in the node", "maniobra desactivada en el nodo", "Schalten im Knoten deaktiviert", "commutation désactivée dans le nœud", "manovra disattivata nel nodo", "ノードで切替が無効", "节点已禁用切换"],
  elLiveChannel: ["Channel", "Canal", "Kanal", "Canal", "Canale", "チャンネル", "通道"],
  elLiveState: ["State", "Estado", "Zustand", "État", "Stato", "状態", "状态"],
  elLiveAlarm: ["alarm", "alarma", "Alarm", "alarme", "allarme", "アラーム", "报警"],
  elLive_closed: ["closed", "cerrado", "geschlossen", "fermé", "chiuso", "閉", "闭合"],
  elLive_open: ["open", "abierto", "offen", "ouvert", "aperto", "開", "断开"],
  elLive_unknown: ["unknown", "desconocido", "unbekannt", "inconnu", "sconosciuto", "不明", "未知"],
  elLiveSelected: ["Source in use", "Fuente en uso", "Quelle in Verwendung", "Source utilisée", "Sorgente in uso", "使用中の電源", "使用中的电源"],
  elLiveNoSource: ["none", "ninguna", "keine", "aucune", "nessuna", "なし", "无"],
  elLiveClosing: ["closing", "cerrando", "schließt", "ferme", "chiude", "投入中", "正在闭合"],
  elLiveFault_did_not_close: ["did not close", "no cerró", "hat nicht geschlossen", "ne s'est pas fermé", "non si è chiuso", "投入できず", "未能闭合"],
  elLiveFault_did_not_open: ["did not open", "no abrió", "hat nicht geöffnet", "ne s'est pas ouvert", "non si è aperto", "開放できず", "未能断开"],
  elLiveFault_both_closed: ["both sources closed", "las dos fuentes cerradas", "beide Quellen geschlossen", "les deux sources fermées", "entrambe le sorgenti chiuse", "両方の電源が投入", "两路电源均闭合"],
  elLiveFault_disabled: ["disabled", "desactivado", "deaktiviert", "désactivé", "disattivato", "無効", "已禁用"],
  // categories
  elc_source: ["Sources", "Fuentes", "Quellen", "Sources", "Sorgenti", "電源", "电源"],
  elc_storage: ["Storage", "Almacenamiento", "Speicher", "Stockage", "Accumulo", "蓄電", "储能"],
  elc_conversion: ["Conversion", "Conversión", "Umwandlung", "Conversion", "Conversione", "変換", "变换"],
  elc_protection: ["Protections", "Protecciones", "Schutz", "Protections", "Protezioni", "保護", "保护"],
  elc_switching: ["Switching and remote control", "Maniobra y telemando", "Schalten und Fernsteuerung", "Commutation et télécommande", "Manovra e telecomando", "開閉と遠隔操作", "开关与遥控"],
  elc_distribution: ["Distribution", "Distribución", "Verteilung", "Distribution", "Distribuzione", "配電", "配电"],
  elc_measure: ["Measurement and nodes", "Medida y nodos", "Messung und Knoten", "Mesure et nœuds", "Misura e nodi", "計測とノード", "测量与节点"],
  elc_load: ["Loads", "Cargas", "Verbraucher", "Charges", "Carichi", "負荷", "负载"],
  // kinds of element
  el_grid: ["Grid supply", "Red eléctrica", "Stromnetz", "Réseau électrique", "Rete elettrica", "系統電源", "电网"],
  "el_pv-array": ["PV array", "Campo fotovoltaico", "PV-Feld", "Champ photovoltaïque", "Campo fotovoltaico", "太陽光アレイ", "光伏阵列"],
  el_generator: ["Generator", "Grupo electrógeno", "Generator", "Groupe électrogène", "Generatore", "発電機", "发电机"],
  el_battery: ["Battery bank", "Banco de baterías", "Batteriebank", "Parc de batteries", "Banco di batterie", "蓄電池バンク", "电池组"],
  el_inverter: ["Hybrid inverter", "Inversor híbrido", "Hybrid-Wechselrichter", "Onduleur hybride", "Inverter ibrido", "ハイブリッドインバーター", "混合逆变器"],
  el_mppt: ["MPPT solar controller", "Regulador solar MPPT", "MPPT-Laderegler", "Régulateur solaire MPPT", "Regolatore solare MPPT", "MPPT 充電コントローラー", "MPPT 控制器"],
  el_charger: ["Battery charger", "Cargador de baterías", "Batterieladegerät", "Chargeur de batterie", "Caricabatterie", "バッテリー充電器", "电池充电器"],
  "el_dc-dc": ["DC-DC converter", "Convertidor DC-DC", "DC-DC-Wandler", "Convertisseur DC-DC", "Convertitore DC-DC", "DC-DC コンバーター", "DC-DC 转换器"],
  el_mcb: ["Circuit breaker (MCB)", "Magnetotérmico", "Leitungsschutzschalter", "Disjoncteur", "Interruttore magnetotermico", "ブレーカー（MCB）", "微型断路器"],
  "el_mcb-dc": ["DC circuit breaker", "Magnetotérmico DC", "DC-Leitungsschutzschalter", "Disjoncteur DC", "Magnetotermico DC", "DC ブレーカー", "直流断路器"],
  el_rcd: ["Residual-current device", "Interruptor diferencial", "FI-Schutzschalter", "Interrupteur différentiel", "Interruttore differenziale", "漏電遮断器", "漏电保护器"],
  "el_fuse-dc": ["DC fuse", "Fusible DC", "DC-Sicherung", "Fusible DC", "Fusibile DC", "DC ヒューズ", "直流熔断器"],
  el_spd: ["Surge protector", "Protector de sobretensiones", "Überspannungsschutz", "Parafoudre", "Scaricatore di sovratensioni", "サージ保護器", "浪涌保护器"],
  el_isolator: ["Isolator switch", "Seccionador", "Trennschalter", "Sectionneur", "Sezionatore", "断路スイッチ", "隔离开关"],
  el_contactor: ["Contactor", "Contactor", "Schütz", "Contacteur", "Contattore", "電磁接触器", "接触器"],
  "el_e-breaker": ["Electronic breaker (remote)", "Magnetotérmico electrónico (telemando)", "Elektronischer Schutzschalter (fern)", "Disjoncteur électronique (télécommandé)", "Interruttore elettronico (telecomando)", "電子ブレーカー（遠隔）", "电子断路器（遥控）"],
  "el_e-breaker-dc": ["DC electronic breaker (remote)", "Magnetotérmico DC electrónico (telemando)", "Elektronischer DC-Schutzschalter (fern)", "Disjoncteur électronique DC (télécommandé)", "Interruttore elettronico DC (telecomando)", "DC 電子ブレーカー（遠隔）", "直流电子断路器（遥控）"],
  el_transfer: ["Source transfer switch", "Conmutador de fuente (red / inversor)", "Quellenumschalter", "Commutateur de source", "Commutatore di sorgente", "電源切替スイッチ", "电源转换开关"],
  "el_busbar-ac": ["AC busbar", "Embarrado AC", "Sammelschiene AC", "Barre de distribution AC", "Sbarra AC", "AC 母線", "交流母排"],
  "el_busbar-dc": ["DC busbar", "Embarrado DC", "Sammelschiene DC", "Barre de distribution DC", "Sbarra DC", "DC 母線", "直流母排"],
  el_relay: ["Relay module", "Módulo de relé", "Relaismodul", "Module relais", "Modulo relè", "リレーモジュール", "继电器模块"],
  el_diverter: ["Solar surplus diverter", "Derivador de excedentes solares", "PV-Überschussregler", "Routeur de surplus solaire", "Deviatore di surplus solare", "太陽光余剰ダイバーター", "光伏余电分流器"],
  el_plc: ["Automation controller (PLC)", "Cuadro de automatismos (PLC)", "Automatisierungssteuerung (SPS)", "Automate programmable (API)", "Controllore di automazione (PLC)", "オートメーションコントローラー（PLC）", "自动化控制器（PLC）"],
  "el_junction-ac": ["AC junction", "Empalme AC", "Verbindungspunkt AC", "Jonction AC", "Giunzione AC", "AC 接続点", "交流接线点"],
  "el_junction-dc": ["DC junction", "Empalme DC", "Verbindungspunkt DC", "Jonction DC", "Giunzione DC", "DC 接続点", "直流接线点"],
  "el_meter-ac": ["AC energy meter", "Contador / medidor AC", "Stromzähler AC", "Compteur d'énergie AC", "Contatore di energia AC", "AC 電力量計", "交流电能表"],
  "el_meter-dc": ["DC meter (shunt)", "Medidor DC (shunt)", "DC-Messgerät (Shunt)", "Mesure DC (shunt)", "Misuratore DC (shunt)", "DC 計測（シャント）", "直流计量（分流器）"],
  el_node: ["ARMOR-ELECTRICAL node", "Nodo ARMOR-ELECTRICAL", "ARMOR-ELECTRICAL-Knoten", "Nœud ARMOR-ELECTRICAL", "Nodo ARMOR-ELECTRICAL", "ARMOR-ELECTRICAL ノード", "ARMOR-ELECTRICAL 节点"],
  el_load: ["Load", "Carga", "Verbraucher", "Charge", "Carico", "負荷", "负载"],
  "el_water-heater": ["Electric water heater", "Termo eléctrico", "Elektro-Warmwasserspeicher", "Chauffe-eau électrique", "Scaldabagno elettrico", "電気温水器", "电热水器"],
  el_socket: ["Smart socket", "Enchufe inteligente", "Smarte Steckdose", "Prise connectée", "Presa intelligente", "スマートコンセント", "智能插座"],
  el_lighting: ["Lighting", "Iluminación", "Beleuchtung", "Éclairage", "Illuminazione", "照明", "照明"],
  "el_ev-charger": ["EV charger", "Cargador de coche eléctrico", "Wallbox", "Borne de recharge", "Wallbox", "EV 充電器", "电动车充电桩"],
  el_hvac: ["Air conditioning", "Climatización", "Klimaanlage", "Climatisation", "Climatizzazione", "空調", "空调"],
  "el_load-dc": ["DC load", "Carga DC", "DC-Verbraucher", "Charge DC", "Carico DC", "DC 負荷", "直流负载"],
  // properties
  elp_manufacturer: ["Manufacturer", "Fabricante", "Hersteller", "Fabricant", "Produttore", "メーカー", "制造商"],
  elp_model: ["Model", "Modelo", "Modell", "Modèle", "Modello", "モデル", "型号"],
  elp_voltage_v: ["Voltage (V)", "Tensión (V)", "Spannung (V)", "Tension (V)", "Tensione (V)", "電圧 (V)", "电压 (V)"],
  elp_contracted_kw: ["Contracted power (kW)", "Potencia contratada (kW)", "Vertragsleistung (kW)", "Puissance souscrite (kW)", "Potenza impegnata (kW)", "契約電力 (kW)", "合同功率 (kW)"],
  elp_peak_wp: ["Peak power (Wp)", "Potencia pico (Wp)", "Spitzenleistung (Wp)", "Puissance crête (Wc)", "Potenza di picco (Wp)", "ピーク電力 (Wp)", "峰值功率 (Wp)"],
  elp_strings: ["Strings", "Strings", "Strings", "Strings", "Stringhe", "ストリング数", "组串数"],
  elp_voc_v: ["Open-circuit voltage (V)", "Tensión en vacío (V)", "Leerlaufspannung (V)", "Tension à vide (V)", "Tensione a vuoto (V)", "開放電圧 (V)", "开路电压 (V)"],
  elp_rated_w: ["Rated power (W)", "Potencia nominal (W)", "Nennleistung (W)", "Puissance nominale (W)", "Potenza nominale (W)", "定格電力 (W)", "额定功率 (W)"],
  elp_nominal_v: ["Nominal voltage (V)", "Tensión nominal (V)", "Nennspannung (V)", "Tension nominale (V)", "Tensione nominale (V)", "公称電圧 (V)", "标称电压 (V)"],
  elp_capacity_ah: ["Capacity (Ah)", "Capacidad (Ah)", "Kapazität (Ah)", "Capacité (Ah)", "Capacità (Ah)", "容量 (Ah)", "容量 (Ah)"],
  elp_chemistry: ["Chemistry", "Química", "Zellchemie", "Chimie", "Chimica", "セル化学", "化学体系"],
  elp_modules: ["Modules", "Módulos", "Module", "Modules", "Moduli", "モジュール数", "模块数"],
  elp_nominal_dc_v: ["DC voltage (V)", "Tensión DC (V)", "DC-Spannung (V)", "Tension DC (V)", "Tensione DC (V)", "DC 電圧 (V)", "直流电压 (V)"],
  elp_acin_max_w: ["Most it draws from the AC input (W)", "Máximo que toma de la entrada AC (W)", "Höchstbezug am AC-Eingang (W)", "Maximum tiré de l'entrée AC (W)", "Massimo assorbito dall'ingresso AC (W)", "AC 入力からの最大消費 (W)", "交流输入最大取电 (W)"],
  elp_rating_a: ["Rating (A)", "Calibre (A)", "Nennstrom (A)", "Calibre (A)", "Portata (A)", "定格電流 (A)", "额定电流 (A)"],
  elp_curve: ["Curve", "Curva", "Charakteristik", "Courbe", "Curva", "特性", "曲线"],
  elp_poles: ["Poles", "Polos", "Pole", "Pôles", "Poli", "極数", "极数"],
  elp_sensitivity_ma: ["Sensitivity (mA)", "Sensibilidad (mA)", "Empfindlichkeit (mA)", "Sensibilité (mA)", "Sensibilità (mA)", "感度 (mA)", "灵敏度 (mA)"],
  elp_type: ["Type", "Tipo", "Typ", "Type", "Tipo", "タイプ", "类型"],
  elp_coil: ["Coil", "Bobina", "Spule", "Bobine", "Bobina", "コイル", "线圈"],
  elp_mode: ["Mode", "Modo", "Modus", "Mode", "Modalità", "モード", "模式"],
  elp_kind: ["Kind", "Clase", "Art", "Genre", "Genere", "種類", "种类"],
  elp_shunt_a: ["Shunt (A)", "Shunt (A)", "Shunt (A)", "Shunt (A)", "Shunt (A)", "シャント (A)", "分流器 (A)"],
  elp_node_id: ["Node identifier", "Identificador del nodo", "Knotenkennung", "Identifiant du nœud", "Identificativo del nodo", "ノード ID", "节点标识"],
  elp_channels: ["Channels", "Canales", "Kanäle", "Canaux", "Canali", "チャンネル数", "通道数"],
  elp_power_w: ["Power (W)", "Potencia (W)", "Leistung (W)", "Puissance (W)", "Potenza (W)", "電力 (W)", "功率 (W)"],
  elp_volume_l: ["Volume (L)", "Volumen (L)", "Volumen (L)", "Volume (L)", "Volume (L)", "容量 (L)", "容积 (L)"],
  elv_manual: ["manual", "manual", "manuell", "manuel", "manuale", "手動", "手动"],
  elv_automatic: ["automatic", "automático", "automatisch", "automatique", "automatico", "自動", "自动"],
  elv_direct: ["direct", "directo", "direkt", "direct", "diretto", "直接", "直接"],
  elv_other: ["other", "otra", "andere", "autre", "altra", "その他", "其他"],
  elv_Lead: ["Lead-acid", "Plomo-ácido", "Blei-Säure", "Plomb-acide", "Piombo-acido", "鉛蓄電池", "铅酸"],
  // the tools and the panels
  elPalette: ["Elements", "Elementos", "Elemente", "Éléments", "Elementi", "部品", "元件"],
  elInspector: ["Properties", "Propiedades", "Eigenschaften", "Propriétés", "Proprietà", "プロパティ", "属性"],
  elChecks: ["Checks", "Comprobaciones", "Prüfungen", "Contrôles", "Controlli", "チェック", "检查"],
  elTotals: ["Totals", "Totales", "Summen", "Totaux", "Totali", "合計", "合计"],
  elTotPv: ["PV peak", "FV pico", "PV-Spitze", "PV crête", "FV di picco", "太陽光ピーク", "光伏峰值"],
  elTotBattery: ["Storage", "Almacenamiento", "Speicher", "Stockage", "Accumulo", "蓄電量", "储能"],
  elTotInverters: ["Inverters", "Inversores", "Wechselrichter", "Onduleurs", "Inverter", "インバーター", "逆变器"],
  elTotLoads: ["AC loads drawn", "Cargas AC dibujadas", "Gezeichnete AC-Lasten", "Charges AC dessinées", "Carichi AC disegnati", "描画した AC 負荷", "已绘制的交流负载"],
  elNoIssues: ["Nothing to report.", "Nada que señalar.", "Nichts zu melden.", "Rien à signaler.", "Nulla da segnalare.", "指摘事項はありません。", "没有需要提示的内容。"],
  elIssueErrors: ["errors", "errores", "Fehler", "erreurs", "errori", "エラー", "错误"],
  elIssueWarnings: ["warnings", "avisos", "Warnungen", "avertissements", "avvisi", "警告", "警告"],
  elToolSelect: ["Select and move", "Seleccionar y mover", "Auswählen und verschieben", "Sélectionner et déplacer", "Seleziona e sposta", "選択と移動", "选择与移动"],
  elToolWire: ["Wire", "Cable", "Leitung", "Câble", "Cavo", "配線", "连线"],
  elToolFrame: ["Panel frame", "Marco de cuadro", "Tafelrahmen", "Cadre de tableau", "Riquadro di quadro", "盤の枠", "配电箱框"],
  elUndo: ["Undo", "Deshacer", "Rückgängig", "Annuler", "Annulla", "元に戻す", "撤销"],
  elRedo: ["Redo", "Rehacer", "Wiederholen", "Rétablir", "Ripeti", "やり直し", "重做"],
  elDelete: ["Delete", "Borrar", "Löschen", "Supprimer", "Elimina", "削除", "删除"],
  elDuplicate: ["Duplicate", "Duplicar", "Duplizieren", "Dupliquer", "Duplica", "複製", "复制"],
  elFit: ["Fit to screen", "Ajustar a la pantalla", "An Bildschirm anpassen", "Ajuster à l'écran", "Adatta allo schermo", "全体表示", "适应屏幕"],
  elNew: ["New drawing", "Dibujo nuevo", "Neue Zeichnung", "Nouveau dessin", "Nuovo disegno", "新規図面", "新建图纸"],
  elPresetHouse: ["Load the example: house with solar", "Cargar el ejemplo: casa con solar", "Beispiel laden: Haus mit Solar", "Charger l'exemple : maison avec solaire", "Carica l'esempio: casa con solare", "例を読み込む：太陽光つきの家", "载入示例：带光伏的住宅"],
  elClearConfirm: ["Start a new drawing? The current one is kept in the undo history.", "¿Empezar un dibujo nuevo? El actual queda en el historial de deshacer.", "Neue Zeichnung beginnen? Die aktuelle bleibt im Rückgängig-Verlauf.", "Commencer un nouveau dessin ? L'actuel reste dans l'historique d'annulation.", "Iniziare un nuovo disegno? Quello attuale resta nella cronologia di annullamento.", "新しい図面を始めますか？ 現在の図面は元に戻す履歴に残ります。", "新建图纸？当前图纸会保留在撤销历史中。"],
  elExportJson: ["Export JSON", "Exportar JSON", "JSON exportieren", "Exporter en JSON", "Esporta JSON", "JSON を書き出す", "导出 JSON"],
  elExportSvg: ["Export SVG", "Exportar SVG", "SVG exportieren", "Exporter en SVG", "Esporta SVG", "SVG を書き出す", "导出 SVG"],
  elImport: ["Import JSON", "Importar JSON", "JSON importieren", "Importer un JSON", "Importa JSON", "JSON を読み込む", "导入 JSON"],
  elImportBad: ["That file is not an electrical drawing.", "Ese archivo no es un dibujo eléctrico.", "Diese Datei ist keine Elektrozeichnung.", "Ce fichier n'est pas un dessin électrique.", "Quel file non è un disegno elettrico.", "そのファイルは電気図面ではありません。", "该文件不是电气图纸。"],
  elImported: ["Drawing imported.", "Dibujo importado.", "Zeichnung importiert.", "Dessin importé.", "Disegno importato.", "図面を読み込みました。", "图纸已导入。"],
  elExported: ["Drawing exported.", "Dibujo exportado.", "Zeichnung exportiert.", "Dessin exporté.", "Disegno esportato.", "図面を書き出しました。", "图纸已导出。"],
  elName: ["Name", "Nombre", "Name", "Nom", "Nome", "名前", "名称"],
  elBindSolar: ["Solar device it shows", "Dispositivo solar que muestra", "Angezeigtes Solargerät", "Appareil solaire affiché", "Dispositivo solare mostrato", "表示するソーラー機器", "显示的光伏设备"],
  elBindNone: ["none", "ninguno", "keines", "aucun", "nessuno", "なし", "无"],
  elBindNode: ["Node that measures it", "Nodo que lo mide", "Knoten, der es misst", "Nœud qui le mesure", "Nodo che lo misura", "計測するノード", "测量它的节点"],
  elChannel: ["Channel", "Canal", "Kanal", "Canal", "Canale", "チャンネル", "通道"],
  elState: ["Drawn as", "Dibujado como", "Gezeichnet als", "Dessiné comme", "Disegnato come", "図示の状態", "图示状态"],
  elStateClosed: ["closed", "cerrado", "geschlossen", "fermé", "chiuso", "閉", "闭合"],
  elStateOpen: ["open (breaks the line)", "abierto (corta la línea)", "offen (unterbricht die Leitung)", "ouvert (coupe la ligne)", "aperto (interrompe la linea)", "開（回路を遮断）", "断开（切断线路）"],
  elRemote: ["can be switched from a node", "se podrá maniobrar desde un nodo", "kann von einem Knoten geschaltet werden", "pourra être commandé depuis un nœud", "si potrà comandare da un nodo", "ノードから開閉可能", "可由节点操控"],
  elWire: ["Wire", "Cable", "Leitung", "Câble", "Cavo", "電線", "导线"],
  elWireSection: ["Section (mm²)", "Sección (mm²)", "Querschnitt (mm²)", "Section (mm²)", "Sezione (mm²)", "断面積 (mm²)", "截面 (mm²)"],
  elWireLength: ["Length (m)", "Longitud (m)", "Länge (m)", "Longueur (m)", "Lunghezza (m)", "長さ (m)", "长度 (m)"],
  elWireLabel: ["Label", "Etiqueta", "Bezeichnung", "Étiquette", "Etichetta", "ラベル", "标签"],
  elFrame: ["Panel frame", "Marco de cuadro", "Tafelrahmen", "Cadre de tableau", "Riquadro di quadro", "盤の枠", "配电箱框"],
  elFrameColour: ["Colour", "Color", "Farbe", "Couleur", "Colore", "色", "颜色"],
  elLive: ["Live values", "Valores en directo", "Live-Werte", "Valeurs en direct", "Valori in tempo reale", "リアルタイム値", "实时数值"],
  elSaved: ["Saved on the server", "Guardado en el servidor", "Auf dem Server gespeichert", "Enregistré sur le serveur", "Salvato sul server", "サーバーに保存済み", "已保存到服务器"],
  elSaving: ["Saving…", "Guardando…", "Speichern…", "Enregistrement…", "Salvataggio…", "保存中…", "保存中…"],
  elOffline: ["Server not reachable: kept in this browser only", "Servidor sin respuesta: solo en este navegador", "Server nicht erreichbar: nur in diesem Browser", "Serveur injoignable : conservé dans ce navigateur seulement", "Server non raggiungibile: solo in questo browser", "サーバーに接続できません：このブラウザーにのみ保存", "服务器无法访问：仅保存在此浏览器"],
  elConflict: ["Someone else saved the electrical drawing first: their version is now on screen.", "Otra persona guardó antes el dibujo eléctrico: ahora se ve su versión.", "Jemand anderes hat die Elektrozeichnung zuerst gespeichert: Ihre Version ist jetzt zu sehen.", "Quelqu'un a enregistré le dessin électrique avant : sa version est maintenant affichée.", "Qualcun altro ha salvato prima il disegno elettrico: ora si vede la sua versione.", "他の人が先に電気図面を保存しました。その版を表示しています。", "有人先保存了电气图纸：现在显示的是其版本。"],
  elKeys: ["V select · W wire · Del delete · Ctrl+Z undo · arrows nudge · Esc cancel · wheel zoom · drag empty space to pan", "V seleccionar · W cable · Supr borrar · Ctrl+Z deshacer · flechas mover · Esc cancelar · rueda zoom · arrastra el fondo para desplazar", "V Auswahl · W Leitung · Entf löschen · Strg+Z rückgängig · Pfeile schieben · Esc abbrechen · Rad Zoom · Hintergrund ziehen", "V sélection · W câble · Suppr effacer · Ctrl+Z annuler · flèches déplacer · Échap annuler · molette zoom · glisser le fond pour défiler", "V seleziona · W cavo · Canc elimina · Ctrl+Z annulla · frecce sposta · Esc annulla · rotella zoom · trascina lo sfondo", "V 選択 · W 配線 · Del 削除 · Ctrl+Z 元に戻す · 矢印 移動 · Esc 取消 · ホイール ズーム · 背景ドラッグで移動", "V 选择 · W 连线 · Del 删除 · Ctrl+Z 撤销 · 方向键 移动 · Esc 取消 · 滚轮 缩放 · 拖动空白处平移"],
  elWiringHint: ["Click another port to finish the wire (Esc cancels).", "Pulsa otro puerto para terminar el cable (Esc cancela).", "Klicken Sie einen anderen Anschluss, um die Leitung zu beenden (Esc bricht ab).", "Cliquez un autre port pour finir le câble (Échap annule).", "Fai clic su un'altra porta per finire il cavo (Esc annulla).", "別のポートをクリックして配線を終えます（Esc で取消）。", "点击另一个端口完成连线（Esc 取消）。"],
  elPlaceHint: ["Click on the drawing to place it (Shift keeps placing, Esc cancels).", "Pulsa en el dibujo para colocarlo (Mayús sigue colocando, Esc cancela).", "Klicken Sie in die Zeichnung, um es zu setzen (Umschalt setzt weiter, Esc bricht ab).", "Cliquez dans le dessin pour le placer (Maj continue, Échap annule).", "Fai clic nel disegno per posizionarlo (Maiusc continua, Esc annulla).", "図面をクリックして配置します（Shift で連続配置、Esc で取消）。", "点击图纸放置（Shift 连续放置，Esc 取消）。"],
  elDisclaimer: ["The checks are a guide for reviewing the drawing, not a substitute for the regulations or an installer.", "Las comprobaciones son una guía para revisar el dibujo, no sustituyen al reglamento ni a un instalador.", "Die Prüfungen sind eine Hilfe zum Durchsehen der Zeichnung, kein Ersatz für die Vorschriften oder einen Installateur.", "Les contrôles sont un guide pour relire le dessin, pas un substitut à la réglementation ni à un installateur.", "I controlli sono una guida per rivedere il disegno, non sostituiscono la normativa né un installatore.", "チェックは図面を見直すための目安であり、法規や施工業者に代わるものではありません。", "检查仅用于审阅图纸，不能代替法规或安装人员。"],
  elDrawn: ["Elements", "Elementos", "Elemente", "Éléments", "Elementi", "部品数", "元件数"],
  elWires: ["Wires", "Cables", "Leitungen", "Câbles", "Cavi", "電線数", "导线数"],
  // what the checks say
  eli_orphan: ["{0} is not connected to anything.", "{0} no está conectado a nada.", "{0} ist mit nichts verbunden.", "{0} n'est relié à rien.", "{0} non è collegato a nulla.", "{0} は何にも接続されていません。", "{0} 未连接任何设备。"],
  eli_port_open: ["{0}: the port \"{1}\" is not connected.", "{0}: el puerto «{1}» no está conectado.", "{0}: der Anschluss „{1}“ ist nicht verbunden.", "{0} : le port « {1} » n'est pas relié.", "{0}: la porta «{1}» non è collegata.", "{0}：ポート「{1}」が接続されていません。", "{0}：端口“{1}”未连接。"],
  eli_node_unbound: ["The node {0} has no identifier yet.", "El nodo {0} aún no tiene identificador.", "Der Knoten {0} hat noch keine Kennung.", "Le nœud {0} n'a pas encore d'identifiant.", "Il nodo {0} non ha ancora un identificativo.", "ノード {0} にはまだ ID がありません。", "节点 {0} 尚无标识。"],
  eli_dc_voltage: ["Voltage mismatch on a DC wire: {0} works at {1} V and {2} at {3} V.", "Tensiones distintas en un cable DC: {0} trabaja a {1} V y {2} a {3} V.", "Spannungen passen nicht an einer DC-Leitung: {0} arbeitet mit {1} V und {2} mit {3} V.", "Tensions différentes sur un câble DC : {0} travaille à {1} V et {2} à {3} V.", "Tensioni diverse su un cavo DC: {0} lavora a {1} V e {2} a {3} V.", "DC 電線の電圧が合いません：{0} は {1} V、{2} は {3} V です。", "直流导线两端电压不一致：{0} 为 {1} V，{2} 为 {3} V。"],
  eli_cable_small: ["A {0} mm² cable is behind a {1} A protection; it should not be protected by more than {2} A.", "Un cable de {0} mm² está detrás de una protección de {1} A; no debería protegerse con más de {2} A.", "Ein Kabel mit {0} mm² liegt hinter einer {1}-A-Schutzeinrichtung; es sollte mit höchstens {2} A abgesichert sein.", "Un câble de {0} mm² est derrière une protection de {1} A ; il ne devrait pas être protégé par plus de {2} A.", "Un cavo da {0} mm² è dietro una protezione da {1} A; non dovrebbe essere protetto con più di {2} A.", "{0} mm² のケーブルが {1} A の保護の後ろにあります。保護は {2} A までにすべきです。", "{0} mm² 的导线位于 {1} A 保护之后；其保护不应超过 {2} A。"],
  eli_backfeed: ["{0} is fed by two sources at once ({1}) with no transfer switch between them.", "{0} recibe alimentación de dos fuentes a la vez ({1}) sin un conmutador entre ellas.", "{0} wird von zwei Quellen gleichzeitig gespeist ({1}) ohne Umschalter dazwischen.", "{0} est alimenté par deux sources à la fois ({1}) sans commutateur entre elles.", "{0} è alimentato da due sorgenti insieme ({1}) senza un commutatore tra loro.", "{0} は 2 つの電源（{1}）から同時に給電されており、間に切替スイッチがありません。", "{0} 同时由两个电源（{1}）供电，且它们之间没有转换开关。"],
  eli_breaker_small: ["{0} is rated {1} A but about {2} A can flow behind it.", "{0} es de {1} A pero detrás pueden circular unos {2} A.", "{0} ist für {1} A ausgelegt, dahinter können aber etwa {2} A fließen.", "{0} est de {1} A mais environ {2} A peuvent circuler derrière.", "{0} è da {1} A ma dietro possono passare circa {2} A.", "{0} は {1} A ですが、その先に約 {2} A が流れ得ます。", "{0} 额定 {1} A，但其后可能流过约 {2} A。"],
  eli_inverter_overload: ["{0}: the loads on its output add up to {1} W, more than its {2} W.", "{0}: las cargas de su salida suman {1} W, más de sus {2} W.", "{0}: die Lasten am Ausgang ergeben {1} W, mehr als seine {2} W.", "{0} : les charges de sa sortie totalisent {1} W, plus que ses {2} W.", "{0}: i carichi della sua uscita sommano {1} W, più dei suoi {2} W.", "{0}：出力側の負荷の合計は {1} W で、定格 {2} W を超えています。", "{0}：其输出侧负载合计 {1} W，超过其额定 {2} W。"],
  eli_grid_overload: ["{0}: the loads drawn from the grid add up to {1} W, more than the {2} W contracted.", "{0}: las cargas tomadas de la red suman {1} W, más de los {2} W contratados.", "{0}: die aus dem Netz bezogenen Lasten ergeben {1} W, mehr als die vereinbarten {2} W.", "{0} : les charges tirées du réseau totalisent {1} W, plus que les {2} W souscrits.", "{0}: i carichi prelevati dalla rete sommano {1} W, più dei {2} W impegnati.", "{0}：系統から引く負荷の合計は {1} W で、契約の {2} W を超えています。", "{0}：从电网取电的负载合计 {1} W，超过合同的 {2} W。"],
  eli_no_supply: ["{0} is not reached by any source.", "{0} no recibe alimentación de ninguna fuente.", "{0} wird von keiner Quelle erreicht.", "{0} n'est atteint par aucune source.", "{0} non è raggiunto da nessuna sorgente.", "{0} にはどの電源からも給電されません。", "{0} 没有任何电源到达。"],
  eli_no_breaker: ["{0} has a path from a source with no circuit breaker in front of it.", "{0} tiene un camino desde una fuente sin magnetotérmico delante.", "{0} hat einen Weg von einer Quelle ohne Leitungsschutzschalter davor.", "{0} a un chemin depuis une source sans disjoncteur devant.", "{0} ha un percorso da una sorgente senza interruttore magnetotermico davanti.", "{0} には、ブレーカーを通らない電源からの経路があります。", "{0} 存在一条从电源出发、前面没有断路器的路径。"],
  eli_no_rcd: ["{0} has no residual-current device in front of it.", "{0} no tiene diferencial delante.", "{0} hat keinen FI-Schutzschalter davor.", "{0} n'a pas d'interrupteur différentiel devant.", "{0} non ha un differenziale davanti.", "{0} の前段に漏電遮断器がありません。", "{0} 前面没有漏电保护器。"],
  elerr_unknown_port: ["That port does not exist.", "Ese puerto no existe.", "Dieser Anschluss existiert nicht.", "Ce port n'existe pas.", "Quella porta non esiste.", "そのポートは存在しません。", "该端口不存在。"],
  elerr_same_element: ["A wire cannot join an element to itself.", "Un cable no puede unir un elemento consigo mismo.", "Eine Leitung kann ein Element nicht mit sich selbst verbinden.", "Un câble ne peut pas relier un élément à lui-même.", "Un cavo non può unire un elemento a se stesso.", "電線で同じ部品自身をつなぐことはできません。", "导线不能把元件连到自身。"],
  elerr_domain: ["AC, DC and signal ports cannot be joined to each other.", "Los puertos AC, DC y de señal no se pueden unir entre sí.", "AC-, DC- und Signalanschlüsse lassen sich nicht miteinander verbinden.", "Les ports AC, DC et signal ne peuvent pas être reliés entre eux.", "Le porte AC, DC e di segnale non si possono unire tra loro.", "AC・DC・信号のポート同士はつなげません。", "交流、直流和信号端口之间不能互连。"],
  elerr_busy: ["That port already has a wire (only busbars and junctions take several).", "Ese puerto ya tiene un cable (solo los embarrados y empalmes admiten varios).", "Dieser Anschluss hat schon eine Leitung (nur Sammelschienen und Verbindungspunkte nehmen mehrere).", "Ce port a déjà un câble (seuls les barres et jonctions en acceptent plusieurs).", "Quella porta ha già un cavo (solo sbarre e giunzioni ne accettano più d'uno).", "そのポートには既に電線があります（母線と接続点のみ複数可）。", "该端口已有导线（只有母排和接线点可接多根）。"],
  elerr_exists: ["Those two ports are already joined.", "Esos dos puertos ya están unidos.", "Diese beiden Anschlüsse sind schon verbunden.", "Ces deux ports sont déjà reliés.", "Quelle due porte sono già collegate.", "その 2 つのポートは既に接続済みです。", "这两个端口已相连。"],
  elerr_signal_pair: ["A signal wire joins a node to the element it measures or switches.", "Un cable de señal une un nodo con el elemento que mide o maniobra.", "Eine Signalleitung verbindet einen Knoten mit dem Element, das er misst oder schaltet.", "Un câble de signal relie un nœud à l'élément qu'il mesure ou commande.", "Un cavo di segnale unisce un nodo all'elemento che misura o comanda.", "信号線はノードと、それが計測・開閉する部品をつなぎます。", "信号线连接节点与其测量或控制的元件。"],
  elerr_too_many: ["The drawing has reached its limit.", "El dibujo ha alcanzado su límite.", "Die Zeichnung hat ihre Grenze erreicht.", "Le dessin a atteint sa limite.", "Il disegno ha raggiunto il limite.", "図面が上限に達しました。", "图纸已达上限。"],
  // the example
  elx_panel: ["Main distribution board", "Cuadro general", "Hauptverteilung", "Tableau général", "Quadro generale", "主分電盤", "总配电箱"],
  elx_system1: ["Solar system 1", "Sistema solar 1", "Solarsystem 1", "Système solaire 1", "Sistema solare 1", "ソーラーシステム 1", "光伏系统 1"],
  elx_system2: ["Solar system 2", "Sistema solar 2", "Solarsystem 2", "Système solaire 2", "Sistema solare 2", "ソーラーシステム 2", "光伏系统 2"],
  elx_backup: ["Backed-up loads", "Cargas respaldadas", "Notstrom-Verbraucher", "Charges secourues", "Carichi di backup", "バックアップ負荷", "备用供电负载"],
};

export const electricalCatalogues: RowCatalogues = cataloguesFromRows(ROWS);
export const ELECTRICAL_KEYS = Object.keys(ROWS);
