/**
 * The words of Configuration > Node firmware (updating the firmware of the field nodes from Studio), in the seven languages.
 * One row per phrase: en, es, de, fr, it, ja, zh.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
 */
import type { Locale } from "./i18n";

type Row = readonly [string, string, string, string, string, string, string];
const order: readonly Locale[] = ["en", "es", "de", "fr", "it", "ja", "zh"];

const rows: Record<string, Row> = {
  tabFirmware: ["Node firmware", "Firmware de nodos", "Knoten-Firmware", "Firmware des nœuds", "Firmware dei nodi", "ノードのファームウェア", "节点固件"],
  fw_title: ["Update the firmware of the nodes", "Actualizar el firmware de los nodos", "Firmware der Knoten aktualisieren", "Mettre à jour le firmware des nœuds", "Aggiorna il firmware dei nodi", "ノードのファームウェアを更新", "更新节点固件"],
  fw_help: [
    "Updates field nodes without opening the page of each one. The server sends the image to every node you tick, one after another, signs in to each node's own panel with the login below (used for this update only, never kept) and waits for the node to come back with the new version. It works for every kind of node, also one with no Internet.",
    "Actualiza los nodos de campo sin abrir la página de cada uno. El servidor envía la imagen a cada nodo marcado, uno tras otro, entra en el panel propio de cada nodo con el acceso de abajo (solo para esta actualización, nunca se guarda) y espera a que el nodo vuelva con la versión nueva. Sirve para todo tipo de nodo, también para uno sin Internet.",
    "Aktualisiert Feldknoten, ohne die Seite jedes Knotens zu öffnen. Der Server sendet das Image nacheinander an jeden markierten Knoten, meldet sich mit dem Zugang unten am eigenen Panel jedes Knotens an (nur für dieses Update, nie gespeichert) und wartet, bis der Knoten mit der neuen Version zurückkommt. Es funktioniert für jede Art von Knoten, auch ohne Internet.",
    "Met à jour les nœuds de terrain sans ouvrir la page de chacun. Le serveur envoie l'image à chaque nœud coché, l'un après l'autre, se connecte au panneau de chaque nœud avec l'identifiant ci-dessous (uniquement pour cette mise à jour, jamais conservé) et attend que le nœud revienne avec la nouvelle version. Cela marche pour tous les types de nœuds, même sans Internet.",
    "Aggiorna i nodi di campo senza aprire la pagina di ciascuno. Il server invia l'immagine a ogni nodo selezionato, uno dopo l'altro, accede al pannello di ciascun nodo con l'accesso qui sotto (solo per questo aggiornamento, mai conservato) e attende che il nodo torni con la nuova versione. Funziona per ogni tipo di nodo, anche senza Internet.",
    "各ノードのページを開かずにフィールドノードを更新します。サーバーがチェックしたノードに順番にイメージを送り、下のログイン情報で各ノード自身のパネルにサインインし（この更新のためだけに使い、保存しません）、ノードが新しいバージョンで戻るのを待ちます。インターネットに接続していないノードを含め、すべての種類のノードで使えます。",
    "无需打开每个节点的页面即可更新现场节点。服务器依次向每个勾选的节点发送镜像，用下方的登录信息登录各节点自己的面板（仅用于本次更新，绝不保存），并等待节点以新版本重新上线。适用于所有类型的节点，也包括没有互联网的节点。",
  ],
  fw_kind: ["Type of node", "Tipo de nodo", "Art des Knotens", "Type de nœud", "Tipo di nodo", "ノードの種類", "节点类型"],
  fw_kind_radar: ["Radar", "Radar", "Radar", "Radar", "Radar", "レーダー", "雷达"],
  fw_kind_solar: ["Solar", "Solar", "Solar", "Solaire", "Solare", "ソーラー", "太阳能"],
  fw_kind_electrical: ["Electrical", "Eléctrico", "Elektrik", "Électrique", "Elettrico", "電気", "电气"],
  fw_kind_hmi: ["Touch panel (HMI)", "Panel táctil (HMI)", "Touch-Panel (HMI)", "Écran tactile (HMI)", "Pannello touch (HMI)", "タッチパネル (HMI)", "触摸面板 (HMI)"],
  fw_nodes: ["Nodes found on the network", "Nodos encontrados en la red", "Im Netzwerk gefundene Knoten", "Nœuds trouvés sur le réseau", "Nodi trovati nella rete", "ネットワークで見つかったノード", "网络中发现的节点"],
  fw_none: ["No node of this type has been found on the network yet. Search for nodes in the Radar, Inverters or Electrical menus and come back.", "Aún no se ha encontrado en la red ningún nodo de este tipo. Busca nodos en los menús Radar, Inversores o Eléctrico y vuelve.", "Im Netzwerk wurde noch kein Knoten dieser Art gefunden. Suche in den Menüs Radar, Wechselrichter oder Elektrik nach Knoten und komm zurück.", "Aucun nœud de ce type n'a encore été trouvé sur le réseau. Cherchez des nœuds dans les menus Radar, Onduleurs ou Électrique, puis revenez.", "Nessun nodo di questo tipo è ancora stato trovato nella rete. Cerca i nodi nei menu Radar, Inverter o Elettrico e torna.", "このタイプのノードはまだネットワークで見つかっていません。レーダー、インバーター、電気のメニューでノードを検索してから戻ってください。", "网络中尚未发现此类型的节点。请在雷达、逆变器或电气菜单中搜索节点后再回来。"],
  fw_ask: ["Ask the nodes their version", "Preguntar la versión a los nodos", "Versionen der Knoten abfragen", "Demander leur version aux nœuds", "Chiedi la versione ai nodi", "ノードにバージョンを問い合わせる", "查询节点版本"],
  fw_select_kind: ["Select all of this type", "Marcar todos los de este tipo", "Alle dieser Art markieren", "Cocher tous ceux de ce type", "Seleziona tutti di questo tipo", "この種類をすべて選択", "选择此类型的全部节点"],
  fw_select_none: ["Clear the selection", "Quitar la selección", "Auswahl aufheben", "Effacer la sélection", "Annulla la selezione", "選択を解除", "清除选择"],
  fw_version_now: ["version", "versión", "Version", "version", "versione", "バージョン", "版本"],
  fw_unreachable: ["does not answer", "no responde", "antwortet nicht", "ne répond pas", "non risponde", "応答なし", "无响应"],
  fw_login_title: ["Login of the nodes' own panel", "Acceso al panel propio de los nodos", "Zugang zum eigenen Panel der Knoten", "Identifiant du panneau propre des nœuds", "Accesso al pannello proprio dei nodi", "ノード自身のパネルのログイン", "节点自身面板的登录信息"],
  fw_login_help: ["The administrator of the nodes' panel (the same for all the ticked nodes). It is used for this update only: it is not stored and not written in the audit trail.", "El administrador del panel de los nodos (el mismo para todos los marcados). Se usa solo para esta actualización: no se guarda ni se escribe en el registro de auditoría.", "Der Administrator des Panels der Knoten (derselbe für alle markierten). Er wird nur für dieses Update verwendet: nicht gespeichert und nicht im Audit-Protokoll vermerkt.", "L'administrateur du panneau des nœuds (le même pour tous ceux cochés). Il n'est utilisé que pour cette mise à jour : ni conservé ni écrit dans le journal d'audit.", "L'amministratore del pannello dei nodi (lo stesso per tutti quelli selezionati). Serve solo per questo aggiornamento: non viene conservato né scritto nel registro di audit.", "ノードのパネルの管理者（チェックしたすべてのノードで共通）。この更新のためだけに使い、保存も監査記録への書き込みもしません。", "节点面板的管理员（所有勾选的节点相同）。仅用于本次更新：不会被保存，也不会写入审计记录。"],
  fw_user: ["User", "Usuario", "Benutzer", "Utilisateur", "Utente", "ユーザー", "用户"],
  fw_password: ["Password", "Contraseña", "Passwort", "Mot de passe", "Password", "パスワード", "密码"],
  fw_source: ["Where the firmware comes from", "De dónde sale el firmware", "Woher die Firmware kommt", "D'où vient le firmware", "Da dove proviene il firmware", "ファームウェアの入手元", "固件来源"],
  fw_source_github: ["Newest release on GitHub", "Última versión publicada en GitHub", "Neueste Version auf GitHub", "Dernière version sur GitHub", "Ultima versione su GitHub", "GitHub の最新リリース", "GitHub 上的最新发布"],
  fw_source_file: ["A file from this computer", "Un archivo de este ordenador", "Eine Datei von diesem Computer", "Un fichier de cet ordinateur", "Un file da questo computer", "このコンピューターのファイル", "此电脑上的文件"],
  fw_check_release: ["Look up the release", "Consultar la versión publicada", "Veröffentlichte Version abfragen", "Consulter la version publiée", "Consulta la versione pubblicata", "リリースを確認", "查询发布版本"],
  fw_release: ["Newest release", "Última versión publicada", "Neueste Version", "Dernière version publiée", "Ultima versione pubblicata", "最新リリース", "最新发布"],
  fw_release_ok: ["downloaded and checked against the hash the release publishes", "descargada y comprobada con la suma que publica la versión", "heruntergeladen und mit der veröffentlichten Prüfsumme verglichen", "téléchargée et vérifiée avec la somme publiée par la version", "scaricata e verificata con la somma pubblicata dalla versione", "ダウンロードし、リリースが公開するハッシュで確認済み", "已下载并用该发布提供的校验和核对"],
  fw_file: ["Firmware file (the .bin of the node's project, not the merged image)", "Archivo de firmware (el .bin del proyecto del nodo, no la imagen completa)", "Firmware-Datei (die .bin des Knoten-Projekts, nicht das vollständige Image)", "Fichier de firmware (le .bin du projet du nœud, pas l'image complète)", "File firmware (il .bin del progetto del nodo, non l'immagine completa)", "ファームウェアファイル（ノードのプロジェクトの .bin。結合イメージではありません）", "固件文件（节点项目的 .bin，不是合并镜像）"],
  fw_start: ["Update the ticked nodes", "Actualizar los nodos marcados", "Markierte Knoten aktualisieren", "Mettre à jour les nœuds cochés", "Aggiorna i nodi selezionati", "選択したノードを更新", "更新已勾选的节点"],
  fw_confirm_title: ["Update the firmware?", "¿Actualizar el firmware?", "Firmware aktualisieren?", "Mettre à jour le firmware ?", "Aggiornare il firmware?", "ファームウェアを更新しますか？", "更新固件？"],
  fw_confirm_text: ["The ticked nodes will restart one after another with the new firmware. Do not cut their power meanwhile. A node whose new firmware does not start goes back to the previous one by itself.", "Los nodos marcados se reiniciarán uno tras otro con el firmware nuevo. No les quites la alimentación mientras tanto. Un nodo cuyo firmware nuevo no arranque vuelve solo al anterior.", "Die markierten Knoten starten nacheinander mit der neuen Firmware neu. Trenne sie währenddessen nicht vom Strom. Ein Knoten, dessen neue Firmware nicht startet, kehrt von selbst zur vorherigen zurück.", "Les nœuds cochés redémarreront l'un après l'autre avec le nouveau firmware. Ne coupez pas leur alimentation entre-temps. Un nœud dont le nouveau firmware ne démarre pas revient seul au précédent.", "I nodi selezionati si riavvieranno uno dopo l'altro con il nuovo firmware. Non togliere loro l'alimentazione nel frattempo. Un nodo il cui nuovo firmware non parte torna da solo al precedente.", "チェックしたノードは新しいファームウェアで順番に再起動します。その間は電源を切らないでください。新しいファームウェアが起動しないノードは自動的に前のものに戻ります。", "已勾选的节点将依次用新固件重启。期间请勿断电。新固件无法启动的节点会自动回到之前的版本。"],
  fw_confirm_go: ["Update", "Actualizar", "Aktualisieren", "Mettre à jour", "Aggiorna", "更新する", "更新"],
  fw_job: ["Progress", "Progreso", "Fortschritt", "Progression", "Avanzamento", "進行状況", "进度"],
  fw_job_preparing: ["Getting the image ready...", "Preparando la imagen...", "Image wird vorbereitet ...", "Préparation de l'image...", "Preparazione dell'immagine...", "イメージを準備中...", "正在准备镜像..."],
  fw_job_running: ["Updating, one node at a time...", "Actualizando, un nodo cada vez...", "Aktualisierung, ein Knoten nach dem anderen ...", "Mise à jour, un nœud à la fois...", "Aggiornamento, un nodo alla volta...", "更新中（1 台ずつ）...", "正在更新，一次一个节点..."],
  fw_job_done: ["All the nodes are updated.", "Todos los nodos están actualizados.", "Alle Knoten sind aktualisiert.", "Tous les nœuds sont à jour.", "Tutti i nodi sono aggiornati.", "すべてのノードが更新されました。", "所有节点均已更新。"],
  fw_job_failed: ["Some nodes could not be updated; see the reason on each.", "Algún nodo no se pudo actualizar; mira el motivo en cada uno.", "Einige Knoten konnten nicht aktualisiert werden; den Grund siehe bei jedem.", "Certains nœuds n'ont pas pu être mis à jour ; voyez la raison pour chacun.", "Alcuni nodi non si sono potuti aggiornare; vedi il motivo su ciascuno.", "更新できなかったノードがあります。各ノードの理由を確認してください。", "部分节点无法更新，请查看每个节点的原因。"],
  fw_state_waiting: ["waiting", "esperando", "wartet", "en attente", "in attesa", "待機中", "等待中"],
  fw_state_checking: ["checking", "comprobando", "prüft", "vérification", "verifica", "確認中", "检查中"],
  fw_state_signing_in: ["signing in", "entrando", "meldet an", "connexion", "accesso", "サインイン中", "登录中"],
  fw_state_uploading: ["sending the image", "enviando la imagen", "sendet das Image", "envoi de l'image", "invio dell'immagine", "イメージを送信中", "正在发送镜像"],
  fw_state_restarting: ["restarting", "reiniciando", "startet neu", "redémarrage", "riavvio", "再起動中", "重启中"],
  fw_state_done: ["updated", "actualizado", "aktualisiert", "mis à jour", "aggiornato", "更新済み", "已更新"],
  fw_state_failed: ["failed", "con fallo", "fehlgeschlagen", "échec", "non riuscito", "失敗", "失败"],
  fw_err_generic: ["It could not be done.", "No se pudo hacer.", "Es ging nicht.", "Impossible à faire.", "Non è stato possibile.", "実行できませんでした。", "无法完成。"],
  fw_err_node_not_reachable: ["The node does not answer on the network.", "El nodo no responde en la red.", "Der Knoten antwortet im Netzwerk nicht.", "Le nœud ne répond pas sur le réseau.", "Il nodo non risponde in rete.", "ノードがネットワークで応答しません。", "节点在网络上没有响应。"],
  fw_err_panel_login_refused: ["The node's panel refused that user or password.", "El panel del nodo rechazó ese usuario o contraseña.", "Das Panel des Knotens hat diesen Benutzer oder dieses Passwort abgelehnt.", "Le panneau du nœud a refusé cet utilisateur ou ce mot de passe.", "Il pannello del nodo ha rifiutato quell'utente o password.", "ノードのパネルがそのユーザーまたはパスワードを拒否しました。", "节点面板拒绝了该用户或密码。"],
  fw_err_panel_login_failed: ["The node's panel did not accept the login.", "El panel del nodo no aceptó el acceso.", "Das Panel des Knotens hat die Anmeldung nicht akzeptiert.", "Le panneau du nœud n'a pas accepté la connexion.", "Il pannello del nodo non ha accettato l'accesso.", "ノードのパネルがログインを受け付けませんでした。", "节点面板未接受该登录。"],
  fw_err_upload_failed: ["The image could not be sent to the node.", "No se pudo enviar la imagen al nodo.", "Das Image konnte nicht an den Knoten gesendet werden.", "L'image n'a pas pu être envoyée au nœud.", "Non è stato possibile inviare l'immagine al nodo.", "イメージをノードに送信できませんでした。", "无法将镜像发送给节点。"],
  fw_err_hash_mismatch: ["The node received something other than what was sent (its hash differs).", "El nodo recibió algo distinto de lo enviado (su suma no coincide).", "Der Knoten hat etwas anderes empfangen als gesendet (Prüfsumme weicht ab).", "Le nœud a reçu autre chose que ce qui a été envoyé (sa somme diffère).", "Il nodo ha ricevuto qualcosa di diverso da quanto inviato (la somma non coincide).", "ノードが送信内容と異なるものを受信しました（ハッシュが一致しません）。", "节点收到的与发送的不同（校验和不一致）。"],
  fw_err_did_not_come_back: ["The node did not come back with the new version in time. Check it before trying again.", "El nodo no volvió con la versión nueva a tiempo. Revísalo antes de reintentar.", "Der Knoten kam nicht rechtzeitig mit der neuen Version zurück. Prüfe ihn, bevor du es erneut versuchst.", "Le nœud n'est pas revenu à temps avec la nouvelle version. Vérifiez-le avant de réessayer.", "Il nodo non è tornato in tempo con la nuova versione. Controllalo prima di riprovare.", "ノードが時間内に新しいバージョンで戻りませんでした。再試行する前に確認してください。", "节点未能及时以新版本重新上线。重试前请先检查它。"],
  fw_err_node_wrong_firmware: ["That firmware belongs to another project.", "Ese firmware es de otro proyecto.", "Diese Firmware gehört zu einem anderen Projekt.", "Ce firmware appartient à un autre projet.", "Quel firmware appartiene a un altro progetto.", "そのファームウェアは別のプロジェクトのものです。", "该固件属于另一个项目。"],
  fw_err_node_not_firmware: ["The node says that file is not a firmware image.", "El nodo dice que ese archivo no es una imagen de firmware.", "Der Knoten sagt, diese Datei sei kein Firmware-Image.", "Le nœud dit que ce fichier n'est pas une image de firmware.", "Il nodo dice che quel file non è un'immagine firmware.", "ノードはそのファイルがファームウェアイメージではないと言っています。", "节点表示该文件不是固件镜像。"],
  fw_err_checksum_mismatch: ["The release's image does not match the hash it publishes: it was not used.", "La imagen de la versión no coincide con la suma que publica: no se usó.", "Das Image der Version stimmt nicht mit der veröffentlichten Prüfsumme überein: nicht verwendet.", "L'image de la version ne correspond pas à la somme publiée : elle n'a pas été utilisée.", "L'immagine della versione non corrisponde alla somma pubblicata: non è stata usata.", "リリースのイメージが公開されたハッシュと一致しないため、使用しませんでした。", "该发布的镜像与其公布的校验和不符：未使用。"],
  fw_err_no_checksum: ["The release carries no hash file (.sha256), so it is not used.", "La versión no trae archivo de suma (.sha256), por eso no se usa.", "Die Version enthält keine Prüfsummendatei (.sha256) und wird deshalb nicht verwendet.", "La version ne contient pas de fichier de somme (.sha256) ; elle n'est donc pas utilisée.", "La versione non include un file di somma (.sha256), quindi non viene usata.", "このリリースにはハッシュファイル (.sha256) がないため、使用しません。", "该发布没有校验和文件 (.sha256)，因此不使用。"],
  fw_err_no_release: ["This kind of node has no release on GitHub yet.", "Este tipo de nodo aún no tiene versión publicada en GitHub.", "Für diese Art von Knoten gibt es auf GitHub noch keine Version.", "Ce type de nœud n'a pas encore de version sur GitHub.", "Questo tipo di nodo non ha ancora una versione su GitHub.", "このタイプのノードには GitHub にまだリリースがありません。", "此类型的节点在 GitHub 上还没有发布版本。"],
  fw_err_no_image_in_release: ["The newest release has no firmware image attached.", "La última versión no trae imagen de firmware.", "An der neuesten Version hängt kein Firmware-Image.", "La dernière version n'a pas d'image de firmware jointe.", "L'ultima versione non ha un'immagine firmware allegata.", "最新リリースにはファームウェアイメージが添付されていません。", "最新发布没有附带固件镜像。"],
  fw_err_github_unreachable: ["GitHub could not be reached from the server.", "El servidor no pudo llegar a GitHub.", "Der Server konnte GitHub nicht erreichen.", "Le serveur n'a pas pu joindre GitHub.", "Il server non ha potuto raggiungere GitHub.", "サーバーから GitHub に接続できませんでした。", "服务器无法访问 GitHub。"],
  fw_err_download_failed: ["The release could not be downloaded.", "No se pudo descargar la versión.", "Die Version konnte nicht heruntergeladen werden.", "La version n'a pas pu être téléchargée.", "Non è stato possibile scaricare la versione.", "リリースをダウンロードできませんでした。", "无法下载该发布版本。"],
  fw_err_bad_size: ["That file is not the size of a firmware image.", "Ese archivo no tiene el tamaño de una imagen de firmware.", "Diese Datei hat nicht die Größe eines Firmware-Images.", "Ce fichier n'a pas la taille d'une image de firmware.", "Quel file non ha la dimensione di un'immagine firmware.", "そのファイルはファームウェアイメージのサイズではありません。", "该文件的大小不符合固件镜像。"],
  fw_err_not_firmware: ["That file is not an ESP32 firmware image.", "Ese archivo no es una imagen de firmware de ESP32.", "Diese Datei ist kein ESP32-Firmware-Image.", "Ce fichier n'est pas une image de firmware ESP32.", "Quel file non è un'immagine firmware ESP32.", "そのファイルは ESP32 のファームウェアイメージではありません。", "该文件不是 ESP32 固件镜像。"],
  fw_err_job_running: ["Another update is already running; wait for it to finish.", "Ya hay otra actualización en marcha; espera a que termine.", "Es läuft bereits ein anderes Update; warte, bis es fertig ist.", "Une autre mise à jour est déjà en cours ; attendez qu'elle se termine.", "È già in corso un altro aggiornamento; attendi che finisca.", "別の更新が実行中です。完了するまでお待ちください。", "已有另一个更新正在进行，请等待其完成。"],
  fw_err_no_panel_login: ["Type the user and password of the nodes' panel.", "Escribe el usuario y la contraseña del panel de los nodos.", "Gib Benutzer und Passwort des Panels der Knoten ein.", "Saisissez l'utilisateur et le mot de passe du panneau des nœuds.", "Inserisci utente e password del pannello dei nodi.", "ノードのパネルのユーザーとパスワードを入力してください。", "请输入节点面板的用户名和密码。"],
  fw_err_invalid_address: ["One of the addresses is not on the local network.", "Una de las direcciones no es de la red local.", "Eine der Adressen liegt nicht im lokalen Netzwerk.", "Une des adresses n'est pas sur le réseau local.", "Uno degli indirizzi non è nella rete locale.", "アドレスの1つがローカルネットワークにありません。", "其中一个地址不在本地网络中。"],
  fw_err_forbidden: ["Only an administrator can do this.", "Esto solo lo puede hacer un administrador.", "Das kann nur ein Administrator tun.", "Seul un administrateur peut faire cela.", "Solo un amministratore può farlo.", "管理者のみ実行できます。", "只有管理员可以这样做。"],
};

/** The catalogue of one language. */
export const firmwareCatalogue = (locale: Locale): Record<string, string> => {
  const index = order.indexOf(locale);
  return Object.fromEntries(Object.entries(rows).map(([key, row]) => [key, row[index]]));
};
