/**
 * Hover hints, part 5: the administration screens (services, broker accounts, settings files) and adopting a node. See hintsA.ts and hoverHints.ts.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D)
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
import type { Hint } from "./hintsA";

export const hintsE: Record<string, Hint> = {
  tabServices: ["Start, stop or restart the A.R.M.O.R. services of the machine.", "Arranca, para o reinicia los servicios de A.R.M.O.R. de la máquina.", "Die A.R.M.O.R.-Dienste des Rechners starten, stoppen oder neu starten.", "Démarre, arrête ou redémarre les services A.R.M.O.R. de la machine.", "Avvia, ferma o riavvia i servizi A.R.M.O.R. della macchina.", "マシン上の A.R.M.O.R. サービスを起動・停止・再起動します。", "启动、停止或重启本机的 A.R.M.O.R. 服务。"],
  tabBroker: ["The MQTT broker: its state, the account of every node and its settings.", "El broker MQTT: su estado, la cuenta de cada nodo y sus ajustes.", "Der MQTT-Broker: Zustand, Konto jedes Knotens und Einstellungen.", "Le broker MQTT : son état, le compte de chaque nœud et ses réglages.", "Il broker MQTT: il suo stato, l'account di ogni nodo e le sue impostazioni.", "MQTT ブローカー：状態、各ノードのアカウント、設定。", "MQTT 代理：状态、各节点的账户及其设置。"],
  tabFiles: ["Read and change every settings file of the system, with a copy kept of the old one.", "Lee y cambia cada archivo de ajustes del sistema, conservando copia del anterior.", "Jede Einstellungsdatei des Systems lesen und ändern, mit Kopie der alten.", "Lit et modifie chaque fichier de réglages du système, en gardant une copie de l'ancien.", "Legge e modifica ogni file di impostazioni del sistema, conservando una copia del vecchio.", "システムのすべての設定ファイルを読み書きします。旧ファイルのコピーが残ります。", "读取并修改系统的每个设置文件，并保留旧文件的副本。"],
  adm_start: ["Starts the service.", "Arranca el servicio.", "Startet den Dienst.", "Démarre le service.", "Avvia il servizio.", "サービスを起動します。", "启动该服务。"],
  adm_stop: ["Stops the service. What depends on it stops working until it is started again.", "Para el servicio. Lo que depende de él deja de funcionar hasta que se arranque de nuevo.", "Stoppt den Dienst. Was davon abhängt, funktioniert nicht mehr, bis er wieder gestartet wird.", "Arrête le service. Ce qui en dépend cesse de fonctionner jusqu'à son redémarrage.", "Ferma il servizio. Ciò che ne dipende smette di funzionare finché non viene riavviato.", "サービスを停止します。依存するものは再起動するまで動作しません。", "停止该服务。依赖它的功能在重新启动前无法使用。"],
  adm_restart: ["Restarts the service; it is unavailable for a few seconds.", "Reinicia el servicio; durante unos segundos no estará disponible.", "Startet den Dienst neu; er ist einige Sekunden nicht erreichbar.", "Redémarre le service ; il est indisponible quelques secondes.", "Riavvia il servizio; per qualche secondo non è disponibile.", "サービスを再起動します。数秒間利用できません。", "重启该服务，几秒钟内不可用。"],
  adm_save: ["Saves the file. The previous one is kept as a copy. The change applies when the service restarts.", "Guarda el archivo. El anterior se conserva como copia. El cambio se aplica cuando el servicio se reinicia.", "Speichert die Datei. Die vorige bleibt als Kopie erhalten. Die Änderung gilt beim Neustart des Dienstes.", "Enregistre le fichier. Le précédent est gardé en copie. Le changement s'applique au redémarrage du service.", "Salva il file. Il precedente resta come copia. La modifica si applica al riavvio del servizio.", "ファイルを保存します。以前のものはコピーとして残り、変更はサービスの再起動時に反映されます。", "保存文件。旧文件会保留为副本，更改在服务重启后生效。"],
  adm_save_restart: ["Saves the file and restarts the services that read it, so the change applies at once.", "Guarda el archivo y reinicia los servicios que lo leen, para que el cambio se aplique al instante.", "Speichert die Datei und startet die Dienste neu, die sie lesen, damit die Änderung sofort gilt.", "Enregistre le fichier et redémarre les services qui le lisent, pour appliquer le changement aussitôt.", "Salva il file e riavvia i servizi che lo leggono, così la modifica si applica subito.", "ファイルを保存し、それを読むサービスを再起動して、変更をすぐに反映します。", "保存文件并重启读取它的服务，使更改立即生效。"],
  adm_revert: ["Throws away what you typed and shows the saved file again.", "Descarta lo que escribiste y vuelve a mostrar el archivo guardado.", "Verwirft Ihre Eingaben und zeigt wieder die gespeicherte Datei.", "Abandonne ce que vous avez saisi et réaffiche le fichier enregistré.", "Scarta ciò che hai scritto e mostra di nuovo il file salvato.", "入力内容を破棄し、保存済みのファイルを再表示します。", "放弃所输入的内容，重新显示已保存的文件。"],
  adm_role: ["The kind of account decides which topics it may read and write.", "El tipo de cuenta decide qué topics puede leer y escribir.", "Die Kontoart bestimmt, welche Topics gelesen und geschrieben werden dürfen.", "Le type de compte décide quels topics il peut lire et écrire.", "Il tipo di account decide quali topic può leggere e scrivere.", "アカウントの種類によって、読み書きできるトピックが決まります。", "账户类型决定其可读写的主题。"],
  adm_name: ["The name of the node or device. The account is called after it, for example field-node-nodo-radar-2.", "El nombre del nodo o dispositivo. La cuenta se llama según él, por ejemplo field-node-nodo-radar-2.", "Der Name des Knotens oder Geräts. Das Konto heißt danach, z. B. field-node-nodo-radar-2.", "Le nom du nœud ou de l'appareil. Le compte porte ce nom, par exemple field-node-nodo-radar-2.", "Il nome del nodo o dispositivo. L'account si chiama di conseguenza, ad esempio field-node-nodo-radar-2.", "ノードまたは機器の名前。アカウント名はこれに基づきます（例：field-node-nodo-radar-2）。", "节点或设备的名称，账户以此命名，例如 field-node-nodo-radar-2。"],
  adm_add_account: ["Makes the account and shows its password once.", "Crea la cuenta y muestra su contraseña una sola vez.", "Legt das Konto an und zeigt das Passwort einmalig.", "Crée le compte et montre son mot de passe une seule fois.", "Crea l'account e mostra la sua password una sola volta.", "アカウントを作成し、パスワードを 1 度だけ表示します。", "创建账户并仅显示一次密码。"],
  adm_remove: ["Removes the account from the broker. The node or device that uses it can no longer connect.", "Quita la cuenta del broker. El nodo o dispositivo que la usa ya no podrá conectarse.", "Entfernt das Konto aus dem Broker. Der Knoten oder das Gerät kann sich nicht mehr verbinden.", "Supprime le compte du broker. Le nœud ou l'appareil qui l'utilise ne pourra plus se connecter.", "Rimuove l'account dal broker. Il nodo o dispositivo che lo usa non potrà più connettersi.", "ブローカーからアカウントを削除します。それを使うノードや機器は接続できなくなります。", "从代理中删除账户，使用它的节点或设备将无法再连接。"],
  adm_adopt: ["Makes this node's broker account and writes it into the node, so it starts reporting by itself.", "Crea la cuenta del broker de este nodo y la escribe en el nodo, para que empiece a informar solo.", "Legt das Broker-Konto dieses Knotens an und schreibt es in den Knoten, damit er von selbst zu melden beginnt.", "Crée le compte broker de ce nœud et l'écrit dans le nœud, pour qu'il commence à rapporter seul.", "Crea l'account broker di questo nodo e lo scrive nel nodo, così inizia a riferire da solo.", "このノードのブローカーアカウントを作成してノードに書き込み、自動で報告を始めさせます。", "为此节点创建代理账户并写入节点，使其自动开始上报。"],
  adm_adopt_go: ["Makes the account and, with the login of the node's panel, writes the broker settings into the node and restarts it.", "Crea la cuenta y, con el acceso al panel del nodo, escribe los ajustes del broker en el nodo y lo reinicia.", "Legt das Konto an und schreibt mit dem Zugang zum Knoten-Panel die Broker-Einstellungen in den Knoten und startet ihn neu.", "Crée le compte et, avec l'identifiant du panneau du nœud, écrit les réglages du broker dans le nœud et le redémarre.", "Crea l'account e, con l'accesso al pannello del nodo, scrive le impostazioni del broker nel nodo e lo riavvia.", "アカウントを作成し、ノードのパネルのログイン情報でブローカー設定をノードに書き込んで再起動します。", "创建账户，并用节点面板的登录信息把代理设置写入节点后重启。"],
  adm_adopt_user: ["The administrator user of the node's own web panel. It is used once and never kept.", "El usuario administrador del panel web del propio nodo. Se usa una vez y no se guarda.", "Der Administrator-Benutzer des eigenen Web-Panels des Knotens. Er wird einmal genutzt und nie gespeichert.", "L'utilisateur administrateur du panneau web du nœud. Il est utilisé une fois et jamais conservé.", "L'utente amministratore del pannello web del nodo. Viene usato una volta e mai conservato.", "ノード自身の Web パネルの管理者ユーザー。1 回だけ使用し、保存しません。", "节点自身网页面板的管理员用户，仅使用一次，不会保存。"],
  adm_adopt_password: ["The password of the node's own web panel. It is used once and never kept; leave it empty to type the account into the node yourself.", "La contraseña del panel web del propio nodo. Se usa una vez y no se guarda; déjala vacía para escribir tú la cuenta en el nodo.", "Das Passwort des eigenen Web-Panels des Knotens. Es wird einmal genutzt und nie gespeichert; leer lassen, um das Konto selbst im Knoten einzutragen.", "Le mot de passe du panneau web du nœud. Il est utilisé une fois et jamais conservé ; laissez vide pour saisir vous-même le compte dans le nœud.", "La password del pannello web del nodo. Viene usata una volta e mai conservata; lascia vuoto per scrivere tu l'account nel nodo.", "ノード自身の Web パネルのパスワード。1 回だけ使用し、保存しません。空欄にすると、アカウントを自分でノードに入力します。", "节点自身网页面板的密码，仅使用一次，不会保存；留空则由你自己在节点中输入账户。"],
  adm_adopt_broker: ["The address the node will use to reach the broker: it has to be reachable from the node, so use the machine's address on the network.", "La dirección que usará el nodo para llegar al broker: debe ser alcanzable desde el nodo, así que usa la dirección de la máquina en la red.", "Die Adresse, mit der der Knoten den Broker erreicht: Sie muss vom Knoten aus erreichbar sein, verwenden Sie also die Netzadresse des Rechners.", "L'adresse que le nœud utilisera pour joindre le broker : elle doit être joignable depuis le nœud, utilisez donc l'adresse de la machine sur le réseau.", "L'indirizzo che il nodo userà per raggiungere il broker: deve essere raggiungibile dal nodo, quindi usa l'indirizzo della macchina nella rete.", "ノードがブローカーに接続するアドレス。ノードから到達できる必要があるため、ネットワーク上のマシンのアドレスを使います。", "节点用来访问代理的地址：必须能从节点访问，因此请使用本机在网络中的地址。"],
};
