/**
 * Interface text of the Network menu and the Network Designer, one row per phrase: English, Spanish, German, French, Italian, Japanese, Chinese.
 * `net_` phrases are the menu, `netkind_` the kinds of device, `netev_` the events (with {0}, {1} ... for the names and figures), `netstate_` the state of the
 * internet, `alarm_network_` the alarms the server raises about the network, and `nd_` the Network Designer.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
 */
import { cataloguesFromRows, type Row, type RowCatalogues } from "./catalogueRows";

const ROWS: Record<string, Row> = {
  // ---- the menu in the sidebar ----
  network: ["Network", "Red", "Netzwerk", "Réseau", "Rete", "ネットワーク", "网络"],
  networkDesigner: ["Network Designer", "Diseñador de red", "Netzwerkplaner", "Concepteur de réseau", "Progettista di rete", "ネットワーク設計", "网络设计器"],
  navNetwork: ["Network", "Red", "Netzwerk", "Réseau", "Rete", "ネットワーク", "网络"],
  // ---- headings and tabs ----
  net_title: ["THE LOCAL NETWORK", "LA RED LOCAL", "DAS LOKALE NETZWERK", "LE RÉSEAU LOCAL", "LA RETE LOCALE", "ローカルネットワーク", "本地网络"],
  net_help: ["The devices on the house's network, whether the internet is there and what changes. It only observes: nothing here changes any device.", "Los dispositivos de la red de la casa, si hay internet y qué cambia. Solo observa: nada de aquí modifica ningún dispositivo.", "Die Geräte im Netzwerk des Hauses, ob das Internet da ist und was sich ändert. Es beobachtet nur: nichts hier verändert ein Gerät.", "Les appareils du réseau de la maison, si internet est là et ce qui change. Il observe seulement : rien ici ne modifie un appareil.", "I dispositivi della rete di casa, se internet c'è e cosa cambia. Osserva soltanto: nulla qui modifica un dispositivo.", "家庭ネットワーク上の機器、インターネットの有無、そして変化を表示します。観測するだけで、ここから機器を変更することはありません。", "家中网络上的设备、互联网是否可用以及有什么变化。只做观察：这里不会改变任何设备。"],
  net_tab_devices: ["Devices", "Dispositivos", "Geräte", "Appareils", "Dispositivi", "デバイス", "设备"],
  net_tab_internet: ["Internet", "Internet", "Internet", "Internet", "Internet", "インターネット", "互联网"],
  net_tab_traffic: ["Traffic", "Tráfico", "Datenverkehr", "Trafic", "Traffico", "トラフィック", "流量"],
  net_tab_events: ["Events", "Eventos", "Ereignisse", "Événements", "Eventi", "イベント", "事件"],
  net_no_nodes: ["No ARMOR-NETWORK node has reported yet. Start one on a machine of the network (armor-network watch).", "Ningún nodo ARMOR-NETWORK ha informado todavía. Arranca uno en una máquina de la red (armor-network watch).", "Noch kein ARMOR-NETWORK-Knoten hat sich gemeldet. Starten Sie einen auf einem Rechner des Netzwerks (armor-network watch).", "Aucun nœud ARMOR-NETWORK n'a encore rapporté. Lancez-en un sur une machine du réseau (armor-network watch).", "Nessun nodo ARMOR-NETWORK ha ancora riferito. Avviane uno su una macchina della rete (armor-network watch).", "ARMOR-NETWORK ノードからの報告はまだありません。ネットワーク上のマシンで起動してください（armor-network watch）。", "尚无 ARMOR-NETWORK 节点上报。请在网络中的一台机器上启动一个（armor-network watch）。"],
  net_node_stale: ["This node has stopped reporting: what is shown is what it last saw.", "Este nodo ha dejado de informar: lo que se muestra es lo último que vio.", "Dieser Knoten meldet sich nicht mehr: gezeigt wird, was er zuletzt sah.", "Ce nœud ne rapporte plus : ce qui est montré est ce qu'il a vu en dernier.", "Questo nodo ha smesso di riferire: ciò che si vede è l'ultima cosa che ha visto.", "このノードは報告を停止しています。表示は最後に見た内容です。", "该节点已停止上报：显示的是它最后看到的内容。"],
  // ---- the internet ----
  net_internet: ["Internet", "Internet", "Internet", "Internet", "Internet", "インターネット", "互联网"],
  netstate_up: ["The internet is up", "Hay internet", "Das Internet ist erreichbar", "Internet fonctionne", "Internet funziona", "インターネットは正常です", "互联网正常"],
  netstate_degraded: ["The internet is slow or losing packets", "Internet va lento o pierde paquetes", "Das Internet ist langsam oder verliert Pakete", "Internet est lent ou perd des paquets", "Internet è lento o perde pacchetti", "インターネットが遅いかパケットが失われています", "互联网变慢或丢包"],
  netstate_down: ["No internet: the router answers and nothing beyond it does", "Sin internet: el router responde y nada más allá responde", "Kein Internet: der Router antwortet, dahinter antwortet nichts", "Pas d'internet : le routeur répond et rien au-delà ne répond", "Niente internet: il router risponde e nulla oltre risponde", "インターネット不通：ルーターは応答しますが、その先は応答しません", "无法上网：路由器有响应，但其后没有任何响应"],
  netstate_lan_down: ["The local network is down: the router does not answer", "La red local ha caído: el router no responde", "Das lokale Netzwerk ist ausgefallen: der Router antwortet nicht", "Le réseau local est tombé : le routeur ne répond pas", "La rete locale è caduta: il router non risponde", "ローカルネットワーク障害：ルーターが応答しません", "本地网络中断：路由器没有响应"],
  netstate_unknown: ["Checking the internet…", "Comprobando internet…", "Internet wird geprüft …", "Vérification d'internet…", "Verifica di internet…", "インターネットを確認しています…", "正在检查互联网…"],
  netstate_hint_down: ["The fault is beyond the router: the provider, the line or the router's own connection.", "La avería está más allá del router: el operador, la línea o la conexión del propio router.", "Die Störung liegt hinter dem Router: Anbieter, Leitung oder die eigene Verbindung des Routers.", "La panne est au-delà du routeur : le fournisseur, la ligne ou la connexion du routeur.", "Il guasto è oltre il router: il gestore, la linea o la connessione del router.", "障害はルーターの先にあります：プロバイダー、回線、またはルーター自身の接続。", "故障在路由器之外：运营商、线路或路由器自身的连接。"],
  netstate_hint_lan_down: ["The fault is on this side: the router is off, a cable or a switch, or the machine of the node.", "La avería está de este lado: el router apagado, un cable o un conmutador, o la máquina del nodo.", "Die Störung liegt auf dieser Seite: Router aus, ein Kabel oder Switch, oder der Rechner des Knotens.", "La panne est de ce côté : routeur éteint, un câble ou un commutateur, ou la machine du nœud.", "Il guasto è da questa parte: router spento, un cavo o uno switch, o la macchina del nodo.", "障害はこちら側です：ルーターの電源、ケーブルやスイッチ、またはノードのマシン。", "故障在本地一侧：路由器关机、线缆或交换机，或节点所在的机器。"],
  net_latency: ["Latency", "Latencia", "Latenz", "Latence", "Latenza", "遅延", "延迟"],
  net_loss: ["Loss", "Pérdida", "Verlust", "Perte", "Perdita", "損失", "丢包"],
  net_since: ["Since", "Desde", "Seit", "Depuis", "Da", "開始", "自"],
  net_outages24: ["Outages, 24 h", "Cortes, 24 h", "Ausfälle, 24 h", "Coupures, 24 h", "Interruzioni, 24 h", "停止回数（24時間）", "中断次数（24 小时）"],
  net_downtime24: ["Without internet, 24 h", "Sin internet, 24 h", "Ohne Internet, 24 h", "Sans internet, 24 h", "Senza internet, 24 h", "インターネット不通（24時間）", "断网时间（24 小时）"],
  net_probes: ["What is asked", "Qué se pregunta", "Was gefragt wird", "Ce qui est demandé", "Cosa si chiede", "確認内容", "检测项目"],
  net_probe_target: ["Target", "Destino", "Ziel", "Cible", "Destinazione", "宛先", "目标"],
  net_probe_kind: ["Kind", "Tipo", "Art", "Type", "Tipo", "種類", "类型"],
  net_probe_result: ["Result", "Resultado", "Ergebnis", "Résultat", "Risultato", "結果", "结果"],
  net_probe_ok: ["answers", "responde", "antwortet", "répond", "risponde", "応答あり", "有响应"],
  net_probe_fail: ["no answer", "sin respuesta", "keine Antwort", "pas de réponse", "nessuna risposta", "応答なし", "无响应"],
  net_router: ["Router", "Router", "Router", "Routeur", "Router", "ルーター", "路由器"],
  net_router_ok: ["answers", "responde", "antwortet", "répond", "risponde", "応答あり", "有响应"],
  net_router_no: ["does not answer", "no responde", "antwortet nicht", "ne répond pas", "non risponde", "応答なし", "无响应"],
  net_outages: ["Outages", "Cortes", "Ausfälle", "Coupures", "Interruzioni", "停止履歴", "中断记录"],
  net_no_outages: ["No outage since the server has been watching.", "Ningún corte desde que el servidor vigila.", "Kein Ausfall, seit der Server beobachtet.", "Aucune coupure depuis que le serveur surveille.", "Nessuna interruzione da quando il server osserva.", "サーバーが監視を始めてから停止はありません。", "自服务器开始监控以来没有中断。"],
  net_outage_when: ["Began", "Empezó", "Begann", "Début", "Inizio", "開始", "开始"],
  net_outage_len: ["Lasted", "Duró", "Dauer", "Durée", "Durata", "継続", "持续"],
  net_outage_kind: ["What failed", "Qué falló", "Was ausfiel", "Ce qui a failli", "Cosa è mancato", "対象", "故障对象"],
  net_outage_internet: ["The internet", "Internet", "Das Internet", "Internet", "Internet", "インターネット", "互联网"],
  net_outage_gateway: ["The router", "El router", "Der Router", "Le routeur", "Il router", "ルーター", "路由器"],
  net_chart_latency: ["Latency (ms)", "Latencia (ms)", "Latenz (ms)", "Latence (ms)", "Latenza (ms)", "遅延 (ms)", "延迟 (ms)"],
  net_chart_loss: ["Loss (%)", "Pérdida (%)", "Verlust (%)", "Perte (%)", "Perdita (%)", "損失 (%)", "丢包 (%)"],
  net_chart_empty: ["Not enough samples yet.", "Todavía no hay suficientes muestras.", "Noch nicht genug Messwerte.", "Pas encore assez d'échantillons.", "Ancora pochi campioni.", "サンプルがまだ足りません。", "样本还不够。"],
  // ---- the network itself ----
  net_interface: ["Interface", "Interfaz", "Schnittstelle", "Interface", "Interfaccia", "インターフェース", "接口"],
  net_network: ["Network", "Red", "Netzwerk", "Réseau", "Rete", "ネットワーク", "网络"],
  net_devices: ["Devices", "Dispositivos", "Geräte", "Appareils", "Dispositivi", "デバイス", "设备"],
  net_online: ["online", "en línea", "online", "en ligne", "online", "オンライン", "在线"],
  net_offline: ["offline", "sin conexión", "offline", "hors ligne", "offline", "オフライン", "离线"],
  net_not_known: ["not marked as known", "sin marcar como conocidos", "nicht als bekannt markiert", "non marqués comme connus", "non segnati come noti", "未確認", "未标记为已知"],
  net_last_scan: ["Last scan", "Último barrido", "Letzter Scan", "Dernier balayage", "Ultima scansione", "最終スキャン", "最近一次扫描"],
  net_scan_hosts: ["addresses looked at", "direcciones examinadas", "Adressen untersucht", "adresses examinées", "indirizzi esaminati", "確認したアドレス", "已检查的地址"],
  // ---- the devices ----
  net_search: ["Search by name, address, MAC or maker", "Buscar por nombre, dirección, MAC o fabricante", "Suchen nach Name, Adresse, MAC oder Hersteller", "Rechercher par nom, adresse, MAC ou fabricant", "Cerca per nome, indirizzo, MAC o produttore", "名前・アドレス・MAC・メーカーで検索", "按名称、地址、MAC 或厂商搜索"],
  net_all_kinds: ["All kinds", "Todos los tipos", "Alle Arten", "Tous les types", "Tutti i tipi", "すべての種類", "所有类型"],
  net_only_unknown: ["Not known", "Sin conocer", "Nicht bekannt", "Non connus", "Non noti", "未確認のみ", "仅未知"],
  net_only_offline: ["Offline", "Sin conexión", "Offline", "Hors ligne", "Offline", "オフラインのみ", "仅离线"],
  net_col_status: ["State", "Estado", "Zustand", "État", "Stato", "状態", "状态"],
  net_col_name: ["Name", "Nombre", "Name", "Nom", "Nome", "名前", "名称"],
  net_col_address: ["Address", "Dirección", "Adresse", "Adresse", "Indirizzo", "アドレス", "地址"],
  net_col_mac: ["MAC", "MAC", "MAC", "MAC", "MAC", "MAC", "MAC"],
  net_col_kind: ["Kind", "Tipo", "Art", "Type", "Tipo", "種類", "类型"],
  net_col_maker: ["Maker", "Fabricante", "Hersteller", "Fabricant", "Produttore", "メーカー", "厂商"],
  net_col_ports: ["Open ports", "Puertos abiertos", "Offene Ports", "Ports ouverts", "Porte aperte", "開放ポート", "开放端口"],
  net_col_seen: ["Last seen", "Visto por última vez", "Zuletzt gesehen", "Vu pour la dernière fois", "Visto l'ultima volta", "最終確認", "最后看到"],
  net_col_latency: ["Latency", "Latencia", "Latenz", "Latence", "Latenza", "遅延", "延迟"],
  net_none_found: ["No device matches.", "Ningún dispositivo coincide.", "Kein Gerät passt.", "Aucun appareil ne correspond.", "Nessun dispositivo corrisponde.", "該当するデバイスはありません。", "没有匹配的设备。"],
  net_known: ["known", "conocido", "bekannt", "connu", "noto", "確認済み", "已知"],
  net_new: ["not known", "sin conocer", "nicht bekannt", "non connu", "non noto", "未確認", "未知"],
  net_this_machine: ["this machine", "esta máquina", "dieser Rechner", "cette machine", "questa macchina", "このマシン", "本机"],
  netkind_router: ["Router", "Router", "Router", "Routeur", "Router", "ルーター", "路由器"],
  netkind_computer: ["Computer", "Ordenador", "Computer", "Ordinateur", "Computer", "コンピューター", "电脑"],
  netkind_phone: ["Phone or tablet", "Móvil o tableta", "Handy oder Tablet", "Téléphone ou tablette", "Telefono o tablet", "スマホ・タブレット", "手机或平板"],
  netkind_tv: ["TV or player", "TV o reproductor", "Fernseher oder Player", "TV ou lecteur", "TV o lettore", "テレビ・プレーヤー", "电视或播放器"],
  netkind_printer: ["Printer", "Impresora", "Drucker", "Imprimante", "Stampante", "プリンター", "打印机"],
  netkind_camera: ["Camera", "Cámara", "Kamera", "Caméra", "Telecamera", "カメラ", "摄像头"],
  netkind_iot: ["Smart device", "Dispositivo inteligente", "Smart-Gerät", "Appareil connecté", "Dispositivo smart", "スマートデバイス", "智能设备"],
  netkind_server: ["Server", "Servidor", "Server", "Serveur", "Server", "サーバー", "服务器"],
  netkind_nas: ["Storage (NAS)", "Almacenamiento (NAS)", "Speicher (NAS)", "Stockage (NAS)", "Archiviazione (NAS)", "ストレージ (NAS)", "存储 (NAS)"],
  netkind_network: ["Network equipment", "Equipo de red", "Netzwerkgerät", "Équipement réseau", "Apparato di rete", "ネットワーク機器", "网络设备"],
  netkind_unknown: ["Unknown", "Desconocido", "Unbekannt", "Inconnu", "Sconosciuto", "不明", "未知"],
  // ---- one device ----
  net_detail: ["Device", "Dispositivo", "Gerät", "Appareil", "Dispositivo", "デバイス", "设备"],
  net_hostname: ["Name on the network", "Nombre en la red", "Name im Netzwerk", "Nom sur le réseau", "Nome in rete", "ネットワーク上の名前", "网络中的名称"],
  net_random_mac: ["random address: the device changes it on purpose, so it is not an identity", "dirección aleatoria: el dispositivo la cambia a propósito, así que no es una identidad", "zufällige Adresse: das Gerät ändert sie absichtlich, sie ist also keine Identität", "adresse aléatoire : l'appareil la change exprès, ce n'est donc pas une identité", "indirizzo casuale: il dispositivo lo cambia apposta, quindi non è un'identità", "ランダムアドレス：機器が意図的に変更するため、識別情報ではありません", "随机地址：设备会有意更改，因此不能作为身份"],
  net_os: ["Operating system (a guess)", "Sistema operativo (una suposición)", "Betriebssystem (eine Vermutung)", "Système d'exploitation (une supposition)", "Sistema operativo (una supposizione)", "OS（推定）", "操作系统（推测）"],
  net_first_seen: ["First seen", "Visto por primera vez", "Zuerst gesehen", "Vu pour la première fois", "Visto la prima volta", "初回確認", "首次看到"],
  net_ports: ["Open ports", "Puertos abiertos", "Offene Ports", "Ports ouverts", "Porte aperte", "開放ポート", "开放端口"],
  net_no_ports: ["No open port among those looked at.", "Ningún puerto abierto entre los examinados.", "Kein offener Port unter den untersuchten.", "Aucun port ouvert parmi ceux examinés.", "Nessuna porta aperta tra quelle esaminate.", "確認したポートに開放されたものはありません。", "已检查的端口中没有开放的。"],
  net_risky_port: ["a port a house rarely wants open", "un puerto que una casa rara vez quiere abierto", "ein Port, den ein Haus selten offen haben will", "un port qu'une maison veut rarement ouvert", "una porta che una casa raramente vuole aperta", "家庭ではあまり開けたくないポート", "家庭很少需要开放的端口"],
  net_services: ["Announces", "Anuncia", "Kündigt an", "Annonce", "Annuncia", "公開しているサービス", "对外宣告"],
  net_guess_note: ["The kind, the system and the maker are guesses from the address, the answers and the maker's block of the MAC.", "El tipo, el sistema y el fabricante son suposiciones a partir de la dirección, las respuestas y el bloque del fabricante en la MAC.", "Art, System und Hersteller sind Vermutungen aus Adresse, Antworten und Herstellerblock der MAC.", "Le type, le système et le fabricant sont des suppositions d'après l'adresse, les réponses et le bloc du fabricant dans la MAC.", "Tipo, sistema e produttore sono supposizioni dall'indirizzo, dalle risposte e dal blocco del produttore nel MAC.", "種類・OS・メーカーは、アドレス、応答、MAC のメーカーブロックからの推測です。", "类型、系统和厂商是根据地址、响应和 MAC 的厂商段推测的。"],
  net_edit: ["What you know about it", "Lo que sabes de él", "Was Sie darüber wissen", "Ce que vous en savez", "Quello che ne sai", "あなたの情報", "您已知的信息"],
  net_name: ["Name", "Nombre", "Name", "Nom", "Nome", "名前", "名称"],
  net_notes: ["Notes", "Notas", "Notizen", "Notes", "Note", "メモ", "备注"],
  net_trusted: ["It is known and welcome on the network", "Es conocido y bienvenido en la red", "Es ist bekannt und im Netzwerk willkommen", "Il est connu et bienvenu sur le réseau", "È noto e benvenuto in rete", "既知の機器として許可", "已知并允许接入网络"],
  net_kind_own: ["Kind (your own)", "Tipo (el tuyo)", "Art (eigene)", "Type (le vôtre)", "Tipo (il tuo)", "種類（手動）", "类型（自定义）"],
  net_kind_auto: ["as guessed", "el supuesto", "wie vermutet", "comme supposé", "come ipotizzato", "推定のまま", "按推测"],
  net_save: ["Save", "Guardar", "Speichern", "Enregistrer", "Salva", "保存", "保存"],
  net_forget: ["Forget what I noted", "Olvidar lo anotado", "Notizen vergessen", "Oublier mes notes", "Dimentica le note", "メモを削除", "忘记我的备注"],
  net_saved: ["Saved.", "Guardado.", "Gespeichert.", "Enregistré.", "Salvato.", "保存しました。", "已保存。"],
  net_failed: ["It could not be saved.", "No se ha podido guardar.", "Es konnte nicht gespeichert werden.", "Impossible d'enregistrer.", "Impossibile salvare.", "保存できませんでした。", "无法保存。"],
  net_admin_only: ["Only an administrator can name devices or mark them as known.", "Solo un administrador puede poner nombre a los dispositivos o marcarlos como conocidos.", "Nur ein Administrator kann Geräte benennen oder als bekannt markieren.", "Seul un administrateur peut nommer les appareils ou les marquer comme connus.", "Solo un amministratore può dare un nome ai dispositivi o segnarli come noti.", "デバイスの命名や既知の設定は管理者のみ可能です。", "只有管理员可以命名设备或将其标记为已知。"],
  // ---- traffic ----
  net_rx: ["Received", "Recibido", "Empfangen", "Reçu", "Ricevuto", "受信", "接收"],
  net_tx: ["Sent", "Enviado", "Gesendet", "Envoyé", "Inviato", "送信", "发送"],
  net_traffic_note: ["The traffic of the node's interface (the sum of the interfaces on Windows), not of each device: that needs the router's counters.", "El tráfico de la interfaz del nodo (la suma de las interfaces en Windows), no el de cada dispositivo: eso requiere los contadores del router.", "Der Datenverkehr der Schnittstelle des Knotens (unter Windows die Summe der Schnittstellen), nicht je Gerät: dafür braucht es die Zähler des Routers.", "Le trafic de l'interface du nœud (la somme des interfaces sous Windows), pas celui de chaque appareil : cela demande les compteurs du routeur.", "Il traffico dell'interfaccia del nodo (la somma delle interfacce su Windows), non di ogni dispositivo: servono i contatori del router.", "ノードのインターフェースのトラフィック（Windows では全インターフェースの合計）で、機器ごとではありません。機器ごとにはルーターのカウンターが必要です。", "节点接口的流量（Windows 上为各接口之和），不是每台设备的流量：那需要路由器的计数器。"],
  net_chart_rx: ["Received (Mbit/s)", "Recibido (Mbit/s)", "Empfangen (Mbit/s)", "Reçu (Mbit/s)", "Ricevuto (Mbit/s)", "受信 (Mbit/s)", "接收 (Mbit/s)"],
  net_chart_tx: ["Sent (Mbit/s)", "Enviado (Mbit/s)", "Gesendet (Mbit/s)", "Envoyé (Mbit/s)", "Inviato (Mbit/s)", "送信 (Mbit/s)", "发送 (Mbit/s)"],
  // ---- events ----
  net_events: ["What changed", "Qué ha cambiado", "Was sich geändert hat", "Ce qui a changé", "Cosa è cambiato", "変化", "变化"],
  net_no_events: ["Nothing has changed since the server has been watching.", "No ha cambiado nada desde que el servidor vigila.", "Nichts hat sich geändert, seit der Server beobachtet.", "Rien n'a changé depuis que le serveur surveille.", "Nulla è cambiato da quando il server osserva.", "サーバーが監視を始めてから変化はありません。", "自服务器开始监控以来没有变化。"],
  netev_new_device: ["A device that was never seen has appeared: {0}", "Ha aparecido un dispositivo que nunca se había visto: {0}", "Ein nie gesehenes Gerät ist aufgetaucht: {0}", "Un appareil jamais vu est apparu : {0}", "È comparso un dispositivo mai visto: {0}", "未確認のデバイスが現れました：{0}", "出现了从未见过的设备：{0}"],
  netev_device_online: ["{0} is back", "{0} ha vuelto", "{0} ist wieder da", "{0} est de retour", "{0} è tornato", "{0} が復帰しました", "{0} 已恢复"],
  netev_device_offline: ["{0} stopped answering", "{0} ha dejado de responder", "{0} antwortet nicht mehr", "{0} ne répond plus", "{0} non risponde più", "{0} が応答しなくなりました", "{0} 不再响应"],
  netev_ip_changed: ["{0} changed its address", "{0} ha cambiado de dirección", "{0} hat seine Adresse geändert", "{0} a changé d'adresse", "{0} ha cambiato indirizzo", "{0} のアドレスが変わりました", "{0} 更改了地址"],
  netev_arp_conflict: ["Two machines answer for one address: {0}", "Dos máquinas responden por una misma dirección: {0}", "Zwei Rechner antworten für eine Adresse: {0}", "Deux machines répondent pour une même adresse : {0}", "Due macchine rispondono per lo stesso indirizzo: {0}", "1 つのアドレスに 2 台が応答しています：{0}", "两台机器响应同一个地址：{0}"],
  netev_port_opened: ["{0} opened port {1}", "{0} ha abierto el puerto {1}", "{0} hat Port {1} geöffnet", "{0} a ouvert le port {1}", "{0} ha aperto la porta {1}", "{0} がポート {1} を開きました", "{0} 打开了端口 {1}"],
  netev_port_closed: ["{0} closed port {1}", "{0} ha cerrado el puerto {1}", "{0} hat Port {1} geschlossen", "{0} a fermé le port {1}", "{0} ha chiuso la porta {1}", "{0} がポート {1} を閉じました", "{0} 关闭了端口 {1}"],
  netev_internet_down: ["The internet went down", "Se cayó internet", "Das Internet ist ausgefallen", "Internet est tombé", "Internet è caduto", "インターネットが切れました", "互联网中断"],
  netev_internet_up: ["The internet is back after {0}", "Vuelve internet tras {0}", "Das Internet ist zurück nach {0}", "Internet est de retour après {0}", "Internet è tornato dopo {0}", "{0} 後にインターネットが復旧しました", "互联网在 {0} 后恢复"],
  netev_gateway_down: ["The router stopped answering", "El router ha dejado de responder", "Der Router antwortet nicht mehr", "Le routeur ne répond plus", "Il router non risponde più", "ルーターが応答しなくなりました", "路由器不再响应"],
  netev_gateway_up: ["The router answers again", "El router vuelve a responder", "Der Router antwortet wieder", "Le routeur répond de nouveau", "Il router risponde di nuovo", "ルーターが再び応答しています", "路由器恢复响应"],
  // ---- alarms the server raises ----
  alarm_network_internet_down: ["The internet is down and the router still answers: the provider's side", "No hay internet y el router sigue respondiendo: es cosa del operador", "Das Internet ist ausgefallen und der Router antwortet noch: Seite des Anbieters", "Internet est coupé et le routeur répond encore : côté fournisseur", "Internet è caduto e il router risponde ancora: lato gestore", "インターネットが不通です（ルーターは応答）：プロバイダー側", "互联网中断，但路由器仍有响应：运营商一侧"],
  alarm_network_lan_down: ["The local network is down: the router does not answer", "La red local está caída: el router no responde", "Das lokale Netzwerk ist ausgefallen: der Router antwortet nicht", "Le réseau local est tombé : le routeur ne répond pas", "La rete locale è caduta: il router non risponde", "ローカルネットワークが停止：ルーターが応答しません", "本地网络中断：路由器没有响应"],
  alarm_network_degraded: ["The internet is slow or losing packets", "Internet va lento o pierde paquetes", "Das Internet ist langsam oder verliert Pakete", "Internet est lent ou perd des paquets", "Internet è lento o perde pacchetti", "インターネットが遅いかパケットが失われています", "互联网变慢或丢包"],
  alarm_network_new_device: ["A device that was never seen has joined the network", "Un dispositivo que nunca se había visto se ha unido a la red", "Ein nie gesehenes Gerät ist dem Netzwerk beigetreten", "Un appareil jamais vu a rejoint le réseau", "Un dispositivo mai visto si è unito alla rete", "未確認のデバイスがネットワークに参加しました", "从未见过的设备加入了网络"],
  alarm_network_arp_conflict: ["Two machines answer for one address on the network", "Dos máquinas responden por una misma dirección de la red", "Zwei Rechner antworten für dieselbe Adresse im Netzwerk", "Deux machines répondent pour une même adresse du réseau", "Due macchine rispondono per lo stesso indirizzo di rete", "ネットワーク上で 1 つのアドレスに 2 台が応答しています", "网络上有两台机器响应同一个地址"],
  alarm_network_port_opened: ["A device on the network opened a port", "Un dispositivo de la red ha abierto un puerto", "Ein Gerät im Netzwerk hat einen Port geöffnet", "Un appareil du réseau a ouvert un port", "Un dispositivo della rete ha aperto una porta", "ネットワーク上の機器がポートを開きました", "网络上的设备打开了一个端口"],
  alarm_network_offline: ["A network node stopped reporting", "Un nodo de red ha dejado de informar", "Ein Netzwerkknoten meldet sich nicht mehr", "Un nœud réseau ne rapporte plus", "Un nodo di rete ha smesso di riferire", "ネットワークノードが報告を停止しました", "网络节点停止上报"],
  alarm_network_watched_online: ["A device you asked to watch has come onto the network", "Un dispositivo que pediste vigilar ha entrado en la red", "Ein Gerät, das Sie überwachen wollten, ist ins Netzwerk gekommen", "Un appareil que vous surveilliez est arrivé sur le réseau", "Un dispositivo che volevi sorvegliare è entrato in rete", "監視を依頼したデバイスがネットワークに参加しました", "您要求监视的设备已接入网络"],
  // ---- the Network Designer ----
  nd_title: ["The house's network: line, router, switches and everything that hangs from them", "La red de la casa: línea, router, conmutadores y todo lo que cuelga de ellos", "Das Netzwerk des Hauses: Anschluss, Router, Switches und alles, was daran hängt", "Le réseau de la maison : ligne, routeur, commutateurs et tout ce qui y est relié", "La rete di casa: linea, router, switch e tutto ciò che vi è collegato", "家庭ネットワーク：回線、ルーター、スイッチ、接続されたすべての機器", "家中的网络：线路、路由器、交换机以及连接的所有设备"],
  nd_help: ["Draw the provider's line, the router, the switches and access points and every device, join their ports with links and let the checks read the drawing. It can also draw what the nodes found on the network and tell what is drawn and not there. It is a drawing: it configures nothing.", "Dibuja la línea del operador, el router, los conmutadores y puntos de acceso y cada dispositivo, une sus puertos con enlaces y deja que las comprobaciones lean el dibujo. También puede dibujar lo que los nodos encontraron en la red y decirte qué está dibujado y no está. Es un dibujo: no configura nada.", "Zeichnen Sie Anbieterleitung, Router, Switches, Access Points und jedes Gerät, verbinden Sie ihre Anschlüsse mit Verbindungen und lassen Sie die Prüfungen die Zeichnung lesen. Es kann auch zeichnen, was die Knoten im Netzwerk gefunden haben, und sagen, was gezeichnet ist und nicht da ist. Es ist eine Zeichnung: es konfiguriert nichts.", "Dessinez la ligne du fournisseur, le routeur, les commutateurs, les points d'accès et chaque appareil, reliez leurs ports par des liens et laissez les contrôles lire le dessin. Il peut aussi dessiner ce que les nœuds ont trouvé sur le réseau et dire ce qui est dessiné et absent. C'est un dessin : il ne configure rien.", "Disegna la linea del gestore, il router, gli switch, i punti di accesso e ogni dispositivo, collega le loro porte con i collegamenti e lascia che i controlli leggano il disegno. Può anche disegnare ciò che i nodi hanno trovato in rete e dire cosa è disegnato e non c'è. È un disegno: non configura nulla.", "プロバイダー回線、ルーター、スイッチ、アクセスポイント、各機器を描き、ポートをリンクでつなぐと、チェックが図面を読みます。ノードがネットワークで見つけた機器を描くことも、描かれているのに存在しないものを示すこともできます。これは図面であり、何も設定しません。", "绘制运营商线路、路由器、交换机、接入点和每台设备，用链路连接端口，检查功能会读取图纸。它还能绘制节点在网络中发现的设备，并指出哪些已绘制但不存在。这只是一张图：不会配置任何东西。"],
  ndc_wan: ["The outside", "El exterior", "Draußen", "L'extérieur", "L'esterno", "外部", "外部"],
  ndc_core: ["The core of the network", "El núcleo de la red", "Der Kern des Netzwerks", "Le cœur du réseau", "Il cuore della rete", "ネットワークの中核", "网络核心"],
  ndc_endpoint: ["Devices", "Dispositivos", "Geräte", "Appareils", "Dispositivi", "デバイス", "设备"],
  ndc_service: ["A.R.M.O.R.", "A.R.M.O.R.", "A.R.M.O.R.", "A.R.M.O.R.", "A.R.M.O.R.", "A.R.M.O.R.", "A.R.M.O.R."],
  ndk_internet: ["Internet line", "Línea de internet", "Internetanschluss", "Ligne internet", "Linea internet", "インターネット回線", "互联网线路"],
  ndk_modem: ["Modem / ONT", "Módem / ONT", "Modem / ONT", "Modem / ONT", "Modem / ONT", "モデム / ONU", "调制解调器 / ONT"],
  ndk_router: ["Router", "Router", "Router", "Routeur", "Router", "ルーター", "路由器"],
  ndk_firewall: ["Firewall", "Cortafuegos", "Firewall", "Pare-feu", "Firewall", "ファイアウォール", "防火墙"],
  ndk_switch: ["Switch", "Conmutador", "Switch", "Commutateur", "Switch", "スイッチ", "交换机"],
  "ndk_access-point": ["Access point", "Punto de acceso", "Access Point", "Point d'accès", "Punto di accesso", "アクセスポイント", "接入点"],
  ndk_powerline: ["Powerline adapter", "Adaptador PLC", "Powerline-Adapter", "Adaptateur CPL", "Adattatore powerline", "PLC アダプター", "电力线适配器"],
  ndk_server: ["Server", "Servidor", "Server", "Serveur", "Server", "サーバー", "服务器"],
  ndk_nas: ["NAS storage", "Almacenamiento NAS", "NAS-Speicher", "Stockage NAS", "Archiviazione NAS", "NAS ストレージ", "NAS 存储"],
  ndk_computer: ["Computer", "Ordenador", "Computer", "Ordinateur", "Computer", "コンピューター", "电脑"],
  ndk_phone: ["Phone or tablet", "Móvil o tableta", "Handy oder Tablet", "Téléphone ou tablette", "Telefono o tablet", "スマホ・タブレット", "手机或平板"],
  ndk_tv: ["TV or player", "TV o reproductor", "Fernseher oder Player", "TV ou lecteur", "TV o lettore", "テレビ・プレーヤー", "电视或播放器"],
  ndk_printer: ["Printer", "Impresora", "Drucker", "Imprimante", "Stampante", "プリンター", "打印机"],
  ndk_camera: ["IP camera", "Cámara IP", "IP-Kamera", "Caméra IP", "Telecamera IP", "IP カメラ", "IP 摄像头"],
  ndk_iot: ["Smart device", "Dispositivo inteligente", "Smart-Gerät", "Appareil connecté", "Dispositivo smart", "スマートデバイス", "智能设备"],
  ndk_sbc: ["Single-board computer", "Ordenador de placa única", "Einplatinencomputer", "Ordinateur monocarte", "Computer a scheda singola", "シングルボードコンピューター", "单板计算机"],
  ndk_hub: ["Hub (Zigbee, Z-Wave…)", "Hub (Zigbee, Z-Wave…)", "Hub (Zigbee, Z-Wave …)", "Concentrateur (Zigbee, Z-Wave…)", "Hub (Zigbee, Z-Wave…)", "ハブ（Zigbee、Z-Wave など）", "网关（Zigbee、Z-Wave 等）"],
  "ndk_armor-server": ["A.R.M.O.R. server", "Servidor A.R.M.O.R.", "A.R.M.O.R.-Server", "Serveur A.R.M.O.R.", "Server A.R.M.O.R.", "A.R.M.O.R. サーバー", "A.R.M.O.R. 服务器"],
  "ndk_armor-node": ["A.R.M.O.R. node", "Nodo A.R.M.O.R.", "A.R.M.O.R.-Knoten", "Nœud A.R.M.O.R.", "Nodo A.R.M.O.R.", "A.R.M.O.R. ノード", "A.R.M.O.R. 节点"],
  ndp_provider: ["Provider", "Operador", "Anbieter", "Fournisseur", "Gestore", "プロバイダー", "运营商"],
  ndp_down_mbps: ["Download (Mbit/s)", "Bajada (Mbit/s)", "Download (Mbit/s)", "Débit descendant (Mbit/s)", "Download (Mbit/s)", "下り (Mbit/s)", "下行 (Mbit/s)"],
  ndp_up_mbps: ["Upload (Mbit/s)", "Subida (Mbit/s)", "Upload (Mbit/s)", "Débit montant (Mbit/s)", "Upload (Mbit/s)", "上り (Mbit/s)", "上行 (Mbit/s)"],
  ndp_type: ["Type", "Tipo", "Art", "Type", "Tipo", "種類", "类型"],
  ndp_ip: ["IP address", "Dirección IP", "IP-Adresse", "Adresse IP", "Indirizzo IP", "IP アドレス", "IP 地址"],
  ndp_subnet: ["Network (CIDR)", "Red (CIDR)", "Netzwerk (CIDR)", "Réseau (CIDR)", "Rete (CIDR)", "ネットワーク (CIDR)", "网络 (CIDR)"],
  ndp_dhcp: ["DHCP server", "Servidor DHCP", "DHCP-Server", "Serveur DHCP", "Server DHCP", "DHCP サーバー", "DHCP 服务器"],
  ndp_ssid: ["Wi-Fi name (SSID)", "Nombre del Wi-Fi (SSID)", "WLAN-Name (SSID)", "Nom du Wi-Fi (SSID)", "Nome del Wi-Fi (SSID)", "Wi-Fi 名 (SSID)", "Wi-Fi 名称 (SSID)"],
  ndp_wifi_band: ["Wi-Fi band", "Banda Wi-Fi", "WLAN-Band", "Bande Wi-Fi", "Banda Wi-Fi", "Wi-Fi 帯域", "Wi-Fi 频段"],
  ndp_band: ["Band", "Banda", "Band", "Bande", "Banda", "帯域", "频段"],
  ndp_mode: ["Mode", "Modo", "Modus", "Mode", "Modalità", "モード", "模式"],
  ndp_ports: ["Ports", "Puertos", "Ports", "Ports", "Porte", "ポート数", "端口数"],
  ndp_managed: ["Managed", "Gestionado", "Verwaltet", "Administrable", "Gestito", "マネージド", "可管理"],
  ndp_poe_budget_w: ["PoE budget (W)", "Potencia PoE (W)", "PoE-Budget (W)", "Budget PoE (W)", "Budget PoE (W)", "PoE 電力 (W)", "PoE 功率预算 (W)"],
  ndp_poe_w: ["PoE draw (W)", "Consumo PoE (W)", "PoE-Bedarf (W)", "Consommation PoE (W)", "Consumo PoE (W)", "PoE 消費 (W)", "PoE 功耗 (W)"],
  ndp_speed_mbps: ["Speed (Mbit/s)", "Velocidad (Mbit/s)", "Geschwindigkeit (Mbit/s)", "Débit (Mbit/s)", "Velocità (Mbit/s)", "速度 (Mbit/s)", "速率 (Mbit/s)"],
  ndp_role: ["Role", "Función", "Rolle", "Rôle", "Ruolo", "役割", "用途"],
  ndp_os: ["Operating system", "Sistema operativo", "Betriebssystem", "Système d'exploitation", "Sistema operativo", "OS", "操作系统"],
  ndp_capacity_tb: ["Capacity (TB)", "Capacidad (TB)", "Kapazität (TB)", "Capacité (To)", "Capacità (TB)", "容量 (TB)", "容量 (TB)"],
  ndp_rtsp: ["Video stream address", "Dirección del vídeo", "Videostream-Adresse", "Adresse du flux vidéo", "Indirizzo del video", "映像ストリームのアドレス", "视频流地址"],
  ndp_protocol: ["Protocol", "Protocolo", "Protokoll", "Protocole", "Protocollo", "プロトコル", "协议"],
  ndp_port: ["Port", "Puerto", "Port", "Port", "Porta", "ポート", "端口"],
  ndp_family: ["Family", "Familia", "Familie", "Famille", "Famiglia", "種類", "类别"],
  ndp_node_id: ["Node id", "Id del nodo", "Knoten-ID", "Id du nœud", "Id del nodo", "ノード ID", "节点 ID"],
  ndv_on: ["on", "activado", "an", "activé", "attivo", "オン", "开"],
  ndv_off: ["off", "desactivado", "aus", "désactivé", "disattivo", "オフ", "关"],
  ndv_bridge: ["bridge", "puente", "Bridge", "pont", "bridge", "ブリッジ", "桥接"],
  ndv_router: ["router", "router", "Router", "routeur", "router", "ルーター", "路由"],
  ndv_no: ["no", "no", "nein", "non", "no", "いいえ", "否"],
  ndv_yes: ["yes", "sí", "ja", "oui", "sì", "はい", "是"],
  ndv_radar: ["radar", "radar", "Radar", "radar", "radar", "レーダー", "雷达"],
  ndv_solar: ["solar", "solar", "Solar", "solaire", "solare", "ソーラー", "光伏"],
  ndv_electrical: ["electrical", "eléctrico", "Elektro", "électrique", "elettrico", "電気", "电气"],
  ndv_network: ["network", "red", "Netzwerk", "réseau", "rete", "ネットワーク", "网络"],
  ndv_other: ["other", "otro", "andere", "autre", "altro", "その他", "其他"],
  nderr_unknown_port: ["That port does not exist.", "Ese puerto no existe.", "Diesen Anschluss gibt es nicht.", "Ce port n'existe pas.", "Quella porta non esiste.", "そのポートはありません。", "该端口不存在。"],
  nderr_same_element: ["A link joins two different elements.", "Un enlace une dos elementos distintos.", "Eine Verbindung verbindet zwei verschiedene Elemente.", "Un lien relie deux éléments différents.", "Un collegamento unisce due elementi diversi.", "リンクは 2 つの異なる要素をつなぎます。", "链路连接两个不同的元素。"],
  nderr_medium: ["A cable, the air and the provider's line are different: only ports of the same kind are joined.", "Un cable, el aire y la línea del operador son cosas distintas: solo se unen puertos del mismo tipo.", "Kabel, Funk und Anbieterleitung sind verschieden: nur Anschlüsse derselben Art werden verbunden.", "Un câble, l'air et la ligne du fournisseur sont différents : seuls des ports du même type se relient.", "Un cavo, l'aria e la linea del gestore sono diversi: si uniscono solo porte dello stesso tipo.", "ケーブル、無線、プロバイダー回線は別物です。同じ種類のポート同士だけをつなげます。", "网线、无线和运营商线路不同：只能连接同类端口。"],
  nderr_busy: ["That port already has a link.", "Ese puerto ya tiene un enlace.", "Dieser Anschluss hat schon eine Verbindung.", "Ce port a déjà un lien.", "Quella porta ha già un collegamento.", "そのポートには既にリンクがあります。", "该端口已有链路。"],
  nderr_exists: ["Those two ports are already joined.", "Esos dos puertos ya están unidos.", "Diese beiden Anschlüsse sind schon verbunden.", "Ces deux ports sont déjà reliés.", "Quelle due porte sono già collegate.", "その 2 つのポートは既に接続されています。", "这两个端口已连接。"],
  nderr_too_many: ["The drawing has reached its limit.", "El dibujo ha alcanzado su límite.", "Die Zeichnung hat ihre Grenze erreicht.", "Le dessin a atteint sa limite.", "Il disegno ha raggiunto il suo limite.", "図面が上限に達しました。", "图纸已达上限。"],
  nd_tool_link: ["Link", "Enlace", "Verbindung", "Lien", "Collegamento", "リンク", "链路"],
  nd_example: ["Typical house", "Casa tipo", "Typisches Haus", "Maison type", "Casa tipo", "標準的な家", "典型住宅"],
  nd_draw_found: ["Draw what was found", "Dibujar lo encontrado", "Gefundenes zeichnen", "Dessiner ce qui a été trouvé", "Disegna ciò che è stato trovato", "検出した機器を描く", "绘制已发现的设备"],
  nd_nothing_new: ["Everything the nodes found is already in the drawing.", "Todo lo que encontraron los nodos ya está en el dibujo.", "Alles, was die Knoten gefunden haben, ist schon in der Zeichnung.", "Tout ce que les nœuds ont trouvé est déjà dans le dessin.", "Tutto ciò che i nodi hanno trovato è già nel disegno.", "ノードが見つけたものはすべて図面にあります。", "节点发现的设备都已在图纸中。"],
  nd_drawn_found: ["{0} devices were added and tied to the devices they are. The links are a guess: correct them.", "Se han añadido {0} dispositivos, cada uno ligado al dispositivo que es. Los enlaces son una suposición: corrígelos.", "{0} Geräte wurden hinzugefügt und mit den Geräten verknüpft, die sie sind. Die Verbindungen sind eine Vermutung: korrigieren Sie sie.", "{0} appareils ont été ajoutés et liés à ce qu'ils sont. Les liens sont une supposition : corrigez-les.", "Sono stati aggiunti {0} dispositivi, ciascuno legato al dispositivo che è. I collegamenti sono un'ipotesi: correggili.", "{0} 台を追加し、それぞれの機器に関連付けました。リンクは推定です。修正してください。", "已添加 {0} 台设备并与实际设备关联。链路是推测的：请自行修正。"],
  nd_bind_device: ["Tied to the device found", "Ligado al dispositivo encontrado", "Verknüpft mit dem gefundenen Gerät", "Lié à l'appareil trouvé", "Legato al dispositivo trovato", "検出した機器と関連付け", "关联到已发现的设备"],
  nd_bound_missing: ["The nodes do not report that device now.", "Los nodos no informan de ese dispositivo ahora.", "Die Knoten melden dieses Gerät derzeit nicht.", "Les nœuds ne signalent pas cet appareil actuellement.", "I nodi non segnalano ora quel dispositivo.", "現在そのデバイスはノードから報告されていません。", "节点目前没有上报该设备。"],
  nd_medium_wan: ["The provider's line", "La línea del operador", "Die Anbieterleitung", "La ligne du fournisseur", "La linea del gestore", "プロバイダー回線", "运营商线路"],
  nd_medium_eth: ["Cable (Ethernet)", "Cable (Ethernet)", "Kabel (Ethernet)", "Câble (Ethernet)", "Cavo (Ethernet)", "ケーブル (Ethernet)", "网线 (以太网)"],
  nd_medium_wifi: ["Wireless (Wi-Fi)", "Inalámbrico (Wi-Fi)", "Funk (WLAN)", "Sans fil (Wi-Fi)", "Wireless (Wi-Fi)", "無線 (Wi-Fi)", "无线 (Wi-Fi)"],
  nd_speed: ["Speed (Mbit/s)", "Velocidad (Mbit/s)", "Geschwindigkeit (Mbit/s)", "Débit (Mbit/s)", "Velocità (Mbit/s)", "速度 (Mbit/s)", "速率 (Mbit/s)"],
  nd_vlan: ["VLAN", "VLAN", "VLAN", "VLAN", "VLAN", "VLAN", "VLAN"],
  nd_links: ["Links", "Enlaces", "Verbindungen", "Liens", "Collegamenti", "リンク", "链路"],
  nd_wired: ["By cable", "Por cable", "Per Kabel", "Par câble", "Via cavo", "有線", "有线"],
  nd_wireless: ["Wireless", "Inalámbricos", "Per Funk", "Sans fil", "Wireless", "無線", "无线"],
  nd_poe: ["Power over cable (PoE)", "Alimentación por cable (PoE)", "Stromversorgung über Kabel (PoE)", "Alimentation par câble (PoE)", "Alimentazione via cavo (PoE)", "ケーブル給電 (PoE)", "网线供电 (PoE)"],
  nd_tied: ["Tied to a device found", "Ligados a un dispositivo encontrado", "Mit gefundenem Gerät verknüpft", "Liés à un appareil trouvé", "Legati a un dispositivo trovato", "検出機器と関連付け済み", "已关联到已发现的设备"],
  nd_disclaimer: ["The checks are a guide for reviewing the drawing. The drawing configures nothing: what is on the network is what the nodes find.", "Las comprobaciones son una guía para revisar el dibujo. El dibujo no configura nada: lo que hay en la red es lo que encuentran los nodos.", "Die Prüfungen sind eine Hilfe zur Durchsicht der Zeichnung. Die Zeichnung konfiguriert nichts: Was im Netzwerk ist, finden die Knoten.", "Les contrôles sont un guide pour revoir le dessin. Le dessin ne configure rien : ce qui est sur le réseau, ce sont les nœuds qui le trouvent.", "I controlli sono una guida per rivedere il disegno. Il disegno non configura nulla: ciò che c'è in rete è ciò che trovano i nodi.", "チェックは図面を見直すための目安です。図面は何も設定しません。ネットワーク上の実態はノードが検出したものです。", "检查只是审阅图纸的参考。图纸不会配置任何东西：网络中有什么以节点发现的为准。"],
  ndx_lan: ["Home network", "Red de casa", "Heimnetzwerk", "Réseau de la maison", "Rete di casa", "家庭ネットワーク", "家庭网络"],
  ndi_ip_invalid: ["{0} has an address that is not one: {1}.", "{0} tiene una dirección que no lo es: {1}.", "{0} hat eine ungültige Adresse: {1}.", "{0} a une adresse invalide : {1}.", "{0} ha un indirizzo non valido: {1}.", "{0} のアドレスが不正です：{1}。", "{0} 的地址无效：{1}。"],
  ndi_ip_duplicate: ["{1} and {2} have the same address, {0}.", "{1} y {2} tienen la misma dirección, {0}.", "{1} und {2} haben dieselbe Adresse, {0}.", "{1} et {2} ont la même adresse, {0}.", "{1} e {2} hanno lo stesso indirizzo, {0}.", "{1} と {2} が同じアドレス {0} です。", "{1} 和 {2} 的地址相同，均为 {0}。"],
  ndi_ip_outside: ["{0} has the address {1}, outside the network of the router ({2}).", "{0} tiene la dirección {1}, fuera de la red del router ({2}).", "{0} hat die Adresse {1}, außerhalb des Router-Netzwerks ({2}).", "{0} a l'adresse {1}, hors du réseau du routeur ({2}).", "{0} ha l'indirizzo {1}, fuori dalla rete del router ({2}).", "{0} のアドレス {1} はルーターのネットワーク ({2}) の外です。", "{0} 的地址 {1} 不在路由器的网络 ({2}) 内。"],
  ndi_unlinked: ["{0} is not joined to anything.", "{0} no está unido a nada.", "{0} ist mit nichts verbunden.", "{0} n'est relié à rien.", "{0} non è collegato a nulla.", "{0} はどこにも接続されていません。", "{0} 没有连接到任何东西。"],
  ndi_no_internet_path: ["{0} has no way out to the internet in the drawing.", "{0} no tiene salida a internet en el dibujo.", "{0} hat in der Zeichnung keinen Weg ins Internet.", "{0} n'a pas de sortie vers internet dans le dessin.", "{0} non ha uscita verso internet nel disegno.", "{0} には図面上でインターネットへの経路がありません。", "{0} 在图纸中没有通往互联网的路径。"],
  ndi_router_no_wan: ["The router {0} has nothing joined to its line port.", "El router {0} no tiene nada unido a su puerto de línea.", "Am Router {0} ist nichts am Anschluss zur Leitung angeschlossen.", "Le routeur {0} n'a rien de relié à son port de ligne.", "Il router {0} non ha nulla collegato alla porta di linea.", "ルーター {0} の回線ポートに何も接続されていません。", "路由器 {0} 的线路端口没有连接任何东西。"],
  ndi_switch_full: ["{0} has {1} cables and only {2} ports.", "{0} tiene {1} cables y solo {2} puertos.", "{0} hat {1} Kabel, aber nur {2} Ports.", "{0} a {1} câbles et seulement {2} ports.", "{0} ha {1} cavi e solo {2} porte.", "{0} は {1} 本のケーブルに対しポートが {2} 個しかありません。", "{0} 有 {1} 根线缆，但只有 {2} 个端口。"],
  ndi_poe_over: ["{0}: what hangs from it draws {1} W over the cable and it gives {2} W.", "{0}: lo que cuelga de él consume {1} W por el cable y él da {2} W.", "{0}: Was daran hängt, braucht {1} W über das Kabel, es liefert {2} W.", "{0} : ce qui y est relié consomme {1} W par le câble et il en fournit {2} W.", "{0}: ciò che vi è collegato assorbe {1} W via cavo e ne fornisce {2} W.", "{0}：接続機器はケーブル経由で {1} W 消費し、供給は {2} W です。", "{0}：所连设备通过网线耗电 {1} W，而它只提供 {2} W。"],
  ndi_wifi_server: ["{0} is only on Wi-Fi: a server or storage is better on a cable.", "{0} solo va por Wi-Fi: un servidor o un almacenamiento va mejor por cable.", "{0} hängt nur am WLAN: ein Server oder Speicher gehört besser an ein Kabel.", "{0} n'est qu'en Wi-Fi : un serveur ou un stockage est mieux sur câble.", "{0} è solo in Wi-Fi: un server o un'archiviazione sta meglio su cavo.", "{0} は Wi-Fi のみです。サーバーやストレージは有線が望ましいです。", "{0} 仅使用 Wi-Fi：服务器或存储设备最好使用网线。"],
  ndi_bound_missing: ["{0} is tied to a device the nodes do not report now.", "{0} está ligado a un dispositivo que los nodos no informan ahora.", "{0} ist mit einem Gerät verknüpft, das die Knoten derzeit nicht melden.", "{0} est lié à un appareil que les nœuds ne signalent pas actuellement.", "{0} è legato a un dispositivo che i nodi non segnalano ora.", "{0} は現在ノードが報告していないデバイスに関連付けられています。", "{0} 关联的设备目前没有被节点上报。"],
  ndi_bound_offline: ["{0} is tied to a device that is offline.", "{0} está ligado a un dispositivo sin conexión.", "{0} ist mit einem Gerät verknüpft, das offline ist.", "{0} est lié à un appareil hors ligne.", "{0} è legato a un dispositivo offline.", "{0} はオフラインのデバイスに関連付けられています。", "{0} 关联的设备处于离线状态。"],
  ndi_ip_differs: ["{0} is drawn with the address {1} and the device has {2}.", "{0} está dibujado con la dirección {1} y el dispositivo tiene {2}.", "{0} ist mit der Adresse {1} gezeichnet, das Gerät hat {2}.", "{0} est dessiné avec l'adresse {1} et l'appareil a {2}.", "{0} è disegnato con l'indirizzo {1} e il dispositivo ha {2}.", "{0} は図面ではアドレス {1} ですが、実機は {2} です。", "{0} 图中地址为 {1}，而设备实际为 {2}。"],
  ndi_undrawn: ["{0} devices on the network are not in the drawing.", "{0} dispositivos de la red no están en el dibujo.", "{0} Geräte im Netzwerk sind nicht in der Zeichnung.", "{0} appareils du réseau ne sont pas dans le dessin.", "{0} dispositivi della rete non sono nel disegno.", "ネットワーク上の {0} 台が図面にありません。", "网络上有 {0} 台设备不在图纸中。"],
};

export const networkCatalogues: RowCatalogues = cataloguesFromRows(ROWS);
export const NETWORK_KEYS = Object.keys(ROWS);
