/**
 * The words of Configuration > Notifications (where the alarms are sent: the signed webhook, MQTT, Telegram, Home Assistant, and a test of each), in the seven languages.
 * One row per phrase: en, es, de, fr, it, ja, zh.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
 */
import type { Locale } from "./i18n";

type Row = readonly [string, string, string, string, string, string, string];
const order: readonly Locale[] = ["en", "es", "de", "fr", "it", "ja", "zh"];

const rows: Record<string, Row> = {
  tabNotifications: ["Notifications", "Notificaciones", "Benachrichtigungen", "Notifications", "Notifiche", "通知", "通知"],
  nt_title: ["Where the alarms are sent", "A dónde se envían las alarmas", "Wohin die Alarme gesendet werden", "Où les alarmes sont envoyées", "Dove vengono inviati gli allarmi", "アラームの送信先", "报警发送到哪里"],
  nt_help: ["Besides the notifications of the phone app and the history, the server can send every alarm to a Telegram chat and to Home Assistant, and always publishes it on MQTT. Here you see which places are set up and send a test message to each, so a wrong token or address shows up now and not on the night of an alarm.", "Además de las notificaciones de la app del móvil y del historial, el servidor puede enviar cada alarma a un chat de Telegram y a Home Assistant, y siempre la publica en MQTT. Aquí ves qué lugares están configurados y puedes enviar un mensaje de prueba a cada uno, para que un token o una dirección equivocados se vean ahora y no la noche de una alarma.", "Außer den Benachrichtigungen der Handy-App und dem Verlauf kann der Server jeden Alarm an einen Telegram-Chat und an Home Assistant senden und veröffentlicht ihn immer auf MQTT. Hier siehst du, welche Ziele eingerichtet sind, und kannst jedem eine Testnachricht schicken, damit ein falscher Token oder eine falsche Adresse jetzt auffällt und nicht in der Nacht eines Alarms.", "En plus des notifications de l'application du téléphone et de l'historique, le serveur peut envoyer chaque alarme à un chat Telegram et à Home Assistant, et la publie toujours sur MQTT. Vous voyez ici quels endroits sont configurés et pouvez envoyer un message de test à chacun, pour qu'un jeton ou une adresse erronés se voient maintenant et non la nuit d'une alarme.", "Oltre alle notifiche dell'app del telefono e alla cronologia, il server può inviare ogni allarme a una chat Telegram e a Home Assistant, e lo pubblica sempre su MQTT. Qui vedi quali destinazioni sono configurate e puoi inviare un messaggio di prova a ciascuna, così un token o un indirizzo sbagliato si vede adesso e non la notte di un allarme.", "スマートフォンアプリの通知と履歴に加えて、サーバーはすべてのアラームを Telegram のチャットと Home Assistant に送信でき、常に MQTT にも公開します。ここで設定済みの送信先を確認し、それぞれにテストメッセージを送れるので、誤ったトークンやアドレスをアラームの夜ではなく今のうちに見つけられます。", "除手机应用的通知和历史记录外，服务器还可以把每个报警发送到 Telegram 聊天和 Home Assistant，并始终发布到 MQTT。在这里你可以看到已配置的去处，并向每个发送测试消息，这样错误的令牌或地址现在就能发现，而不是在报警的夜晚。"],
  nt_on: ["set up", "configurado", "eingerichtet", "configuré", "configurato", "設定済み", "已配置"],
  nt_off: ["not set up", "sin configurar", "nicht eingerichtet", "non configuré", "non configurato", "未設定", "未配置"],
  nt_webhook: ["Signed webhook", "Webhook firmado", "Signierter Webhook", "Webhook signé", "Webhook firmato", "署名付き Webhook", "签名 Webhook"],
  nt_mqtt: ["MQTT topic armor/server/alert", "Tema MQTT armor/server/alert", "MQTT-Thema armor/server/alert", "Sujet MQTT armor/server/alert", "Topic MQTT armor/server/alert", "MQTT トピック armor/server/alert", "MQTT 主题 armor/server/alert"],
  nt_telegram: ["Telegram", "Telegram", "Telegram", "Telegram", "Telegram", "Telegram", "Telegram"],
  nt_homeassistant: ["Home Assistant", "Home Assistant", "Home Assistant", "Home Assistant", "Home Assistant", "Home Assistant", "Home Assistant"],
  nt_language: ["Language of the sentences", "Idioma de las frases", "Sprache der Sätze", "Langue des phrases", "Lingua delle frasi", "文章の言語", "语句语言"],
  nt_test_all: ["Send a test to every place", "Enviar una prueba a todos los lugares", "Test an alle Ziele senden", "Envoyer un test à tous les endroits", "Invia una prova a tutte le destinazioni", "すべての送信先にテストを送信", "向所有去处发送测试"],
  nt_test_one: ["Test", "Probar", "Testen", "Tester", "Prova", "テスト", "测试"],
  nt_result_ok: ["delivered", "entregado", "zugestellt", "livré", "consegnato", "配信済み", "已送达"],
  nt_result_fail: ["failed", "ha fallado", "fehlgeschlagen", "échec", "non riuscito", "失敗", "失败"],
  nt_nothing: ["Nothing is set up yet: follow the steps on the right.", "Todavía no hay nada configurado: sigue los pasos de la derecha.", "Noch nichts eingerichtet: folge den Schritten rechts.", "Rien n'est encore configuré : suivez les étapes de droite.", "Non c'è ancora nulla di configurato: segui i passi a destra.", "まだ何も設定されていません。右の手順に従ってください。", "尚未配置任何内容：请按右侧的步骤操作。"],
  nt_howto: ["How to set them up", "Cómo configurarlos", "So richtest du sie ein", "Comment les configurer", "Come configurarli", "設定方法", "如何配置"],
  nt_file: ["The values go in the settings file of the server (Settings files > armor.env), and the server is restarted afterwards.", "Los valores van en el archivo de ajustes del servidor (Archivos de ajustes > armor.env) y después se reinicia el servidor.", "Die Werte kommen in die Einstellungsdatei des Servers (Einstellungsdateien > armor.env); danach wird der Server neu gestartet.", "Les valeurs vont dans le fichier de réglages du serveur (Fichiers de réglages > armor.env), puis le serveur est redémarré.", "I valori vanno nel file di impostazioni del server (File di impostazioni > armor.env), poi si riavvia il server.", "値はサーバーの設定ファイル（設定ファイル > armor.env）に入れ、その後サーバーを再起動します。", "数值写在服务器的设置文件中（设置文件 > armor.env），然后重启服务器。"],
  nt_telegram_steps: ["1. In Telegram talk to @BotFather, send /newbot and keep the token. 2. Open a chat with your bot (or add it to a group) and send it any message. 3. Open https://api.telegram.org/bot<TOKEN>/getUpdates in a browser and read \"chat\":{\"id\": ...}. 4. Put ARMOR_TELEGRAM_BOT_TOKEN=<token> and ARMOR_TELEGRAM_CHAT_IDS=<id>[,<id>...] in armor.env.", "1. En Telegram habla con @BotFather, envía /newbot y guarda el token. 2. Abre un chat con tu bot (o añádelo a un grupo) y envíale cualquier mensaje. 3. Abre https://api.telegram.org/bot<TOKEN>/getUpdates en un navegador y lee \"chat\":{\"id\": ...}. 4. Pon ARMOR_TELEGRAM_BOT_TOKEN=<token> y ARMOR_TELEGRAM_CHAT_IDS=<id>[,<id>...] en armor.env.", "1. Sprich in Telegram mit @BotFather, sende /newbot und behalte den Token. 2. Öffne einen Chat mit deinem Bot (oder füge ihn einer Gruppe hinzu) und sende ihm eine beliebige Nachricht. 3. Öffne https://api.telegram.org/bot<TOKEN>/getUpdates in einem Browser und lies \"chat\":{\"id\": ...}. 4. Trage ARMOR_TELEGRAM_BOT_TOKEN=<Token> und ARMOR_TELEGRAM_CHAT_IDS=<id>[,<id>...] in armor.env ein.", "1. Dans Telegram, parlez à @BotFather, envoyez /newbot et gardez le jeton. 2. Ouvrez une discussion avec votre bot (ou ajoutez-le à un groupe) et envoyez-lui un message. 3. Ouvrez https://api.telegram.org/bot<TOKEN>/getUpdates dans un navigateur et lisez \"chat\":{\"id\": ...}. 4. Mettez ARMOR_TELEGRAM_BOT_TOKEN=<jeton> et ARMOR_TELEGRAM_CHAT_IDS=<id>[,<id>...] dans armor.env.", "1. In Telegram parla con @BotFather, invia /newbot e conserva il token. 2. Apri una chat con il tuo bot (o aggiungilo a un gruppo) e invialo un messaggio qualsiasi. 3. Apri https://api.telegram.org/bot<TOKEN>/getUpdates in un browser e leggi \"chat\":{\"id\": ...}. 4. Metti ARMOR_TELEGRAM_BOT_TOKEN=<token> e ARMOR_TELEGRAM_CHAT_IDS=<id>[,<id>...] in armor.env.", "1. Telegram で @BotFather に話しかけ、/newbot を送ってトークンを控えます。2. 作成した bot とのチャットを開き（またはグループに追加し）、何かメッセージを送ります。3. ブラウザで https://api.telegram.org/bot<TOKEN>/getUpdates を開き、\"chat\":{\"id\": ...} を読みます。4. armor.env に ARMOR_TELEGRAM_BOT_TOKEN=<トークン> と ARMOR_TELEGRAM_CHAT_IDS=<id>[,<id>...] を書きます。", "1. 在 Telegram 中与 @BotFather 对话，发送 /newbot 并保存令牌。2. 与你的机器人开启聊天（或把它加入群组）并发送任意消息。3. 在浏览器中打开 https://api.telegram.org/bot<TOKEN>/getUpdates，读取 \"chat\":{\"id\": ...}。4. 在 armor.env 中写入 ARMOR_TELEGRAM_BOT_TOKEN=<令牌> 和 ARMOR_TELEGRAM_CHAT_IDS=<id>[,<id>...]。"],
  nt_ha_steps: ["1. In Home Assistant create an automation whose trigger is Webhook and copy its webhook id. 2. Make its action what you want (a notification to the phone, a siren, a light): trigger.json.text is the sentence, trigger.json.title is A.R.M.O.R., and trigger.json.event, node_id, severity, code say what happened. 3. Put ARMOR_HOMEASSISTANT_URL=http://<address>:8123 and ARMOR_HOMEASSISTANT_WEBHOOK_ID=<id> in armor.env. The id is a secret.", "1. En Home Assistant crea una automatización cuyo disparador sea Webhook y copia su id de webhook. 2. Haz que su acción sea lo que quieras (una notificación al móvil, una sirena, una luz): trigger.json.text es la frase, trigger.json.title es A.R.M.O.R., y trigger.json.event, node_id, severity, code dicen qué ha pasado. 3. Pon ARMOR_HOMEASSISTANT_URL=http://<dirección>:8123 y ARMOR_HOMEASSISTANT_WEBHOOK_ID=<id> en armor.env. El id es un secreto.", "1. Erstelle in Home Assistant eine Automatisierung mit dem Auslöser Webhook und kopiere ihre Webhook-ID. 2. Lege als Aktion fest, was du willst (eine Benachrichtigung ans Handy, eine Sirene, ein Licht): trigger.json.text ist der Satz, trigger.json.title ist A.R.M.O.R., und trigger.json.event, node_id, severity, code sagen, was passiert ist. 3. Trage ARMOR_HOMEASSISTANT_URL=http://<Adresse>:8123 und ARMOR_HOMEASSISTANT_WEBHOOK_ID=<id> in armor.env ein. Die ID ist ein Geheimnis.", "1. Dans Home Assistant, créez une automatisation dont le déclencheur est Webhook et copiez son identifiant de webhook. 2. Faites-en l'action de votre choix (une notification au téléphone, une sirène, une lumière) : trigger.json.text est la phrase, trigger.json.title est A.R.M.O.R., et trigger.json.event, node_id, severity, code disent ce qui s'est passé. 3. Mettez ARMOR_HOMEASSISTANT_URL=http://<adresse>:8123 et ARMOR_HOMEASSISTANT_WEBHOOK_ID=<id> dans armor.env. L'identifiant est un secret.", "1. In Home Assistant crea un'automazione con trigger Webhook e copia il suo id webhook. 2. Fai sì che l'azione sia ciò che vuoi (una notifica al telefono, una sirena, una luce): trigger.json.text è la frase, trigger.json.title è A.R.M.O.R., e trigger.json.event, node_id, severity, code dicono cosa è successo. 3. Metti ARMOR_HOMEASSISTANT_URL=http://<indirizzo>:8123 e ARMOR_HOMEASSISTANT_WEBHOOK_ID=<id> in armor.env. L'id è un segreto.", "1. Home Assistant でトリガーを Webhook にしたオートメーションを作り、Webhook ID をコピーします。2. アクションを好きなもの（スマホへの通知、サイレン、照明）にします。trigger.json.text が文章、trigger.json.title が A.R.M.O.R. で、trigger.json.event、node_id、severity、code が内容を表します。3. armor.env に ARMOR_HOMEASSISTANT_URL=http://<アドレス>:8123 と ARMOR_HOMEASSISTANT_WEBHOOK_ID=<id> を書きます。ID は秘密です。", "1. 在 Home Assistant 中创建触发器为 Webhook 的自动化，并复制其 Webhook ID。2. 将动作设为你想要的（手机通知、警报器、灯光）：trigger.json.text 是语句，trigger.json.title 是 A.R.M.O.R.，trigger.json.event、node_id、severity、code 说明发生了什么。3. 在 armor.env 中写入 ARMOR_HOMEASSISTANT_URL=http://<地址>:8123 和 ARMOR_HOMEASSISTANT_WEBHOOK_ID=<id>。该 ID 是机密。"],
  nt_err_generic: ["It could not be done.", "No se pudo hacer.", "Es ging nicht.", "Impossible à faire.", "Non è stato possibile.", "実行できませんでした。", "无法完成。"],
  nt_err_nothing_configured: ["Nothing is set up yet.", "Todavía no hay nada configurado.", "Noch nichts eingerichtet.", "Rien n'est encore configuré.", "Non c'è ancora nulla di configurato.", "まだ何も設定されていません。", "尚未配置任何内容。"],
};

/** The catalogue of one language. */
export const notificationsCatalogue = (locale: Locale): Record<string, string> => {
  const index = order.indexOf(locale);
  return Object.fromEntries(Object.entries(rows).map(([key, row]) => [key, row[index]]));
};
