/**
 * Interface text of the overview, the system page and the navigation groups, in the seven languages.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
 */
import { cataloguesFromRows, type Row } from "./catalogueRows";

const ROWS: Record<string, Row> = {
  siteConflict: ["Someone else saved the design first; their version is now on screen.", "Otra persona guardó antes el diseño; ahora ves su versión.", "Jemand hat den Plan zuerst gespeichert; dessen Version ist jetzt zu sehen.", "Quelqu'un a enregistré le plan avant vous ; sa version est maintenant affichée.", "Qualcun altro ha salvato prima il progetto; ora vedi la sua versione.", "他の人が先に設計を保存しました。その版を表示しています。", "有人先保存了设计，现在显示的是他们的版本。"],
  siteSync_saved: ["Design saved on the server", "Diseño guardado en el servidor", "Plan auf dem Server gespeichert", "Plan enregistré sur le serveur", "Progetto salvato sul server", "設計はサーバーに保存済み", "设计已保存在服务器"],
  siteSync_saving: ["Saving the design…", "Guardando el diseño…", "Plan wird gespeichert …", "Enregistrement du plan…", "Salvataggio del progetto…", "設計を保存中…", "正在保存设计…"],
  siteSync_offline: ["The design could not be saved on the server; it stays in this browser and is retried.", "No se pudo guardar el diseño en el servidor; queda en este navegador y se reintenta.", "Der Plan konnte nicht auf dem Server gespeichert werden; er bleibt in diesem Browser und wird erneut versucht.", "Le plan n'a pas pu être enregistré sur le serveur ; il reste dans ce navigateur et sera retenté.", "Impossibile salvare il progetto sul server; resta in questo browser e si riprova.", "設計をサーバーに保存できませんでした。このブラウザに残り、再試行します。", "无法在服务器上保存设计；它保留在此浏览器中并会重试。"],
  navEvidence: ["Evidence", "Evidencias", "Beweise", "Preuves", "Prove", "証拠", "证据"],
  navMonitor: ["Monitor", "Vigilancia", "Überwachung", "Surveillance", "Sorveglianza", "監視", "监控"], navControl: ["Control", "Control", "Steuerung", "Contrôle", "Controllo", "制御", "控制"], navDesign: ["Design", "Diseño", "Entwurf", "Conception", "Progetto", "設計", "设计"], navAdmin: ["Administration", "Administración", "Verwaltung", "Administration", "Amministrazione", "管理", "管理"],
  system: ["System", "Sistema", "System", "Système", "Sistema", "システム", "系统"],
  overviewTitle: ["Perimeter operations", "Operaciones del perímetro", "Perimeter-Betrieb", "Opérations du périmètre", "Operazioni del perimetro", "境界オペレーション", "周界运行"],
  overviewHelp: ["Everything that guards the site at a glance: alarms, radars, cameras, devices, automations and the design they live in.", "Todo lo que vigila el emplazamiento de un vistazo: alarmas, radares, cámaras, dispositivos, automatizaciones y el diseño donde viven.", "Alles, was den Standort bewacht, auf einen Blick: Alarme, Radare, Kameras, Geräte, Automatisierungen und der Entwurf, in dem sie stehen.", "Tout ce qui garde le site en un coup d'œil : alarmes, radars, caméras, appareils, automatisations et le plan où ils vivent.", "Tutto ciò che protegge il sito a colpo d'occhio: allarmi, radar, telecamere, dispositivi, automazioni e il progetto in cui vivono.", "敷地を守るすべてを一目で：アラーム、レーダー、カメラ、デバイス、オートメーション、そして設計。", "一眼看清守护场地的一切：警报、雷达、摄像头、设备、自动化以及它们所在的设计。"],
  tileAlarms: ["Alarms", "Alarmas", "Alarme", "Alarmes", "Allarmi", "アラーム", "警报"], tileRadar: ["Radar nodes", "Nodos radar", "Radarknoten", "Nœuds radar", "Nodi radar", "レーダーノード", "雷达节点"], tileCameras: ["Cameras", "Cámaras", "Kameras", "Caméras", "Telecamere", "カメラ", "摄像头"], tileDevices: ["Devices", "Dispositivos", "Geräte", "Appareils", "Dispositivi", "デバイス", "设备"],
  tileAutomations: ["Automations", "Automatizaciones", "Automatisierungen", "Automatisations", "Automazioni", "オートメーション", "自动化"], tileSite: ["Site design", "Diseño del sitio", "Standortentwurf", "Plan du site", "Progetto del sito", "敷地設計", "场地设计"], tileEvidence: ["Evidence", "Evidencias", "Beweise", "Preuves", "Prove", "証拠", "证据"], tileSystem: ["Server", "Servidor", "Server", "Serveur", "Server", "サーバー", "服务器"],
  tileOnline: ["online", "en línea", "online", "en ligne", "online", "オンライン", "在线"], tileTracks: ["targets now", "objetivos ahora", "Ziele jetzt", "cibles maintenant", "bersagli ora", "現在の対象", "当前目标"], tileReachable: ["reachable", "alcanzables", "erreichbar", "joignables", "raggiungibili", "到達可能", "可达"], tileTriggered: ["triggered", "activados", "ausgelöst", "déclenchés", "attivati", "作動中", "已触发"],
  tileEnabled: ["enabled", "activas", "aktiv", "activées", "attive", "有効", "已启用"], tileBuildings: ["buildings", "edificios", "Gebäude", "bâtiments", "edifici", "建物", "建筑"], tileDevicesPlaced: ["devices placed", "dispositivos colocados", "Geräte platziert", "appareils placés", "dispositivi posizionati", "配置済みデバイス", "已放置设备"], tileFiles: ["files", "archivos", "Dateien", "fichiers", "file", "ファイル", "文件"], tileUsers: ["users", "usuarios", "Benutzer", "utilisateurs", "utenti", "ユーザー", "用户"],
  liveMap: ["Live site map", "Mapa en vivo del sitio", "Live-Standortkarte", "Carte du site en direct", "Mappa del sito in tempo reale", "ライブ敷地マップ", "实时场地地图"], liveMapEmpty: ["Draw your site in the site designer and it appears here, with the devices and the radar targets.", "Dibuja tu sitio en el diseñador y aparecerá aquí, con los dispositivos y los objetivos de radar.", "Zeichnen Sie Ihren Standort im Standortplaner; er erscheint hier mit Geräten und Radarzielen.", "Dessinez votre site dans le concepteur et il apparaît ici, avec les appareils et les cibles radar.", "Disegna il tuo sito nel progettista e apparirà qui, con dispositivi e bersagli radar.", "サイトデザイナーで敷地を描くと、デバイスやレーダー対象とともにここに表示されます。", "在场地设计器中绘制场地，它会连同设备和雷达目标一起显示在这里。"],
  needsAttention: ["Needs attention", "Requiere atención", "Braucht Aufmerksamkeit", "À surveiller", "Richiede attenzione", "要確認", "需要关注"], nothingToAttend: ["Everything answers and nothing is triggered.", "Todo responde y nada está activado.", "Alles antwortet und nichts ist ausgelöst.", "Tout répond et rien n'est déclenché.", "Tutto risponde e nulla è attivato.", "すべて応答し、作動しているものはありません。", "一切响应正常，无触发项。"],
  recentActivity: ["Recent activity", "Actividad reciente", "Letzte Aktivität", "Activité récente", "Attività recente", "最近のアクティビティ", "最近活动"], noActivity: ["Nothing has happened yet.", "Todavía no ha pasado nada.", "Es ist noch nichts passiert.", "Rien ne s'est encore passé.", "Non è ancora successo nulla.", "まだ何も起きていません。", "尚无事件。"], openHistory: ["Open the history", "Abrir el historial", "Verlauf öffnen", "Ouvrir l'historique", "Apri la cronologia", "履歴を開く", "打开历史记录"],
  quickActions: ["Quick actions", "Acciones rápidas", "Schnellaktionen", "Actions rapides", "Azioni rapide", "クイック操作", "快捷操作"], qaCameras: ["Watch the cameras", "Ver las cámaras", "Kameras ansehen", "Voir les caméras", "Guarda le telecamere", "カメラを見る", "查看摄像头"], qaDesigner: ["Edit the site design", "Editar el diseño", "Entwurf bearbeiten", "Modifier le plan", "Modifica il progetto", "設計を編集", "编辑场地设计"], qaAddDevice: ["Add a device", "Añadir un dispositivo", "Gerät hinzufügen", "Ajouter un appareil", "Aggiungi un dispositivo", "デバイスを追加", "添加设备"],
  eventAlert: ["Alert level", "Nivel de alerta", "Alarmstufe", "Niveau d'alerte", "Livello di allerta", "警戒レベル", "警戒级别"], eventNode: ["Node", "Nodo", "Knoten", "Nœud", "Nodo", "ノード", "节点"], eventCamera: ["Camera", "Cámara", "Kamera", "Caméra", "Telecamera", "カメラ", "摄像头"], eventMode: ["System", "Sistema", "System", "Système", "Sistema", "システム", "系统"], eventDevice: ["Device", "Dispositivo", "Gerät", "Appareil", "Dispositivo", "デバイス", "设备"], eventAlarm: ["Alarm", "Alarma", "Alarm", "Alarme", "Allarme", "アラーム", "警报"],
  alarmRaised: ["raised", "activada", "ausgelöst", "déclenchée", "scattato", "発生", "触发"], alarmAcknowledged: ["acknowledged", "reconocida", "quittiert", "acquittée", "confermato", "確認済み", "已确认"], alarmCleared: ["ended", "terminada", "beendet", "terminée", "terminato", "終了", "已结束"],
  systemTitle: ["Health of the system", "Salud del sistema", "Zustand des Systems", "Santé du système", "Salute del sistema", "システムの状態", "系统健康状况"],
  systemHelp: ["The server, what it holds, the room it has left, how it connects, and the audit trail of who did what.", "El servidor, lo que guarda, el espacio que le queda, cómo se conecta y el registro de auditoría de quién hizo qué.", "Der Server, was er enthält, wie viel Platz bleibt, wie er verbunden ist, und das Audit-Protokoll, wer was getan hat.", "Le serveur, ce qu'il contient, la place restante, comment il se connecte et la piste d'audit de qui a fait quoi.", "Il server, cosa contiene, lo spazio rimasto, come si connette e il registro di audit di chi ha fatto cosa.", "サーバー、保存内容、空き容量、接続状況、そして誰が何をしたかの監査記録。", "服务器、其保存的内容、剩余空间、连接方式，以及谁做了什么的审计记录。"],
  sysVersion: ["Version", "Versión", "Version", "Version", "Versione", "バージョン", "版本"], sysUptime: ["Running for", "Funcionando desde hace", "Läuft seit", "En marche depuis", "In funzione da", "稼働時間", "已运行"], sysMode: ["Mode", "Modo", "Modus", "Mode", "Modalità", "モード", "模式"], sysRevision: ["State revision", "Revisión del estado", "Zustandsrevision", "Révision de l'état", "Revisione dello stato", "状態リビジョン", "状态修订"],
  sysHolds: ["What it holds", "Lo que guarda", "Was er enthält", "Ce qu'il contient", "Cosa contiene", "保存内容", "保存的内容"], sysNodes: ["Radar nodes", "Nodos radar", "Radarknoten", "Nœuds radar", "Nodi radar", "レーダーノード", "雷达节点"], sysCameras: ["Cameras", "Cámaras", "Kameras", "Caméras", "Telecamere", "カメラ", "摄像头"], sysDevices: ["Devices", "Dispositivos", "Geräte", "Appareils", "Dispositivi", "デバイス", "设备"], sysAlarms: ["Alarms open", "Alarmas abiertas", "Offene Alarme", "Alarmes ouvertes", "Allarmi aperti", "未対応アラーム", "未处理警报"], sysAutomations: ["Automations", "Automatizaciones", "Automatisierungen", "Automatisations", "Automazioni", "オートメーション", "自动化"], sysUsers: ["Users", "Usuarios", "Benutzer", "Utilisateurs", "Utenti", "ユーザー", "用户"], sysEvents: ["Events kept", "Eventos guardados", "Gespeicherte Ereignisse", "Événements conservés", "Eventi conservati", "保存イベント", "已保存事件"],
  sysStorage: ["Storage", "Almacenamiento", "Speicher", "Stockage", "Archiviazione", "ストレージ", "存储"], sysMedia: ["Evidence used", "Evidencias usadas", "Beweise belegt", "Preuves utilisées", "Prove usate", "証拠の使用量", "证据占用"], sysDisk: ["Free on the disk", "Libre en el disco", "Frei auf dem Datenträger", "Libre sur le disque", "Libero sul disco", "ディスク空き", "磁盘剩余"],
  sysLinks: ["Connections", "Conexiones", "Verbindungen", "Connexions", "Connessioni", "接続", "连接"], sysMqtt: ["MQTT broker", "Broker MQTT", "MQTT-Broker", "Broker MQTT", "Broker MQTT", "MQTT ブローカー", "MQTT 代理"], sysVideo: ["Live video (FFmpeg)", "Vídeo en vivo (FFmpeg)", "Live-Video (FFmpeg)", "Vidéo en direct (FFmpeg)", "Video in diretta (FFmpeg)", "ライブ映像（FFmpeg）", "实时视频（FFmpeg）"], sysWebhook: ["Alarm webhook", "Webhook de alarmas", "Alarm-Webhook", "Webhook d'alarmes", "Webhook degli allarmi", "アラーム Webhook", "警报 Webhook"], sysOn: ["connected", "conectado", "verbunden", "connecté", "connesso", "接続済み", "已连接"], sysOff: ["not set up", "sin configurar", "nicht eingerichtet", "non configuré", "non configurato", "未設定", "未配置"],
  auditTitle: ["Audit trail", "Registro de auditoría", "Audit-Protokoll", "Piste d'audit", "Registro di audit", "監査記録", "审计记录"], auditHelp: ["Who did what and whether it was allowed. Passwords, tokens and camera addresses are never written.", "Quién hizo qué y si estaba permitido. Nunca se escriben contraseñas, tokens ni direcciones de cámaras.", "Wer was getan hat und ob es erlaubt war. Passwörter, Tokens und Kameraadressen werden nie geschrieben.", "Qui a fait quoi et si c'était autorisé. Mots de passe, jetons et adresses de caméras ne sont jamais écrits.", "Chi ha fatto cosa e se era consentito. Password, token e indirizzi delle telecamere non vengono mai scritti.", "誰が何をしたか、許可されたか。パスワード・トークン・カメラアドレスは記録されません。", "谁做了什么、是否被允许。密码、令牌和摄像头地址绝不会被记录。"], auditOnlyAdmin: ["Only an administrator can read the audit trail.", "Solo un administrador puede leer el registro de auditoría.", "Nur ein Administrator kann das Audit-Protokoll lesen.", "Seul un administrateur peut lire la piste d'audit.", "Solo un amministratore può leggere il registro di audit.", "監査記録は管理者のみ閲覧できます。", "只有管理员可以查看审计记录。"],
  auditFilter: ["Filter (action, user, target)", "Filtrar (acción, usuario, objetivo)", "Filtern (Aktion, Benutzer, Ziel)", "Filtrer (action, utilisateur, cible)", "Filtra (azione, utente, obiettivo)", "絞り込み（操作・ユーザー・対象）", "筛选（操作、用户、目标）"], auditOnlyProblems: ["Only what was denied or failed", "Solo lo denegado o fallido", "Nur Abgelehntes oder Fehlgeschlagenes", "Seulement refusé ou échoué", "Solo negato o fallito", "拒否・失敗のみ", "仅显示被拒或失败"], auditWhen: ["When", "Cuándo", "Wann", "Quand", "Quando", "日時", "时间"], auditWho: ["Who", "Quién", "Wer", "Qui", "Chi", "ユーザー", "用户"], auditWhat: ["What", "Qué", "Was", "Quoi", "Cosa", "操作", "操作"], auditResult: ["Result", "Resultado", "Ergebnis", "Résultat", "Esito", "結果", "结果"],
  outcome_allowed: ["allowed", "permitido", "erlaubt", "autorisé", "consentito", "許可", "允许"], outcome_denied: ["denied", "denegado", "abgelehnt", "refusé", "negato", "拒否", "拒绝"], outcome_failed: ["failed", "fallido", "fehlgeschlagen", "échoué", "fallito", "失敗", "失败"],
  daysShort: ["d", "d", "T", "j", "g", "日", "天"], hoursShort: ["h", "h", "Std", "h", "h", "時間", "小时"], minutesShort: ["min", "min", "Min", "min", "min", "分", "分钟"],
};

export const overviewCatalogues = cataloguesFromRows(ROWS);
