/**
 * Interface text of the live radar map and of wiring a radar of the design to a field node, in the seven languages.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
 */
import { cataloguesFromRows, type Row } from "./catalogueRows";

const ROWS: Record<string, Row> = {
  radarMap: ["Live radar map", "Mapa de radar en vivo", "Live-Radarkarte", "Carte radar en direct", "Mappa radar in tempo reale", "ライブレーダーマップ", "实时雷达地图"],
  radarMapHelp: ["Drawn from your site design: terrain, buildings, cameras and every radar with the area it covers, and the targets the radars report right now.", "Dibujado a partir de tu diseño del emplazamiento: terreno, edificios, cámaras y cada radar con su zona de cobertura, y los objetivos que los radares detectan ahora.", "Aus Ihrem Standortentwurf gezeichnet: Grundstück, Gebäude, Kameras und jedes Radar mit seinem Abdeckungsbereich sowie die aktuell gemeldeten Ziele.", "Dessinée d'après votre plan du site : terrain, bâtiments, caméras et chaque radar avec sa zone couverte, et les cibles détectées en ce moment.", "Disegnata dal tuo progetto del sito: terreno, edifici, telecamere e ogni radar con la sua area coperta, e i bersagli rilevati ora.", "敷地設計から描画：土地・建物・カメラ・各レーダーの検知範囲と、現在検知中の対象。", "根据你的场地设计绘制：地块、建筑、摄像头、各雷达的覆盖范围，以及雷达当前检测到的目标。"],
  sensorModel: ["Sensor model", "Modelo de sensor", "Sensormodell", "Modèle de capteur", "Modello di sensore", "センサーのモデル", "传感器型号"],
  radarsOfDesign: ["Radars of the design", "Radares del diseño", "Radare des Entwurfs", "Radars du plan", "Radar del progetto", "設計のレーダー", "设计中的雷达"],
  notWired: ["Not wired to a field node", "Sin nodo de campo asignado", "Keinem Feldknoten zugeordnet", "Aucun nœud de terrain associé", "Nessun nodo di campo assegnato", "フィールドノード未割り当て", "未分配现场节点"],
  wireInDesigner: ["Choose its node in the site designer (select the radar, field \"Field node\").", "Elige su nodo en el diseñador de emplazamiento (selecciona el radar, campo «Nodo de campo»).", "Knoten im Standortplaner wählen (Radar auswählen, Feld „Feldknoten“).", "Choisissez son nœud dans le concepteur de site (sélectionnez le radar, champ « Nœud de terrain »).", "Scegli il nodo nel progettista del sito (seleziona il radar, campo «Nodo di campo»).", "サイトデザイナーでノードを選択します（レーダーを選び「フィールドノード」欄）。", "在场地设计器中选择其节点（选中雷达，“现场节点”字段）。"],
  openDesigner: ["Open the site designer", "Abrir el diseñador de emplazamiento", "Standortplaner öffnen", "Ouvrir le concepteur de site", "Apri il progettista del sito", "サイトデザイナーを開く", "打开场地设计器"],
  unmappedNode: ["reports targets but no radar of the design is wired to it, so they cannot be drawn.", "informa de objetivos pero ningún radar del diseño está asignado a él, así que no se pueden dibujar.", "meldet Ziele, aber kein Radar des Entwurfs ist ihm zugeordnet, daher sind sie nicht darstellbar.", "signale des cibles mais aucun radar du plan ne lui est associé ; elles ne peuvent pas être dessinées.", "segnala bersagli ma nessun radar del progetto è assegnato ad esso, quindi non si possono disegnare.", "対象を報告していますが、設計のどのレーダーも割り当てられていないため描画できません。", "上报了目标，但设计中没有雷达分配给它，因此无法绘制。"],
  targetsLive: ["targets now", "objetivos ahora", "Ziele jetzt", "cibles maintenant", "bersagli ora", "現在の対象", "当前目标"],
  legendCounted: ["Counted target", "Objetivo contado", "Gezähltes Ziel", "Cible comptée", "Bersaglio contato", "カウント対象", "计入的目标"],
  legendIgnored: ["Ignored (in an ignore zone)", "Ignorado (en una zona ignorada)", "Ignoriert (in einer Ignorierzone)", "Ignorée (dans une zone ignorée)", "Ignorato (in una zona ignorata)", "無視（除外ゾーン内）", "已忽略（在忽略区内）"],
  legendOutside: ["Outside the sensor's rated sector", "Fuera del sector nominal del sensor", "Außerhalb des Nennsektors des Sensors", "Hors du secteur nominal du capteur", "Fuori dal settore nominale del sensore", "センサーの定格セクター外", "超出传感器额定扇区"],
  legendZone: ["Ignore zone", "Zona ignorada", "Ignorierzone", "Zone ignorée", "Zona ignorata", "除外ゾーン", "忽略区"],
  radarAxisNote: ["Where a target stands is computed from the radar's own axes (sideways x, forward y). The manual does not say which side positive x is on: it is taken to be to the right of where the radar faces. Check it with a real radar and use \"Mirror sideways axis\" in the designer if it is the other way round.", "La posición de un objetivo se calcula con los ejes del propio radar (x lateral, y hacia delante). El manual no dice a qué lado cae la x positiva: se toma a la derecha de hacia donde mira el radar. Compruébalo con un radar real y usa «Invertir eje lateral» en el diseñador si está al revés.", "Die Position eines Ziels wird aus den Achsen des Radars berechnet (x seitlich, y nach vorn). Das Handbuch nennt nicht, auf welcher Seite positives x liegt: angenommen rechts der Blickrichtung. Mit einem echten Radar prüfen und im Planer „Seitenachse spiegeln“ nutzen, falls es umgekehrt ist.", "La position d'une cible est calculée avec les axes du radar (x latéral, y vers l'avant). Le manuel ne dit pas de quel côté est le x positif : on suppose à droite du sens du radar. Vérifiez avec un vrai radar et utilisez « Inverser l'axe latéral » dans le concepteur si c'est l'inverse.", "La posizione di un bersaglio è calcolata dagli assi del radar (x laterale, y in avanti). Il manuale non dice da che parte sia la x positiva: si assume a destra della direzione del radar. Verifica con un radar reale e usa «Inverti asse laterale» nel progettista se è al contrario.", "対象の位置はレーダー自身の軸（横 x、前方 y）から計算します。マニュアルには正の x がどちら側か記載がなく、レーダーの向きの右側と仮定しています。実機で確認し、逆なら設計画面の「横軸を反転」を使ってください。", "目标位置由雷达自身的轴（横向 x、前向 y）计算。手册未说明正 x 在哪一侧，这里假定在雷达朝向的右侧。请用实物雷达核对，若相反，可在设计器中使用“翻转横轴”。"],
  sensorNode: ["Field node", "Nodo de campo", "Feldknoten", "Nœud de terrain", "Nodo di campo", "フィールドノード", "现场节点"],
  sensorNodeHelp: ["The node_id whose reports come from this radar.", "El node_id cuyos informes vienen de este radar.", "Die node_id, deren Meldungen von diesem Radar stammen.", "Le node_id dont les rapports viennent de ce radar.", "Il node_id i cui rapporti provengono da questo radar.", "このレーダーの報告元 node_id。", "由该雷达上报的 node_id。"],
  sensorChannel: ["Radar number (0 = any)", "Número de radar (0 = cualquiera)", "Radar-Nummer (0 = beliebig)", "Numéro de radar (0 = tous)", "Numero radar (0 = qualsiasi)", "レーダー番号（0＝すべて）", "雷达编号（0 = 任意）"],
  sensorMirror: ["Mirror sideways axis", "Invertir eje lateral", "Seitenachse spiegeln", "Inverser l'axe latéral", "Inverti asse laterale", "横軸を反転", "翻转横轴"],
  noNodeChosen: ["(none)", "(ninguno)", "(keiner)", "(aucun)", "(nessuno)", "（なし）", "（无）"],
  staleWord: ["Stale", "Sin señal", "Keine Meldung", "Sans signal", "Nessun segnale", "応答なし", "无信号"],
  offlineWord: ["Offline", "Sin conexión", "Offline", "Hors ligne", "Offline", "オフライン", "离线"],
  openNodePanel: ["Panel", "Panel", "Panel", "Panneau", "Pannello", "パネル", "面板"],
  firmwareWord: ["firmware", "firmware", "Firmware", "firmware", "firmware", "ファームウェア", "固件"],
  tracksWord: ["tracks", "seguimientos", "Spuren", "pistes", "tracce", "トラック", "轨迹"],
  radarSpeed: ["speed", "velocidad", "Geschwindigkeit", "vitesse", "velocità", "速度", "速度"],
  radarWord: ["Radar", "Radar", "Radar", "Radar", "Radar", "レーダー", "雷达"],
  addRadar: ["Add radar", "Añadir radar", "Radar hinzufügen", "Ajouter un radar", "Aggiungi radar", "レーダーを追加", "添加雷达"],
  deleteSensor: ["Delete radar", "Eliminar radar", "Radar löschen", "Supprimer le radar", "Elimina radar", "レーダーを削除", "删除雷达"],
  confirmDeleteSensor: ["Delete the radar", "Eliminar el radar", "Radar löschen:", "Supprimer le radar", "Eliminare il radar", "レーダーを削除:", "删除雷达"],
  noRadarsYet: ["No radars in the design yet. Add one, then choose the field node that reports for it.", "Aún no hay radares en el diseño. Añade uno y elige el nodo de campo que informa por él.", "Noch keine Radare im Plan. Fügen Sie eines hinzu und wählen Sie den Feldknoten, der dafür meldet.", "Aucun radar dans le plan. Ajoutez-en un puis choisissez le nœud de terrain qui le rapporte.", "Nessun radar nel progetto. Aggiungine uno e scegli il nodo di campo che lo riporta.", "設計にレーダーがありません。追加して、報告するフィールドノードを選んでください。", "设计中还没有雷达。添加一个，然后选择为其上报的现场节点。"],
  radarSetupHelp: ["Each LD2450 radar of the site: which field node and channel report for it, where it stands, how high and which way it faces. What you set here is what draws its coverage and places its targets on the map.", "Cada radar LD2450 del emplazamiento: qué nodo de campo y canal informan por él, dónde está, a qué altura y hacia dónde mira. Lo que fijes aquí dibuja su cobertura y coloca sus objetivos en el mapa.", "Jedes LD2450-Radar der Anlage: welcher Feldknoten und Kanal dafür meldet, wo es steht, wie hoch und wohin es blickt. Das bestimmt Abdeckung und Zielpositionen auf der Karte.", "Chaque radar LD2450 du site : quel nœud de terrain et quel canal le rapportent, où il se trouve, à quelle hauteur et vers où il regarde. Cela dessine sa couverture et place ses cibles sur la carte.", "Ogni radar LD2450 del sito: quale nodo di campo e canale lo riportano, dove si trova, a che altezza e dove guarda. Questo disegna la copertura e posiziona i bersagli sulla mappa.", "現場の各LD2450レーダー：どのフィールドノードとチャンネルが報告するか、設置場所、高さ、向き。ここでの設定がカバー範囲とターゲットの位置を決めます。", "现场的每个LD2450雷达：由哪个现场节点和通道上报、安装位置、高度和朝向。此处的设置决定其覆盖范围以及目标在地图上的位置。"],
  radarHardwareNote: ["These settings describe the installation for the map and the counting; the radar module itself keeps the configuration flashed in its node.", "Estos ajustes describen la instalación para el mapa y el recuento; el propio módulo radar conserva la configuración grabada en su nodo.", "Diese Einstellungen beschreiben die Installation für Karte und Zählung; das Radarmodul selbst behält die in seinem Knoten gespeicherte Konfiguration.", "Ces réglages décrivent l'installation pour la carte et le comptage ; le module radar garde la configuration flashée dans son nœud.", "Queste impostazioni descrivono l'installazione per la mappa e il conteggio; il modulo radar mantiene la configurazione caricata nel suo nodo.", "この設定は地図とカウントのための設置情報です。レーダーモジュール自体はノードに書き込まれた設定を保持します。", "这些设置描述安装情况，用于地图和计数；雷达模块本身保留写入其节点的配置。"],
  ignoreZonesOf: ["Ignore zones", "Zonas ignoradas", "Ignorierzonen", "Zones ignorées", "Zone ignorate", "無視ゾーン", "忽略区域"],
  zonesShort: ["zones", "zonas", "Zonen", "zones", "zone", "ゾーン", "区域"],
  radarState_online: ["online", "en línea", "online", "en ligne", "online", "オンライン", "在线"],
  radarState_offline: ["offline", "sin conexión", "offline", "hors ligne", "offline", "オフライン", "离线"],
  radarState_stale: ["no recent data", "sin datos recientes", "keine aktuellen Daten", "pas de données récentes", "nessun dato recente", "最新データなし", "无最新数据"],
  radarState_unwired: ["not linked to a node", "sin nodo asignado", "keinem Knoten zugeordnet", "sans nœud associé", "nessun nodo associato", "ノード未割り当て", "未关联节点"],
  addNode270: ["Add a 270° node", "Añadir un nodo de 270°", "270°-Knoten hinzufügen", "Ajouter un nœud de 270°", "Aggiungi un nodo a 270°", "270°ノードを追加", "添加270°节点"],
  node270Help: ["A node with three radars covers 270°: each radar sees 120° and they face 75° apart, so neighbours overlap by 45°. This creates the three radars in one place, wired to the node as radars 1, 2 and 3 (1 on the left of the middle one, 3 on the right). Move them to where the node stands afterwards.", "Un nodo con tres radares cubre 270°: cada radar ve 120° y miran con 75° de diferencia, así que los vecinos se solapan 45°. Esto crea los tres radares en un mismo sitio, asignados al nodo como radares 1, 2 y 3 (el 1 a la izquierda del central, el 3 a la derecha). Después muévelos al lugar del nodo.", "Ein Knoten mit drei Radaren deckt 270° ab: jedes Radar sieht 120° und sie zeigen 75° auseinander, Nachbarn überlappen also um 45°. Dies legt die drei Radare an einem Ort an, dem Knoten als Radar 1, 2 und 3 zugeordnet (1 links vom mittleren, 3 rechts). Verschieben Sie sie danach an den Standort des Knotens.", "Un nœud à trois radars couvre 270° : chaque radar voit 120° et ils sont orientés à 75° l'un de l'autre, les voisins se recouvrent donc de 45°. Cela crée les trois radars au même endroit, associés au nœud comme radars 1, 2 et 3 (1 à gauche du central, 3 à droite). Déplacez-les ensuite à l'emplacement du nœud.", "Un nodo con tre radar copre 270°: ogni radar vede 120° e sono orientati a 75° l'uno dall'altro, quindi i vicini si sovrappongono di 45°. Questo crea i tre radar nello stesso punto, associati al nodo come radar 1, 2 e 3 (1 a sinistra di quello centrale, 3 a destra). Poi spostali dove si trova il nodo.", "3つのレーダーを持つノードは270°をカバーします。各レーダーは120°を見て75°ずつ離れて向くため、隣同士は45°重なります。同じ場所に3つのレーダーをノードのレーダー1・2・3として作成します（1は中央の左、3は右）。あとでノードの設置場所へ移動してください。", "带三个雷达的节点可覆盖270°：每个雷达视角120°，彼此相差75°朝向，相邻雷达重叠45°。这会在同一位置创建三个雷达，并作为节点的雷达1、2、3（1在中间的左侧，3在右侧）。之后请把它们移到节点所在位置。"],
  node270Name: ["Name of the node's radars", "Nombre de los radares del nodo", "Name der Radare des Knotens", "Nom des radars du nœud", "Nome dei radar del nodo", "ノードのレーダー名", "节点雷达名称"],
  node270Heading: ["The middle radar faces", "El radar central mira hacia", "Das mittlere Radar blickt nach", "Le radar central regarde vers", "Il radar centrale guarda verso", "中央のレーダーの向き", "中间雷达朝向"],
  node270Create: ["Create the three radars", "Crear los tres radares", "Die drei Radare anlegen", "Créer les trois radars", "Crea i tre radar", "3つのレーダーを作成", "创建三个雷达"],
};

export const radarCatalogues = cataloguesFromRows(ROWS);
