/**
 * The phrases of the Services menu (every program and field node of the system, running or not), in the seven languages.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
 */
import { cataloguesFromRows, type Row } from "./catalogueRows";

const ROWS: Record<string, Row> = {
  services: ["Services", "Servicios", "Dienste", "Services", "Servizi", "サービス", "服务"],
  servicesTitle: ["SERVICES", "SERVICIOS", "DIENSTE", "SERVICES", "SERVIZI", "サービス", "服务"],
  servicesHelp: ["Every program of the system and every field node, running or not: the server, Studio, the MQTT broker, the network node, the AI and voice services and the radars and meters that report.", "Todos los programas del sistema y todos los nodos de campo, activos o no: el servidor, Studio, el broker MQTT, el nodo de red, los servicios de IA y voz y los radares y medidores que reportan.", "Jedes Programm des Systems und jeder Feldknoten, laufend oder nicht: der Server, Studio, der MQTT-Broker, der Netzwerkknoten, die KI- und Sprachdienste sowie die meldenden Radare und Zähler.", "Chaque programme du système et chaque nœud de terrain, actif ou non : le serveur, Studio, le broker MQTT, le nœud réseau, les services d'IA et de voix et les radars et compteurs qui font leur rapport.", "Ogni programma del sistema e ogni nodo di campo, attivo o no: il server, Studio, il broker MQTT, il nodo di rete, i servizi di IA e voce e i radar e i contatori che riferiscono.", "システムのすべてのプログラムとフィールドノードを、稼働中かどうかにかかわらず表示します：サーバー、Studio、MQTT ブローカー、ネットワークノード、AI と音声のサービス、報告するレーダーとメーター。", "系统的每个程序和每个现场节点，无论是否在运行：服务器、Studio、MQTT 代理、网络节点、AI 与语音服务，以及上报数据的雷达和电表。"],
  svcRefresh: ["Refresh", "Actualizar", "Aktualisieren", "Actualiser", "Aggiorna", "更新", "刷新"],
  svcTotal: ["Services", "Servicios", "Dienste", "Services", "Servizi", "サービス", "服务"],
  svcActive: ["Active", "Activos", "Aktiv", "Actifs", "Attivi", "稼働", "运行中"],
  svcInactive: ["Not active", "No activos", "Nicht aktiv", "Inactifs", "Non attivi", "停止", "未运行"],
  svcFailed: ["Failed", "Con fallo", "Fehlgeschlagen", "En échec", "Falliti", "失敗", "故障"],
  svcOther: ["Not installed / unknown", "No instalados / desconocidos", "Nicht installiert / unbekannt", "Non installés / inconnus", "Non installati / sconosciuti", "未インストール／不明", "未安装／未知"],
  svcFamilies: ["Families", "Familias", "Familien", "Familles", "Famiglie", "ファミリー", "分组"],
  svcSearch: ["Search a service", "Buscar un servicio", "Dienst suchen", "Chercher un service", "Cerca un servizio", "サービスを検索", "搜索服务"],
  svcAllFamilies: ["All", "Todas", "Alle", "Toutes", "Tutte", "すべて", "全部"],
  svcShowAll: ["All", "Todos", "Alle", "Tous", "Tutti", "すべて", "全部"],
  svcNone: ["No service matches.", "Ningún servicio coincide.", "Kein Dienst passt.", "Aucun service ne correspond.", "Nessun servizio corrisponde.", "該当するサービスがありません。", "没有匹配的服务。"],
  svcLoadError: ["The server did not answer the list of services.", "El servidor no respondió la lista de servicios.", "Der Server hat die Dienstliste nicht beantwortet.", "Le serveur n'a pas répondu la liste des services.", "Il server non ha risposto con l'elenco dei servizi.", "サーバーがサービス一覧に応答しませんでした。", "服务器没有返回服务列表。"],
  svcNoSystemd: ["This machine has no systemd, so the state of its programs is not known; the field nodes are still listed.", "Esta máquina no tiene systemd, así que no se conoce el estado de sus programas; los nodos de campo sí se listan.", "Dieser Rechner hat kein systemd, daher ist der Zustand seiner Programme unbekannt; die Feldknoten werden trotzdem aufgelistet.", "Cette machine n'a pas systemd : l'état de ses programmes est inconnu ; les nœuds de terrain sont tout de même listés.", "Questa macchina non ha systemd, quindi lo stato dei suoi programmi non è noto; i nodi di campo sono comunque elencati.", "このマシンには systemd がないため、プログラムの状態は分かりません。フィールドノードは表示されます。", "此机器没有 systemd，因此不知道其程序的状态；现场节点仍会列出。"],
  svcReadOnly: ["Each program of this machine can be started, stopped, restarted, paused and resumed from its card by an administrator; field nodes are only shown.", "Cada programa de esta máquina se puede arrancar, parar, reiniciar, pausar y reanudar desde su tarjeta por un administrador; los nodos de campo solo se muestran.", "Ein Administrator kann jedes Programm dieser Maschine über seine Karte starten, stoppen, neu starten, pausieren und fortsetzen; Feldknoten werden nur angezeigt.", "Un administrateur peut démarrer, arrêter, redémarrer, mettre en pause et reprendre chaque programme de cette machine depuis sa carte ; les nœuds de terrain sont seulement affichés.", "Un amministratore può avviare, fermare, riavviare, mettere in pausa e riprendere ogni programma di questa macchina dalla sua scheda; i nodi di campo vengono solo mostrati.", "管理者は、このマシンの各プログラムをカードから起動・停止・再起動・一時停止・再開できます。現場ノードは表示のみです。", "管理员可以在每个程序的卡片上启动、停止、重启、暂停和继续本机的程序；现场节点仅作显示。"],
  svcState_paused: ["Paused", "En pausa", "Pausiert", "En pause", "In pausa", "一時停止中", "已暂停"],
  svcBtn_start: ["Start", "Arrancar", "Starten", "Démarrer", "Avvia", "起動", "启动"],
  svcBtn_stop: ["Stop", "Parar", "Stoppen", "Arrêter", "Ferma", "停止", "停止"],
  svcBtn_restart: ["Restart", "Reiniciar", "Neu starten", "Redémarrer", "Riavvia", "再起動", "重启"],
  svcBtn_pause: ["Pause", "Pausar", "Pausieren", "Mettre en pause", "Metti in pausa", "一時停止", "暂停"],
  svcBtn_resume: ["Resume", "Reanudar", "Fortsetzen", "Reprendre", "Riprendi", "再開", "继续"],
  svcAsk_stop: ["It stops, and what depends on it stops working until it is started again.", "Se para, y lo que depende de él deja de funcionar hasta que se arranque de nuevo.", "Er wird gestoppt, und was von ihm abhängt, funktioniert nicht mehr, bis er wieder gestartet wird.", "Il s'arrête, et ce qui en dépend ne fonctionne plus tant qu'il n'est pas redémarré.", "Si ferma, e ciò che ne dipende smette di funzionare finché non viene riavviato.", "停止します。再び起動するまで、これに依存するものは動作しません。", "它会停止，依赖它的功能在重新启动前将无法使用。"],
  svcAsk_stop_console: ["The console you are using stops answering. To start it again it has to be done on the machine.", "La consola que estás usando deja de responder. Para arrancarla otra vez hay que hacerlo en la máquina.", "Die Konsole, die du benutzt, antwortet nicht mehr. Zum erneuten Starten muss es an der Maschine geschehen.", "La console que tu utilises cesse de répondre. Pour la redémarrer, il faut le faire sur la machine.", "La console che stai usando smette di rispondere. Per riavviarla bisogna farlo sulla macchina.", "使用中のコンソールが応答しなくなります。再起動するにはマシン上で操作する必要があります。", "你正在使用的控制台将不再响应。要再次启动，必须在机器上操作。"],
  svcAsk_restart: ["It restarts and is unavailable for a few seconds.", "Se reinicia y no está disponible unos segundos.", "Er wird neu gestartet und ist einige Sekunden nicht verfügbar.", "Il redémarre et est indisponible quelques secondes.", "Si riavvia e non è disponibile per qualche secondo.", "再起動し、数秒間利用できなくなります。", "它会重启，并在几秒内不可用。"],
  svcAsk_restart_console: ["The console restarts and is unavailable for a few seconds; the page reconnects by itself.", "La consola se reinicia y no está disponible unos segundos; la página se reconecta sola.", "Die Konsole startet neu und ist einige Sekunden nicht verfügbar; die Seite verbindet sich von selbst neu.", "La console redémarre et est indisponible quelques secondes ; la page se reconnecte toute seule.", "La console si riavvia e non è disponibile per qualche secondo; la pagina si riconnette da sola.", "コンソールが再起動し、数秒間利用できなくなります。ページは自動的に再接続します。", "控制台会重启，并在几秒内不可用；页面会自动重新连接。"],
  svcAsk_pause: ["The program is frozen where it is: it keeps its memory but answers nothing until you resume it. Nothing is lost.", "El programa se congela donde está: conserva su memoria pero no responde a nada hasta que lo reanudes. No se pierde nada.", "Das Programm wird eingefroren: Es behält seinen Speicher, antwortet aber auf nichts, bis du es fortsetzt. Nichts geht verloren.", "Le programme est figé là où il est : il garde sa mémoire mais ne répond à rien jusqu'à ce que tu le reprennes. Rien n'est perdu.", "Il programma si congela dove si trova: mantiene la memoria ma non risponde a nulla finché non lo riprendi. Non si perde nulla.", "プログラムはその場で凍結されます。メモリは保持されますが、再開するまで何にも応答しません。何も失われません。", "程序会停在当前状态：保留内存，但在你继续之前不响应任何请求。不会丢失任何内容。"],
  svcDone_start: ["started", "arrancado", "gestartet", "démarré", "avviato", "起動しました", "已启动"],
  svcDone_stop: ["stopped", "parado", "gestoppt", "arrêté", "fermato", "停止しました", "已停止"],
  svcDone_restart: ["restarted", "reiniciado", "neu gestartet", "redémarré", "riavviato", "再起動しました", "已重启"],
  svcDone_pause: ["paused", "en pausa", "pausiert", "mis en pause", "messo in pausa", "一時停止しました", "已暂停"],
  svcDone_resume: ["resumed", "reanudado", "fortgesetzt", "repris", "ripreso", "再開しました", "已继续"],
  svcActionFailed: ["The action could not be done", "No se pudo hacer la acción", "Die Aktion war nicht möglich", "L'action n'a pas pu être faite", "Non è stato possibile eseguire l'azione", "操作できませんでした", "无法执行该操作"],
  svcNoAgent: ["The administration agent of the machine does not answer, so the buttons are not shown (see Configuration > Services).", "El agente de administración de la máquina no responde, así que no se muestran los botones (ver Configuración > Servicios).", "Der Administrationsagent der Maschine antwortet nicht, daher werden die Schaltflächen nicht angezeigt (siehe Konfiguration > Dienste).", "L'agent d'administration de la machine ne répond pas, les boutons ne sont donc pas affichés (voir Configuration > Services).", "L'agente di amministrazione della macchina non risponde, quindi i pulsanti non vengono mostrati (vedi Configurazione > Servizi).", "マシンの管理エージェントが応答しないため、ボタンは表示されません（設定 > サービスを参照）。", "本机的管理代理没有响应，因此不显示按钮（见配置 > 服务）。"],
  svcUpdated: ["Updated", "Actualizado", "Aktualisiert", "Mis à jour", "Aggiornato", "更新", "更新于"],
  svcState_running: ["Running", "En marcha", "Läuft", "En marche", "In esecuzione", "稼働中", "运行中"],
  svcState_online: ["Online", "En línea", "Online", "En ligne", "Online", "オンライン", "在线"],
  svcState_stopped: ["Stopped", "Parado", "Gestoppt", "Arrêté", "Fermo", "停止", "已停止"],
  svcState_offline: ["Offline", "Sin conexión", "Offline", "Hors ligne", "Offline", "オフライン", "离线"],
  svcState_failed: ["Failed", "Con fallo", "Fehlgeschlagen", "En échec", "Fallito", "失敗", "故障"],
  svcState_starting: ["Starting", "Arrancando", "Startet", "Démarrage", "In avvio", "起動中", "启动中"],
  svcState_not_installed: ["Not installed", "No instalado", "Nicht installiert", "Non installé", "Non installato", "未インストール", "未安装"],
  svcState_unknown: ["Unknown", "Desconocido", "Unbekannt", "Inconnu", "Sconosciuto", "不明", "未知"],
  svcFamily_Core: ["Core", "Núcleo", "Kern", "Cœur", "Nucleo", "コア", "核心"],
  svcFamily_Network: ["Network", "Red", "Netzwerk", "Réseau", "Rete", "ネットワーク", "网络"],
  svcFamily_AI_and_voice: ["AI and voice", "IA y voz", "KI und Sprache", "IA et voix", "IA e voce", "AI と音声", "AI 与语音"],
  svcFamily_Field_nodes: ["Field nodes", "Nodos de campo", "Feldknoten", "Nœuds de terrain", "Nodi di campo", "フィールドノード", "现场节点"],
  svcDesc_server: ["Central state, alarms, users, cameras, evidence and the API", "Estado central, alarmas, usuarios, cámaras, evidencias y la API", "Zentraler Zustand, Alarme, Benutzer, Kameras, Beweise und die API", "État central, alarmes, utilisateurs, caméras, preuves et l'API", "Stato centrale, allarmi, utenti, telecamere, prove e l'API", "中央の状態、アラーム、ユーザー、カメラ、証拠、API", "中央状态、报警、用户、摄像头、证据和 API"],
  svcDesc_studio: ["The web console", "La consola web", "Die Web-Konsole", "La console web", "La console web", "Web コンソール", "网页控制台"],
  svcDesc_broker: ["Where the field nodes publish what they read", "Donde los nodos de campo publican lo que leen", "Wo die Feldknoten veröffentlichen, was sie lesen", "Où les nœuds de terrain publient ce qu'ils lisent", "Dove i nodi di campo pubblicano ciò che leggono", "フィールドノードが読み取った内容を公開する場所", "现场节点发布其读数的地方"],
  svcDesc_network: ["Watches the local network: devices, internet and what changes", "Vigila la red local: dispositivos, internet y lo que cambia", "Beobachtet das lokale Netz: Geräte, Internet und was sich ändert", "Surveille le réseau local : appareils, internet et ce qui change", "Sorveglia la rete locale: dispositivi, internet e cosa cambia", "ローカルネットワークを監視：デバイス、インターネット、変化", "监视本地网络：设备、互联网和变化"],
  svcDesc_server_ai: ["Decides what a camera detection means (day and night, movement first)", "Decide qué significa una detección de cámara (día y noche, movimiento primero)", "Entscheidet, was eine Kameraerkennung bedeutet (Tag und Nacht, Bewegung zuerst)", "Décide ce que signifie une détection de caméra (jour et nuit, mouvement d'abord)", "Decide cosa significa un rilevamento della telecamera (giorno e notte, prima il movimento)", "カメラの検出の意味を判断（昼夜、まず動き）", "判断摄像头检测的含义（昼夜、先看移动）"],
  svcDesc_voice_ai: ["Spoken commands with a confirmation", "Órdenes por voz con confirmación", "Sprachbefehle mit Bestätigung", "Commandes vocales avec confirmation", "Comandi vocali con conferma", "確認付きの音声コマンド", "带确认的语音指令"],
  svcDesc_radar: ["Radar node", "Nodo radar", "Radarknoten", "Nœud radar", "Nodo radar", "レーダーノード", "雷达节点"],
  svcDesc_electrical: ["Electrical node", "Nodo eléctrico", "Elektrischer Knoten", "Nœud électrique", "Nodo elettrico", "電気ノード", "电气节点"],
  svcUnit: ["Unit", "Unidad", "Einheit", "Unité", "Unità", "ユニット", "单元"],
  svcPid: ["PID", "PID", "PID", "PID", "PID", "PID", "PID"],
  svcMemory: ["Memory", "Memoria", "Speicher", "Mémoire", "Memoria", "メモリ", "内存"],
  svcRestarts: ["Restarts", "Reinicios", "Neustarts", "Redémarrages", "Riavvii", "再起動", "重启次数"],
  svcSince: ["Up for", "Activo desde hace", "Läuft seit", "Actif depuis", "Attivo da", "稼働時間", "已运行"],
  svcVersion: ["Version", "Versión", "Version", "Version", "Versione", "バージョン", "版本"],
  svcLastSeen: ["Last heard", "Última señal", "Zuletzt gehört", "Dernier signal", "Ultimo segnale", "最終受信", "最后收到"],
  svcAtBoot: ["Starts at boot", "Arranca con el equipo", "Startet beim Booten", "Démarre au boot", "Parte all'avvio", "起動時に開始", "开机启动"],
  svcNotAtBoot: ["Not at boot", "No arranca con el equipo", "Nicht beim Booten", "Pas au boot", "Non all'avvio", "起動時は開始しない", "不开机启动"],
  svcPort: ["Port", "Puerto", "Port", "Port", "Porta", "ポート", "端口"],
};

export const servicesCatalogues = cataloguesFromRows(ROWS);
