/**
 * Interface text of the Solar menu (inverters and batteries read by the gateway nodes), one row per phrase in the seven languages.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
 */
import { cataloguesFromRows, type Row } from "./catalogueRows";

const ROWS: Record<string, Row> = {
  solar: ["Solar", "Solar", "Solar", "Solaire", "Solare", "ソーラー", "太阳能"],
  solarTitle: ["Solar energy", "Energía solar", "Solarenergie", "Énergie solaire", "Energia solare", "太陽光発電", "太阳能发电"],
  solarHelp: ["Inverters and batteries as the gateway nodes read them. You declare the equipment here; its readings are read-only.", "Inversores y baterías tal como los leen los nodos pasarela. Aquí declaras los equipos; sus lecturas son de solo lectura.", "Wechselrichter und Batterien, wie die Gateway-Knoten sie lesen. Hier deklarierst du die Geräte; ihre Messwerte sind nur lesbar.", "Onduleurs et batteries tels que les nœuds passerelles les lisent. Vous déclarez ici les équipements ; leurs relevés sont en lecture seule.", "Inverter e batterie come li leggono i nodi gateway. Qui dichiari i dispositivi; le loro letture sono di sola lettura.", "ゲートウェイノードが読み取ったインバーターとバッテリー。ここで機器を登録します。測定値は読み取り専用です。", "网关节点读取的逆变器和电池。在此登记设备；其读数为只读。"],
  solarPv2: ["Second PV input", "Segunda entrada fotovoltaica", "Zweiter PV-Eingang", "Seconde entrée photovoltaïque", "Secondo ingresso fotovoltaico", "2 つ目の PV 入力", "第二路光伏输入"],
  solarUnits: ["Units of the parallel system", "Unidades del sistema en paralelo", "Einheiten des Parallelsystems", "Unités du système en parallèle", "Unità del sistema in parallelo", "並列システムのユニット", "并联系统的单元"],
  solarUnit: ["Unit", "Unidad", "Einheit", "Unité", "Unità", "ユニット", "单元"],
  solarSystemTotal: ["System total", "Total del sistema", "Summe des Systems", "Total du système", "Totale del sistema", "システム合計", "系统总计"],
  solarFault: ["fault", "fallo", "Fehler", "défaut", "guasto", "故障", "故障"],
  solarPv: ["Solar panels", "Paneles solares", "Solarmodule", "Panneaux solaires", "Pannelli solari", "太陽光パネル", "光伏板"],
  solarLoad: ["House load", "Consumo de la casa", "Hausverbrauch", "Consommation de la maison", "Consumo della casa", "住宅の負荷", "家庭负载"],
  solarBattery: ["Battery", "Batería", "Batterie", "Batterie", "Batteria", "バッテリー", "电池"],
  solarGrid: ["Grid", "Red eléctrica", "Netz", "Réseau", "Rete", "系統", "电网"],
  solarMode: ["Inverter mode", "Modo del inversor", "Wechselrichter-Modus", "Mode de l'onduleur", "Modalità dell'inverter", "インバーターのモード", "逆变器模式"],
  solarGridOn: ["connected", "conectada", "verbunden", "connecté", "collegata", "接続中", "已连接"],
  solarGridOff: ["no grid", "sin red", "kein Netz", "pas de réseau", "senza rete", "系統なし", "无电网"],
  solarCharging: ["charging", "cargando", "lädt", "en charge", "in carica", "充電中", "充电中"],
  solarDischarging: ["discharging", "descargando", "entlädt", "en décharge", "in scarica", "放電中", "放电中"],
  solarIdle: ["idle", "en reposo", "Leerlauf", "au repos", "a riposo", "待機中", "待机"],
  solarMode_power_on: ["power on", "encendiéndose", "wird eingeschaltet", "mise sous tension", "accensione", "起動中", "正在开机"],
  solarMode_standby: ["standby", "en espera", "Standby", "en veille", "in attesa", "スタンバイ", "待机"],
  solarMode_line: ["on the grid", "con la red", "am Netz", "sur le réseau", "sulla rete", "系統運転", "市电模式"],
  solarMode_battery: ["on the battery", "con la batería", "im Batteriebetrieb", "sur batterie", "a batteria", "バッテリー運転", "电池模式"],
  solarMode_fault: ["fault", "avería", "Störung", "défaut", "guasto", "故障", "故障"],
  solarMode_power_saving: ["power saving", "ahorro de energía", "Energiesparen", "économie d'énergie", "risparmio energetico", "省電力", "节能"],
  solarMode_shutdown: ["shut down", "apagado", "abgeschaltet", "arrêté", "spento", "停止", "已关机"],
  solarMode_unknown: ["unknown", "desconocido", "unbekannt", "inconnu", "sconosciuto", "不明", "未知"],
  inverters: ["Inverters", "Inversores", "Wechselrichter", "Onduleurs", "Inverter", "インバーター", "逆变器"],
  batteries: ["Batteries", "Baterías", "Batterien", "Batteries", "Batterie", "バッテリー", "电池"],
  navEnergy: ["Solar energy", "Energía solar", "Solarenergie", "Énergie solaire", "Energia solare", "太陽光発電", "太阳能"],
  solarCapacity: ["Capacity", "Capacidad", "Kapazität", "Capacité", "Capacità", "容量", "容量"],
  solarHealth: ["Health (capacity against new)", "Salud (capacidad frente a nueva)", "Zustand (Kapazität gegenüber neu)", "État (capacité par rapport au neuf)", "Stato (capacità rispetto al nuovo)", "劣化状態（新品比の容量）", "健康度（相对新品的容量）"],
  solarCycles: ["Charge cycles", "Ciclos de carga", "Ladezyklen", "Cycles de charge", "Cicli di carica", "充電サイクル", "充电循环"],
  solarModule: ["Module", "Módulo", "Modul", "Module", "Modulo", "モジュール", "模块"],
  solarNone: ["No solar equipment yet", "Aún no hay equipos solares", "Noch keine Solaranlage", "Pas encore d'équipement solaire", "Ancora nessun impianto solare", "ソーラー機器はまだありません", "尚无太阳能设备"],
  solarNoneHelp: ["A gateway node that reads inverters and batteries publishes them here; how to build one is in the ARMOR-SOLAR documentation.", "Un nodo pasarela que lee inversores y baterías los publica aquí; cómo montar uno está en la documentación de ARMOR-SOLAR.", "Ein Gateway-Knoten, der Wechselrichter und Batterien liest, veröffentlicht sie hier; wie man ihn baut, steht in der ARMOR-SOLAR-Dokumentation.", "Un nœud passerelle qui lit onduleurs et batteries les publie ici ; comment en construire un est dans la documentation d'ARMOR-SOLAR.", "Un nodo gateway che legge inverter e batterie li pubblica qui; come costruirlo è nella documentazione di ARMOR-SOLAR.", "インバーターとバッテリーを読み取るゲートウェイノードがここに公開します。作り方はARMOR-SOLARの文書にあります。", "读取逆变器和电池的网关节点会在此发布；搭建方法见 ARMOR-SOLAR 文档。"],
  solarStale: ["no data for a while", "sin datos desde hace rato", "seit einiger Zeit keine Daten", "pas de données depuis un moment", "nessun dato da un po'", "しばらくデータなし", "已有一段时间无数据"],
  solarWarnings: ["Warnings and faults", "Avisos y averías", "Warnungen und Störungen", "Avertissements et défauts", "Avvisi e guasti", "警告と故障", "警告与故障"],
  solarNoWarnings: ["none", "ninguno", "keine", "aucun", "nessuno", "なし", "无"],
  solarModules: ["modules", "módulos", "Module", "modules", "moduli", "モジュール", "模块"],
  solarModuleAbsent: ["not present", "ausente", "nicht vorhanden", "absent", "assente", "未接続", "不存在"],
  solarNoModules: ["The battery does not answer.", "La batería no responde.", "Die Batterie antwortet nicht.", "La batterie ne répond pas.", "La batteria non risponde.", "バッテリーが応答しません。", "电池没有响应。"],
  solarTemperature: ["Temperature", "Temperatura", "Temperatur", "Température", "Temperatura", "温度", "温度"],
  solarCells: ["Cells", "Celdas", "Zellen", "Cellules", "Celle", "セル", "电芯"],
  solarCurrent: ["Current", "Corriente", "Strom", "Courant", "Corrente", "電流", "电流"],
  solarVoltage: ["Voltage", "Tensión", "Spannung", "Tension", "Tensione", "電圧", "电压"],
  solarSoc: ["State of charge", "Estado de carga", "Ladezustand", "État de charge", "Stato di carica", "充電状態", "电量状态"],
  solarHeatsink: ["Heat sink", "Disipador", "Kühlkörper", "Dissipateur", "Dissipatore", "ヒートシンク", "散热器"],
  solarOutput: ["Output", "Salida", "Ausgang", "Sortie", "Uscita", "出力", "输出"],
  solarAlarmOn: ["alarm", "alarma", "Alarm", "alarme", "allarme", "警報", "报警"],
  solarHistory: ["History", "Historial", "Verlauf", "Historique", "Storico", "履歴", "历史"],
  solarRange1: ["1 hour", "1 hora", "1 Stunde", "1 heure", "1 ora", "1時間", "1小时"],
  solarRange6: ["6 hours", "6 horas", "6 Stunden", "6 heures", "6 ore", "6時間", "6小时"],
  solarRange24: ["24 hours", "24 horas", "24 Stunden", "24 heures", "24 ore", "24時間", "24小时"],
  solarNoHistory: ["Not enough data yet.", "Aún no hay datos suficientes.", "Noch nicht genug Daten.", "Pas encore assez de données.", "Non ci sono ancora dati sufficienti.", "まだデータが十分ではありません。", "数据尚不足。"],
  solarPvPower: ["Panels (W)", "Paneles (W)", "Module (W)", "Panneaux (W)", "Pannelli (W)", "パネル (W)", "光伏板 (W)"],
  solarLoadPower: ["Load (W)", "Consumo (W)", "Verbrauch (W)", "Consommation (W)", "Consumo (W)", "負荷 (W)", "负载 (W)"],
  solarChargeLevel: ["Charge (%)", "Carga (%)", "Ladung (%)", "Charge (%)", "Carica (%)", "充電 (%)", "电量 (%)"],
  solarUpdated: ["updated", "actualizado", "aktualisiert", "mis à jour", "aggiornato", "更新", "更新于"],
  solarBatteryPower: ["Battery power", "Potencia de la batería", "Batterieleistung", "Puissance de la batterie", "Potenza della batteria", "バッテリー電力", "电池功率"],
  alarm_solar_fault: ["A solar inverter reports a fault", "Un inversor solar informa de una avería", "Ein Solar-Wechselrichter meldet eine Störung", "Un onduleur solaire signale un défaut", "Un inverter solare segnala un guasto", "ソーラーインバーターが故障を報告しています", "太阳能逆变器报告故障"],
  alarm_solar_battery_low: ["The solar battery is low", "La batería solar está baja", "Die Solarbatterie ist schwach", "La batterie solaire est faible", "La batteria solare è scarica", "ソーラーバッテリーの残量が少なくなっています", "太阳能电池电量低"],
  alarm_solar_battery_alarm: ["A solar battery reports an alarm", "Una batería solar informa de una alarma", "Eine Solarbatterie meldet einen Alarm", "Une batterie solaire signale une alarme", "Una batteria solare segnala un allarme", "ソーラーバッテリーが警報を報告しています", "太阳能电池报告报警"],
  alarm_solar_offline: ["A solar device stopped answering", "Un equipo solar dejó de responder", "Ein Solargerät antwortet nicht mehr", "Un équipement solaire ne répond plus", "Un dispositivo solare non risponde più", "ソーラー機器が応答しなくなりました", "太阳能设备不再响应"],
  alarm_electrical_alarm: ["A meter of the electrical network reports an alarm", "Un contador de la red eléctrica avisa de una alarma", "Ein Zähler des Stromnetzes meldet einen Alarm", "Un compteur du réseau électrique signale une alarme", "Un contatore della rete elettrica segnala un allarme", "電力網の電力量計が警報を出しています", "电网的电表报告了告警"],
  alarm_electrical_voltage: ["The mains voltage is out of range", "La tensión de red está fuera de rango", "Die Netzspannung liegt außerhalb des Bereichs", "La tension du secteur est hors plage", "La tensione di rete è fuori intervallo", "商用電源の電圧が範囲外です", "市电电压超出范围"],
  alarm_electrical_grid_lost: ["The grid supply is lost", "Se ha perdido el suministro de la red", "Die Netzversorgung ist ausgefallen", "L'alimentation du réseau est perdue", "L'alimentazione di rete è mancante", "系統からの電力供給が失われました", "电网供电已中断"],
  alarm_electrical_offline: ["An electrical node stopped answering", "Un nodo eléctrico dejó de responder", "Ein Elektroknoten antwortet nicht mehr", "Un nœud électrique ne répond plus", "Un nodo elettrico non risponde più", "電気ノードが応答しなくなりました", "电气节点不再应答"],
  alarm_electrical_switch_fault: ["A source switch of the electrical network has a fault and is left open", "Un conmutador de fuentes de la red eléctrica tiene una avería y queda abierto", "Ein Quellenumschalter des Stromnetzes hat einen Fehler und bleibt offen", "Un inverseur de sources du réseau électrique est en défaut et reste ouvert", "Un commutatore di sorgenti della rete elettrica è in guasto e resta aperto", "電源切替器に異常があり、開いたままです", "电网的电源切换开关发生故障并保持断开"],
  solarAddInverter: ["Add an inverter", "Añadir un inversor", "Wechselrichter hinzufügen", "Ajouter un onduleur", "Aggiungi un inverter", "インバーターを追加", "添加逆变器"],
  solarAddBattery: ["Add a battery", "Añadir una batería", "Batterie hinzufügen", "Ajouter une batterie", "Aggiungi una batteria", "バッテリーを追加", "添加电池"],
  solarEditDevice: ["Edit", "Editar", "Bearbeiten", "Modifier", "Modifica", "編集", "编辑"],
  solarDelete: ["Delete", "Eliminar", "Löschen", "Supprimer", "Elimina", "削除", "删除"],
  solarConfirmDelete: ["Forget this equipment and its readings?", "¿Olvidar este equipo y sus lecturas?", "Dieses Gerät und seine Messwerte vergessen?", "Oublier cet équipement et ses relevés ?", "Dimenticare questo dispositivo e le sue letture?", "この機器とその測定値を削除しますか？", "忘记此设备及其读数？"],
  solarName: ["Name", "Nombre", "Name", "Nom", "Nome", "名前", "名称"],
  solarModelLabel: ["Model", "Modelo", "Modell", "Modèle", "Modello", "モデル", "型号"],
  solarConnection: ["Connection", "Conexión", "Anschluss", "Connexion", "Collegamento", "接続", "连接方式"],
  solarNode: ["Gateway node", "Nodo pasarela", "Gateway-Knoten", "Nœud passerelle", "Nodo gateway", "ゲートウェイノード", "网关节点"],
  solarNodeHelp: ["The node that reads this equipment through its serial port, for example solar-1.", "El nodo que lee este equipo por su puerto serie, por ejemplo solar-1.", "Der Knoten, der dieses Gerät über seine serielle Schnittstelle liest, zum Beispiel solar-1.", "Le nœud qui lit cet équipement par son port série, par exemple solar-1.", "Il nodo che legge questo dispositivo dalla sua porta seriale, per esempio solar-1.", "このシリアルポート経由で機器を読み取るノード（例：solar-1）。", "通过串口读取此设备的节点，例如 solar-1。"],
  solarNotes: ["Notes", "Notas", "Notizen", "Notes", "Note", "メモ", "备注"],
  solarIdentifier: ["Identifier", "Identificador", "Kennung", "Identifiant", "Identificatore", "識別子", "标识"],
  solarSave: ["Save", "Guardar", "Speichern", "Enregistrer", "Salva", "保存", "保存"],
  solarCancel: ["Cancel", "Cancelar", "Abbrechen", "Annuler", "Annulla", "キャンセル", "取消"],
  solarSaved: ["Saved.", "Guardado.", "Gespeichert.", "Enregistré.", "Salvato.", "保存しました。", "已保存。"],
  solarSaveFailed: ["That could not be done. Check the fields and that you are signed in.", "No se pudo hacer. Revisa los campos y que hayas iniciado sesión.", "Das ging nicht. Prüfe die Felder und ob du angemeldet bist.", "Impossible à faire. Vérifiez les champs et que vous êtes connecté.", "Non è stato possibile. Controlla i campi e di aver effettuato l'accesso.", "実行できませんでした。項目とサインイン状態を確認してください。", "无法完成。请检查各项内容并确认已登录。"],
  solarDeleted: ["Removed.", "Eliminado.", "Entfernt.", "Supprimé.", "Rimosso.", "削除しました。", "已删除。"],
  solarDeclared: ["Declared equipment", "Equipos declarados", "Deklarierte Geräte", "Équipements déclarés", "Dispositivi dichiarati", "登録済みの機器", "已登记设备"],
  solarWaiting: ["waiting for its first reading", "esperando su primera lectura", "wartet auf den ersten Messwert", "en attente de son premier relevé", "in attesa della prima lettura", "最初の測定値を待っています", "等待首次读数"],
  solarWaitingHelp: ["The equipment is declared and waits for its gateway node to send the first reading. Meanwhile you can try the menu with example readings.", "El equipo está declarado y espera a que su nodo pasarela envíe la primera lectura. Mientras tanto puedes probar el menú con lecturas de ejemplo.", "Das Gerät ist deklariert und wartet darauf, dass sein Gateway-Knoten den ersten Messwert sendet. Bis dahin kannst du das Menü mit Beispielwerten ausprobieren.", "L'équipement est déclaré et attend que son nœud passerelle envoie le premier relevé. En attendant, vous pouvez essayer le menu avec des relevés d'exemple.", "Il dispositivo è dichiarato e attende che il suo nodo gateway invii la prima lettura. Nel frattempo puoi provare il menu con letture di esempio.", "機器は登録済みで、ゲートウェイノードからの最初の測定値を待っています。それまではサンプルの測定値でメニューを試せます。", "设备已登记，正在等待其网关节点发送首次读数。在此期间可以用示例读数试用此菜单。"],
  solarReporting: ["sending data", "enviando datos", "sendet Daten", "envoie des données", "invia dati", "データ受信中", "正在上报数据"],
  solarExampleButton: ["Show example readings", "Ver lecturas de ejemplo", "Beispielwerte zeigen", "Voir des relevés d'exemple", "Mostra letture di esempio", "サンプルの測定値を表示", "显示示例读数"],
  solarExampleDone: ["Example readings loaded.", "Lecturas de ejemplo cargadas.", "Beispielwerte geladen.", "Relevés d'exemple chargés.", "Letture di esempio caricate.", "サンプルの測定値を読み込みました。", "已载入示例读数。"],
  solarExampleBadge: ["example data", "datos de ejemplo", "Beispieldaten", "données d'exemple", "dati di esempio", "サンプルデータ", "示例数据"],
  solarDialectHint: ["Serial protocol to choose on the node's port for this inverter:", "Protocolo serie que hay que elegir en el puerto del nodo para este inversor:", "Serielles Protokoll, das am Port des Knotens für diesen Wechselrichter zu wählen ist:", "Protocole série à choisir sur le port du nœud pour cet onduleur :", "Protocollo seriale da scegliere sulla porta del nodo per questo inverter:", "このインバーターにはノードのポートで次のシリアルプロトコルを選びます：", "此逆变器应在节点端口上选择的串行协议："],
  solarDialectAuto: ["automatic (the node looks for it)", "automático (el nodo lo busca)", "automatisch (der Knoten sucht es)", "automatique (le nœud le cherche)", "automatico (il nodo lo cerca)", "自動（ノードが検出します）", "自动（节点自行查找）"],
  solarOther: ["Other", "Otro", "Andere", "Autre", "Altro", "その他", "其他"],
  solarNoneAdd: ["Add your equipment with the button above: it waits for its gateway node, and you can try the menu with example readings.", "Añade tu equipo con el botón de arriba: espera a su nodo pasarela y puedes probar el menú con lecturas de ejemplo.", "Füge dein Gerät mit der Schaltfläche oben hinzu: es wartet auf seinen Gateway-Knoten, und du kannst das Menü mit Beispielwerten ausprobieren.", "Ajoutez votre équipement avec le bouton ci-dessus : il attend son nœud passerelle et vous pouvez essayer le menu avec des relevés d'exemple.", "Aggiungi il tuo dispositivo con il pulsante qui sopra: attende il suo nodo gateway e puoi provare il menu con letture di esempio.", "上のボタンで機器を追加してください。ゲートウェイノードを待つ間、サンプルの測定値でメニューを試せます。", "用上方按钮添加你的设备：它会等待网关节点，你也可以用示例读数试用此菜单。"],
};

export const solarCatalogues = cataloguesFromRows(ROWS);
