/**
 * The phrases of the versions of a design (the list of what the server kept and the unsaved copy of this browser), in the seven languages.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
 */
import { cataloguesFromRows, type Row } from "./catalogueRows";

const ROWS: Record<string, Row> = {
  versionsButton: ["Versions", "Versiones", "Versionen", "Versions", "Versioni", "バージョン", "版本"],
  versionsTitle: ["Earlier versions of this design", "Versiones anteriores de este diseño", "Frühere Versionen dieses Entwurfs", "Versions précédentes de ce plan", "Versioni precedenti di questo progetto", "この設計の以前のバージョン", "此设计的早期版本"],
  versionsHelp: ["The server keeps the design as it was before the changes: at most one every five minutes, always before a save that takes a lot away, and one of each of the last thirty days. Restoring one makes it the current design (the one you have now stays in the list).", "El servidor guarda el diseño tal como estaba antes de los cambios: como mucho uno cada cinco minutos, siempre antes de un guardado que quita mucho, y uno de cada uno de los últimos treinta días. Restaurar una versión la convierte en el diseño actual (el que tienes ahora queda en la lista).", "Der Server bewahrt den Entwurf auf, wie er vor den Änderungen war: höchstens alle fünf Minuten, immer vor einem Speichern, das viel entfernt, und eine pro Tag der letzten dreißig Tage. Beim Wiederherstellen wird sie zum aktuellen Entwurf (der jetzige bleibt in der Liste).", "Le serveur garde le plan tel qu'il était avant les changements : au plus un toutes les cinq minutes, toujours avant un enregistrement qui retire beaucoup, et un par jour des trente derniers jours. Restaurer une version la rend courante (la vôtre reste dans la liste).", "Il server conserva il progetto com'era prima delle modifiche: al massimo uno ogni cinque minuti, sempre prima di un salvataggio che toglie molto, e uno per ciascuno degli ultimi trenta giorni. Ripristinarne una la rende quella attuale (quella di ora resta nell'elenco).", "サーバーは変更前の設計を保存します。5分に1回まで、多くを削除する保存の前には必ず、そして過去30日間の各日に1つです。復元するとそれが現在の設計になります（今のものは一覧に残ります）。", "服务器会保存更改前的设计：最多每五分钟一个，在大量删除的保存之前一定保存，并保留最近三十天中每天的一个。恢复某个版本会使其成为当前设计（现在的这个会留在列表中）。"],
  versionsEmpty: ["No earlier version has been kept yet.", "Todavía no se ha guardado ninguna versión anterior.", "Es wurde noch keine frühere Version gespeichert.", "Aucune version précédente n'a encore été conservée.", "Non è ancora stata conservata alcuna versione precedente.", "以前のバージョンはまだ保存されていません。", "尚未保存任何早期版本。"],
  versionsLoading: ["Asking the server…", "Preguntando al servidor…", "Frage den Server…", "Interrogation du serveur…", "Interrogo il server…", "サーバーに問い合わせ中…", "正在询问服务器…"],
  versionsDelete: ["Delete", "Borrar", "Löschen", "Supprimer", "Elimina", "削除", "删除"],
  versionsDeleteSure: ["Sure? Click again", "¿Seguro? Pulsa otra vez", "Sicher? Nochmal klicken", "Sûr ? Cliquez encore", "Sicuro? Clicca ancora", "本当に？もう一度クリック", "确定？再点一次"],
  versionsDeleteAll: ["Delete all versions", "Borrar todas las versiones", "Alle Versionen löschen", "Supprimer toutes les versions", "Elimina tutte le versioni", "すべてのバージョンを削除", "删除所有版本"],
  versionsDeleted: ["The version was deleted. The current design was not touched.", "Versión borrada. El diseño actual no se ha tocado.", "Die Version wurde gelöscht. Der aktuelle Entwurf blieb unverändert.", "La version a été supprimée. Le plan actuel n'a pas été touché.", "La versione è stata eliminata. Il progetto attuale non è stato toccato.", "バージョンを削除しました。現在の設計はそのままです。", "版本已删除，当前设计未受影响。"],
  versionsFailed: ["The server could not be asked for the versions.", "No se ha podido pedir las versiones al servidor.", "Die Versionen konnten nicht vom Server abgefragt werden.", "Impossible de demander les versions au serveur.", "Impossibile chiedere le versioni al server.", "サーバーからバージョンを取得できませんでした。", "无法向服务器请求版本。"],
  versionsRestore: ["Restore", "Restaurar", "Wiederherstellen", "Restaurer", "Ripristina", "復元", "恢复"],
  versionsRestored: ["The version was restored and will be saved as the current design.", "La versión se ha restaurado y se guardará como diseño actual.", "Die Version wurde wiederhergestellt und wird als aktueller Entwurf gespeichert.", "La version a été restaurée et sera enregistrée comme plan courant.", "La versione è stata ripristinata e verrà salvata come progetto attuale.", "バージョンを復元しました。現在の設計として保存されます。", "版本已恢复，并将保存为当前设计。"],
  versionsDraft: ["Unsaved changes of this browser", "Cambios sin guardar de este navegador", "Nicht gespeicherte Änderungen dieses Browsers", "Modifications non enregistrées de ce navigateur", "Modifiche non salvate di questo browser", "このブラウザーの未保存の変更", "此浏览器中未保存的更改"],
  versionsDraftNotice: ["Changes made in this browser had not reached the server. They were kept: open Versions to restore them.", "Los cambios hechos en este navegador no habían llegado al servidor. Se han conservado: abre Versiones para restaurarlos.", "Änderungen in diesem Browser hatten den Server nicht erreicht. Sie wurden aufbewahrt: Öffnen Sie Versionen, um sie wiederherzustellen.", "Des modifications faites dans ce navigateur n'avaient pas atteint le serveur. Elles ont été gardées : ouvrez Versions pour les restaurer.", "Le modifiche fatte in questo browser non avevano raggiunto il server. Sono state conservate: apri Versioni per ripristinarle.", "このブラウザーで行った変更はサーバーに届いていませんでした。保存してあります。バージョンを開いて復元してください。", "在此浏览器中所做的更改尚未到达服务器。已为您保留：打开“版本”即可恢复。"],
  versionsDraftRecovered: ["Changes made in this browser had not reached the server: they were restored and are being saved now.", "Los cambios hechos en este navegador no habían llegado al servidor: se han restaurado y se están guardando ahora.", "Änderungen in diesem Browser hatten den Server nicht erreicht: Sie wurden wiederhergestellt und werden jetzt gespeichert.", "Des modifications faites dans ce navigateur n'avaient pas atteint le serveur : elles ont été restaurées et sont en cours d'enregistrement.", "Le modifiche fatte in questo browser non avevano raggiunto il server: sono state ripristinate e vengono salvate ora.", "このブラウザーで行った変更はサーバーに届いていませんでした。復元し、現在保存しています。", "在此浏览器中所做的更改尚未到达服务器：已恢复并正在保存。"],
  versionsBy: ["by", "por", "von", "par", "da", "作成者", "由"],
  count_buildings: ["buildings", "edificios", "Gebäude", "bâtiments", "edifici", "建物", "建筑"],
  count_openings: ["openings", "huecos", "Öffnungen", "ouvertures", "aperture", "開口部", "门窗"],
  count_features: ["objects", "objetos", "Objekte", "objets", "oggetti", "オブジェクト", "对象"],
  count_sensors: ["sensors", "sensores", "Sensoren", "capteurs", "sensori", "センサー", "传感器"],
};
export const versionsCatalogues = cataloguesFromRows(ROWS);
