/**
 * The phrases of the Weather menu, in the seven languages: the weather codes, the wind and its compass points, the UV and air quality bands, the pollen, the moon, the warnings the forecast implies and
 * the radar.
 * Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
 */
import { cataloguesFromRows, type Row } from "./catalogueRows";

const ROWS: Record<string, Row> = {
  weather: ["Weather", "Meteorología", "Wetter", "Météo", "Meteo", "天気", "天气"],
  weatherTitle: ["WEATHER", "METEOROLOGÍA", "WETTER", "MÉTÉO", "METEO", "天気", "天气"],
  weatherHelp: ["The weather where the installation is: now, the next hours and days, the rain of the next hour, the air and the pollen, and a live radar of rain and clouds.", "El tiempo donde está la instalación: ahora, las próximas horas y días, la lluvia de la próxima hora, el aire y el polen, y un radar en directo de lluvia y nubes.", "Das Wetter am Standort der Anlage: jetzt, die nächsten Stunden und Tage, der Regen der nächsten Stunde, Luft und Pollen sowie ein Live-Radar für Regen und Wolken.", "La météo là où se trouve l'installation : maintenant, les prochaines heures et jours, la pluie de l'heure à venir, l'air et le pollen, et un radar en direct de la pluie et des nuages.", "Il meteo dove si trova l'impianto: adesso, le prossime ore e giorni, la pioggia della prossima ora, l'aria e il polline, e un radar dal vivo di pioggia e nuvole.", "設置場所の天気：現在、これからの数時間と数日、次の1時間の雨、空気と花粉、そして雨と雲のライブレーダー。", "安装地点的天气：现在、未来数小时和数天、下一小时的降雨、空气与花粉，以及雨和云的实时雷达。"],
  wxConsentTitle: ["Turn on the weather", "Activar la meteorología", "Wetter aktivieren", "Activer la météo", "Attiva il meteo", "天気を有効にする", "启用天气"],
  wxConsentBody: ["This menu asks public weather services over the Internet, and only while it is open: Open-Meteo (forecast, air and pollen), RainViewer (rain radar), EUMETSAT (satellite image of the clouds) and a map from Esri. What they receive is the coordinates of the place you choose and your Internet address, as in any web page. Nothing else of the installation leaves.", "Este menú consulta servicios meteorológicos públicos por Internet, y solo mientras está abierto: Open-Meteo (previsión, aire y polen), RainViewer (radar de lluvia), EUMETSAT (imagen de satélite de las nubes) y un mapa de Esri. Lo que reciben son las coordenadas del lugar que elijas y tu dirección de Internet, como en cualquier página web. Nada más de la instalación sale.", "Dieses Menü fragt öffentliche Wetterdienste über das Internet ab, und nur solange es geöffnet ist: Open-Meteo (Vorhersage, Luft und Pollen), RainViewer (Regenradar), EUMETSAT (Satellitenbild der Wolken) und eine Karte von Esri. Sie erhalten die Koordinaten des gewählten Ortes und Ihre Internetadresse, wie bei jeder Webseite. Sonst verlässt nichts die Anlage.", "Ce menu interroge des services météo publics via Internet, et seulement tant qu'il est ouvert : Open-Meteo (prévisions, air et pollen), RainViewer (radar de pluie), EUMETSAT (image satellite des nuages) et une carte d'Esri. Ils reçoivent les coordonnées du lieu choisi et votre adresse Internet, comme pour toute page web. Rien d'autre de l'installation ne sort.", "Questo menu interroga servizi meteo pubblici via Internet, e solo finché è aperto: Open-Meteo (previsioni, aria e polline), RainViewer (radar della pioggia), EUMETSAT (immagine satellitare delle nuvole) e una mappa di Esri. Ricevono le coordinate del luogo scelto e il tuo indirizzo Internet, come in qualsiasi pagina web. Nient'altro dell'impianto esce.", "このメニューは開いている間だけ、インターネット上の公的な気象サービスに問い合わせます：Open-Meteo（予報・空気・花粉）、RainViewer（雨レーダー）、EUMETSAT（雲の衛星画像）、Esri の地図。送られるのは選んだ場所の座標とあなたのインターネットアドレスだけで、通常のウェブページと同じです。設置の他の情報は外に出ません。", "此菜单仅在打开时通过互联网查询公共气象服务：Open-Meteo（预报、空气和花粉）、RainViewer（雨量雷达）、EUMETSAT（云的卫星图像）和 Esri 地图。它们收到的是您所选地点的坐标和您的互联网地址，与任何网页相同。安装的其他信息不会外传。"],
  wxDisable: ["Turn off and forget the place", "Desactivar y olvidar el lugar", "Ausschalten und Ort vergessen", "Désactiver et oublier le lieu", "Disattiva e dimentica il luogo", "無効にして場所を忘れる", "关闭并忘记地点"],
  wxPlace: ["Place", "Lugar", "Ort", "Lieu", "Luogo", "場所", "地点"],
  wxSearchPlace: ["Search a town or city", "Buscar un pueblo o ciudad", "Ort oder Stadt suchen", "Chercher une ville", "Cerca una città", "町や市を検索", "搜索城镇或城市"],
  wxSearch: ["Search", "Buscar", "Suchen", "Chercher", "Cerca", "検索", "搜索"],
  wxChangePlace: ["Change place", "Cambiar lugar", "Ort ändern", "Changer de lieu", "Cambia luogo", "場所を変更", "更改地点"],
  wxNoResults: ["No place found with that name.", "No se encontró ningún lugar con ese nombre.", "Kein Ort mit diesem Namen gefunden.", "Aucun lieu trouvé avec ce nom.", "Nessun luogo trovato con quel nome.", "その名前の場所は見つかりませんでした。", "没有找到该名称的地点。"],
  wxChoosePlace: ["Choose where the installation is to see its weather.", "Elige dónde está la instalación para ver su tiempo.", "Wählen Sie den Standort der Anlage, um das Wetter zu sehen.", "Choisissez où se trouve l'installation pour voir sa météo.", "Scegli dove si trova l'impianto per vedere il suo meteo.", "設置場所を選ぶと天気が表示されます。", "选择安装地点以查看天气。"],
  wxUpdated: ["Updated", "Actualizado", "Aktualisiert", "Mis à jour", "Aggiornato", "更新", "更新于"],
  wxLoading: ["Loading the weather…", "Cargando el tiempo…", "Wetter wird geladen…", "Chargement de la météo…", "Caricamento del meteo…", "天気を読み込み中…", "正在加载天气…"],
  wxLoadError: ["The weather service did not answer. Try again in a moment.", "El servicio meteorológico no respondió. Inténtalo de nuevo en un momento.", "Der Wetterdienst hat nicht geantwortet. Gleich noch einmal versuchen.", "Le service météo n'a pas répondu. Réessayez dans un instant.", "Il servizio meteo non ha risposto. Riprova tra un momento.", "気象サービスが応答しませんでした。しばらくしてからもう一度お試しください。", "气象服务没有响应。请稍后再试。"],
  wxNow: ["Now", "Ahora", "Jetzt", "Maintenant", "Adesso", "現在", "现在"],
  wxFeelsLike: ["Feels like", "Sensación", "Gefühlt", "Ressenti", "Percepita", "体感", "体感"],
  wxHumidity: ["Humidity", "Humedad", "Luftfeuchte", "Humidité", "Umidità", "湿度", "湿度"],
  wxDewPoint: ["Dew point", "Punto de rocío", "Taupunkt", "Point de rosée", "Punto di rugiada", "露点", "露点"],
  wxPressure: ["Pressure", "Presión", "Luftdruck", "Pression", "Pressione", "気圧", "气压"],
  wxRising: ["rising", "subiendo", "steigend", "en hausse", "in aumento", "上昇中", "上升"],
  wxFalling: ["falling", "bajando", "fallend", "en baisse", "in calo", "下降中", "下降"],
  wxSteady: ["steady", "estable", "stabil", "stable", "stabile", "安定", "稳定"],
  wxWind: ["Wind", "Viento", "Wind", "Vent", "Vento", "風", "风"],
  wxGusts: ["Gusts", "Rachas", "Böen", "Rafales", "Raffiche", "突風", "阵风"],
  wxFrom: ["from", "del", "aus", "de", "da", "風向", "来自"],
  wxCloudCover: ["Cloud cover", "Nubosidad", "Bewölkung", "Nébulosité", "Nuvolosità", "雲量", "云量"],
  wxVisibility: ["Visibility", "Visibilidad", "Sichtweite", "Visibilité", "Visibilità", "視程", "能见度"],
  wxUv: ["UV index", "Índice UV", "UV-Index", "Indice UV", "Indice UV", "UV指数", "紫外线指数"],
  wxPrecipitation: ["Precipitation", "Precipitación", "Niederschlag", "Précipitations", "Precipitazioni", "降水", "降水"],
  wxElevation: ["Elevation", "Altitud", "Höhe", "Altitude", "Altitudine", "標高", "海拔"],
  wxSunrise: ["Sunrise", "Amanecer", "Sonnenaufgang", "Lever du soleil", "Alba", "日の出", "日出"],
  wxSunset: ["Sunset", "Atardecer", "Sonnenuntergang", "Coucher du soleil", "Tramonto", "日の入り", "日落"],
  wxDaylight: ["Daylight", "Luz de día", "Tageslicht", "Durée du jour", "Ore di luce", "日照時間", "白昼时长"],
  wxMoon: ["Moon", "Luna", "Mond", "Lune", "Luna", "月", "月亮"],
  wxLit: ["lit", "iluminada", "beleuchtet", "éclairée", "illuminata", "照らされた部分", "被照亮"],
  wxFreezing: ["Freezing level", "Nivel de congelación", "Nullgradgrenze", "Zéro thermique", "Quota dello zero termico", "氷点高度", "冰点高度"],
  wxRainNow: ["It is raining now", "Está lloviendo ahora", "Es regnet gerade", "Il pleut en ce moment", "Sta piovendo adesso", "今、雨が降っています", "现在正在下雨"],
  wxRainNone: ["No rain expected in the next hour", "No se espera lluvia en la próxima hora", "In der nächsten Stunde ist kein Regen zu erwarten", "Pas de pluie prévue dans l'heure qui vient", "Nessuna pioggia prevista nella prossima ora", "次の1時間は雨の予報はありません", "未来一小时预计无降雨"],
  wxRainFrom: ["Rain from", "Lluvia desde las", "Regen ab", "Pluie à partir de", "Pioggia dalle", "雨：", "降雨从"],
  wxRainMm: ["mm in the next hour", "mm en la próxima hora", "mm in der nächsten Stunde", "mm dans l'heure qui vient", "mm nella prossima ora", "mm（次の1時間）", "毫米（未来一小时）"],
  wxHours: ["Next 48 hours", "Próximas 48 horas", "Nächste 48 Stunden", "48 prochaines heures", "Prossime 48 ore", "今後48時間", "未来48小时"],
  wxDays: ["Next days", "Próximos días", "Nächste Tage", "Prochains jours", "Prossimi giorni", "今後の数日", "未来几天"],
  wxTemperature: ["Temperature", "Temperatura", "Temperatur", "Température", "Temperatura", "気温", "气温"],
  wxRainChance: ["Chance of rain", "Probabilidad de lluvia", "Regenwahrscheinlichkeit", "Probabilité de pluie", "Probabilità di pioggia", "降水確率", "降雨概率"],
  wxClouds: ["Clouds", "Nubes", "Wolken", "Nuages", "Nuvole", "雲", "云"],
  wxCloudLow: ["low", "bajas", "tief", "basses", "basse", "下層", "低层"],
  wxCloudMid: ["medium", "medias", "mittel", "moyennes", "medie", "中層", "中层"],
  wxCloudHigh: ["high", "altas", "hoch", "hautes", "alte", "上層", "高层"],
  wxMax: ["max", "máx", "max", "max", "max", "最高", "最高"],
  wxMin: ["min", "mín", "min", "min", "min", "最低", "最低"],
  wxToday: ["Today", "Hoy", "Heute", "Aujourd'hui", "Oggi", "今日", "今天"],
  wxAir: ["Air quality", "Calidad del aire", "Luftqualität", "Qualité de l'air", "Qualità dell'aria", "空気質", "空气质量"],
  wxAqi: ["European index", "Índice europeo", "Europäischer Index", "Indice européen", "Indice europeo", "欧州指数", "欧洲指数"],
  wxPm25: ["PM2.5", "PM2.5", "PM2.5", "PM2.5", "PM2.5", "PM2.5", "PM2.5"],
  wxPm10: ["PM10", "PM10", "PM10", "PM10", "PM10", "PM10", "PM10"],
  wxOzone: ["Ozone", "Ozono", "Ozon", "Ozone", "Ozono", "オゾン", "臭氧"],
  wxNo2: ["Nitrogen dioxide", "Dióxido de nitrógeno", "Stickstoffdioxid", "Dioxyde d'azote", "Biossido di azoto", "二酸化窒素", "二氧化氮"],
  wxSo2: ["Sulphur dioxide", "Dióxido de azufre", "Schwefeldioxid", "Dioxyde de soufre", "Biossido di zolfo", "二酸化硫黄", "二氧化硫"],
  wxCo: ["Carbon monoxide", "Monóxido de carbono", "Kohlenmonoxid", "Monoxyde de carbone", "Monossido di carbonio", "一酸化炭素", "一氧化碳"],
  wxDust: ["Dust", "Polvo", "Staub", "Poussière", "Polvere", "ダスト", "沙尘"],
  wxPollen: ["Pollen", "Polen", "Pollen", "Pollen", "Polline", "花粉", "花粉"],
  wxPollenNone: ["Pollen is only measured in Europe, in its season.", "El polen solo se mide en Europa, en su temporada.", "Pollen wird nur in Europa und nur in der Saison gemessen.", "Le pollen n'est mesuré qu'en Europe, en saison.", "Il polline è misurato solo in Europa, nella stagione.", "花粉はヨーロッパのシーズン中のみ観測されます。", "花粉仅在欧洲的花粉季测量。"],
  wxPollen_alder: ["Alder", "Aliso", "Erle", "Aulne", "Ontano", "ハンノキ", "桤木"],
  wxPollen_birch: ["Birch", "Abedul", "Birke", "Bouleau", "Betulla", "シラカバ", "桦树"],
  wxPollen_grass: ["Grass", "Gramíneas", "Gräser", "Graminées", "Graminacee", "イネ科", "禾本科"],
  wxPollen_mugwort: ["Mugwort", "Artemisa", "Beifuß", "Armoise", "Artemisia", "ヨモギ", "艾草"],
  wxPollen_olive: ["Olive", "Olivo", "Olive", "Olivier", "Olivo", "オリーブ", "橄榄"],
  wxPollen_ragweed: ["Ragweed", "Ambrosía", "Ambrosia", "Ambroisie", "Ambrosia", "ブタクサ", "豚草"],
  wxWarnings: ["Warnings from the forecast", "Avisos según la previsión", "Warnungen aus der Vorhersage", "Alertes selon les prévisions", "Avvisi dalle previsioni", "予報からの注意", "根据预报的提示"],
  wxWarningsNote: ["Worked out from the forecast of the next 48 hours by simple thresholds. They are not official warnings: follow the national weather service.", "Calculados de la previsión de las próximas 48 horas con umbrales sencillos. No son avisos oficiales: sigue el servicio meteorológico nacional.", "Aus der Vorhersage der nächsten 48 Stunden mit einfachen Schwellen berechnet. Es sind keine amtlichen Warnungen: Folgen Sie dem nationalen Wetterdienst.", "Calculées d'après les prévisions des 48 prochaines heures avec des seuils simples. Ce ne sont pas des alertes officielles : suivez le service météo national.", "Calcolati dalle previsioni delle prossime 48 ore con soglie semplici. Non sono avvisi ufficiali: segui il servizio meteorologico nazionale.", "今後48時間の予報から簡単なしきい値で算出したものです。公的な警報ではありません。気象機関の情報に従ってください。", "根据未来48小时预报按简单阈值推算。这不是官方预警：请关注国家气象部门。"],
  wxNoWarnings: ["Nothing to warn about in the next 48 hours.", "Nada que avisar en las próximas 48 horas.", "In den nächsten 48 Stunden ist nichts zu warnen.", "Rien à signaler dans les 48 prochaines heures.", "Niente da segnalare nelle prossime 48 ore.", "今後48時間は注意すべきことはありません。", "未来48小时无需提示。"],
  wxWatch: ["Watch", "Atención", "Achtung", "Attention", "Attenzione", "注意", "注意"],
  wxWarningLevel: ["Warning", "Aviso", "Warnung", "Alerte", "Avviso", "警告", "警告"],
  wxExpectedAt: ["expected", "previsto", "erwartet", "prévu", "previsto", "予想", "预计"],
  w_rain_heavy: ["Heavy rain", "Lluvia intensa", "Starkregen", "Pluie forte", "Pioggia intensa", "強い雨", "大雨"],
  w_rain_violent: ["Violent rain", "Lluvia torrencial", "Wolkenbruch", "Pluie torrentielle", "Pioggia torrenziale", "激しい雨", "暴雨"],
  w_wind_strong: ["Strong gusts", "Rachas fuertes", "Starke Böen", "Fortes rafales", "Forti raffiche", "強い突風", "强阵风"],
  w_wind_storm: ["Storm gusts", "Rachas de temporal", "Sturmböen", "Rafales de tempête", "Raffiche di tempesta", "暴風級の突風", "风暴级阵风"],
  w_heat: ["Heat", "Calor", "Hitze", "Chaleur", "Caldo", "暑さ", "高温"],
  w_heat_extreme: ["Extreme heat", "Calor extremo", "Extreme Hitze", "Chaleur extrême", "Caldo estremo", "猛暑", "极端高温"],
  w_cold: ["Cold", "Frío", "Kälte", "Froid", "Freddo", "寒さ", "低温"],
  w_cold_extreme: ["Extreme cold", "Frío extremo", "Extreme Kälte", "Froid extrême", "Freddo estremo", "厳しい寒さ", "极端低温"],
  w_snow: ["Snow", "Nieve", "Schnee", "Neige", "Neve", "雪", "降雪"],
  w_snow_heavy: ["Heavy snow", "Nevada fuerte", "Starker Schneefall", "Fortes chutes de neige", "Nevicata intensa", "大雪", "大雪"],
  w_thunder: ["Thunderstorms", "Tormentas", "Gewitter", "Orages", "Temporali", "雷雨", "雷暴"],
  w_thunder_hail: ["Thunderstorms with hail", "Tormentas con granizo", "Gewitter mit Hagel", "Orages avec grêle", "Temporali con grandine", "雹を伴う雷雨", "伴有冰雹的雷暴"],
  w_freezing_rain: ["Freezing rain (ice)", "Lluvia helada (hielo)", "Gefrierender Regen (Eis)", "Pluie verglaçante", "Pioggia gelata (ghiaccio)", "着氷性の雨", "冻雨"],
  w_fog: ["Fog", "Niebla", "Nebel", "Brouillard", "Nebbia", "霧", "雾"],
  w_fog_dense: ["Dense fog", "Niebla densa", "Dichter Nebel", "Brouillard dense", "Nebbia fitta", "濃霧", "浓雾"],
  w_uv_extreme: ["Extreme UV", "UV extremo", "Extreme UV-Strahlung", "UV extrême", "UV estremo", "極端なUV", "极端紫外线"],
  wxRadar: ["Radar", "Radar", "Radar", "Radar", "Radar", "レーダー", "雷达"],
  wxRadarRain: ["Rain", "Lluvia", "Regen", "Pluie", "Pioggia", "雨", "雨"],
  wxRadarClouds: ["Clouds (satellite)", "Nubes (satélite)", "Wolken (Satellit)", "Nuages (satellite)", "Nuvole (satellite)", "雲（衛星）", "云（卫星）"],
  wxRadarPlay: ["Play", "Reproducir", "Abspielen", "Lecture", "Riproduci", "再生", "播放"],
  wxRadarPause: ["Pause", "Pausa", "Pause", "Pause", "Pausa", "一時停止", "暂停"],
  wxRadarOpacity: ["Opacity", "Opacidad", "Deckkraft", "Opacité", "Opacità", "不透明度", "不透明度"],
  wxRadarPast: ["Last two hours, every ten minutes", "Últimas dos horas, cada diez minutos", "Letzte zwei Stunden, alle zehn Minuten", "Deux dernières heures, toutes les dix minutes", "Ultime due ore, ogni dieci minuti", "過去2時間（10分ごと）", "最近两小时，每十分钟"],
  wxRadarCloudsNote: ["Infrared image from the Meteosat satellite (Europe and Africa), about every ten minutes: the brighter, the colder and higher the cloud.", "Imagen infrarroja del satélite Meteosat (Europa y África), cada unos diez minutos: cuanto más brillante, más fría y alta es la nube.", "Infrarotbild des Satelliten Meteosat (Europa und Afrika), etwa alle zehn Minuten: je heller, desto kälter und höher die Wolke.", "Image infrarouge du satellite Meteosat (Europe et Afrique), environ toutes les dix minutes : plus c'est clair, plus le nuage est froid et haut.", "Immagine a infrarossi del satellite Meteosat (Europa e Africa), circa ogni dieci minuti: più è chiara, più la nuvola è fredda e alta.", "Meteosat衛星の赤外画像（ヨーロッパとアフリカ）、約10分ごと。明るいほど雲は冷たく高い位置にあります。", "Meteosat 卫星红外图像（欧洲和非洲），约每十分钟一次：越亮表示云越冷、越高。"],
  wxRadarNoData: ["The radar did not answer.", "El radar no respondió.", "Das Radar hat nicht geantwortet.", "Le radar n'a pas répondu.", "Il radar non ha risposto.", "レーダーが応答しませんでした。", "雷达没有响应。"],
  wxRadarNoFrames: ["No radar images available.", "No hay imágenes de radar disponibles.", "Keine Radarbilder verfügbar.", "Aucune image radar disponible.", "Nessuna immagine radar disponibile.", "利用できるレーダー画像がありません。", "没有可用的雷达图像。"],
  wxSources: ["Data: Open-Meteo.com (CC BY 4.0) and CAMS/Copernicus for the air; radar: RainViewer; clouds: EUMETSAT; map: Esri, HERE, Garmin, © OpenStreetMap contributors.", "Datos: Open-Meteo.com (CC BY 4.0) y CAMS/Copernicus para el aire; radar: RainViewer; nubes: EUMETSAT; mapa: Esri, HERE, Garmin, © colaboradores de OpenStreetMap.", "Daten: Open-Meteo.com (CC BY 4.0) und CAMS/Copernicus für die Luft; Radar: RainViewer; Wolken: EUMETSAT; Karte: Esri, HERE, Garmin, © OpenStreetMap-Mitwirkende.", "Données : Open-Meteo.com (CC BY 4.0) et CAMS/Copernicus pour l'air ; radar : RainViewer ; nuages : EUMETSAT ; carte : Esri, HERE, Garmin, © contributeurs OpenStreetMap.", "Dati: Open-Meteo.com (CC BY 4.0) e CAMS/Copernicus per l'aria; radar: RainViewer; nuvole: EUMETSAT; mappa: Esri, HERE, Garmin, © contributori di OpenStreetMap.", "データ：Open-Meteo.com（CC BY 4.0）、空気はCAMS/Copernicus。レーダー：RainViewer、雲：EUMETSAT、地図：Esri, HERE, Garmin, © OpenStreetMap contributors。", "数据：Open-Meteo.com（CC BY 4.0），空气数据来自 CAMS/Copernicus；雷达：RainViewer；云：EUMETSAT；地图：Esri, HERE, Garmin, © OpenStreetMap 贡献者。"],
  wxMapPlace: ["The place", "El lugar", "Der Ort", "Le lieu", "Il luogo", "場所", "地点"],
  wd_0: ["N", "N", "N", "N", "N", "北", "北"], wd_1: ["NE", "NE", "NO", "NE", "NE", "北東", "东北"], wd_2: ["E", "E", "O", "E", "E", "東", "东"], wd_3: ["SE", "SE", "SO", "SE", "SE", "南東", "东南"],
  wd_4: ["S", "S", "S", "S", "S", "南", "南"], wd_5: ["SW", "SO", "SW", "SO", "SO", "南西", "西南"], wd_6: ["W", "O", "W", "O", "O", "西", "西"], wd_7: ["NW", "NO", "NW", "NO", "NO", "北西", "西北"],
  wind_calm: ["calm", "en calma", "windstill", "calme", "calmo", "静穏", "无风"], wind_light: ["light breeze", "brisa suave", "leichte Brise", "légère brise", "brezza leggera", "そよ風", "微风"],
  wind_moderate: ["moderate breeze", "brisa moderada", "mäßige Brise", "brise modérée", "brezza moderata", "穏やかな風", "和风"], wind_fresh: ["fresh breeze", "viento fresco", "frische Brise", "vent frais", "vento fresco", "強めの風", "清劲风"],
  wind_strong: ["strong wind", "viento fuerte", "starker Wind", "vent fort", "vento forte", "強風", "强风"], wind_gale: ["gale", "temporal", "stürmischer Wind", "coup de vent", "burrasca", "暴風", "大风"],
  wind_storm: ["storm", "temporal fuerte", "Sturm", "tempête", "tempesta", "暴風雨", "风暴"], wind_hurricane: ["hurricane force", "fuerza de huracán", "Orkan", "force d'ouragan", "forza d'uragano", "ハリケーン級", "飓风级"],
  uv_low: ["low", "bajo", "niedrig", "faible", "basso", "弱い", "低"], uv_moderate: ["moderate", "moderado", "mäßig", "modéré", "moderato", "中程度", "中等"], uv_high: ["high", "alto", "hoch", "élevé", "alto", "強い", "高"],
  uv_very_high: ["very high", "muy alto", "sehr hoch", "très élevé", "molto alto", "非常に強い", "很高"], uv_extreme: ["extreme", "extremo", "extrem", "extrême", "estremo", "極端", "极高"],
  aqi_good: ["good", "buena", "gut", "bon", "buona", "良い", "良好"], aqi_fair: ["fair", "razonable", "mäßig", "moyen", "discreta", "まずまず", "尚可"], aqi_moderate: ["moderate", "regular", "mittelmäßig", "médiocre", "mediocre", "普通", "中等"],
  aqi_poor: ["poor", "mala", "schlecht", "mauvais", "scadente", "悪い", "较差"], aqi_very_poor: ["very poor", "muy mala", "sehr schlecht", "très mauvais", "molto scadente", "非常に悪い", "很差"], aqi_extremely_poor: ["extremely poor", "extremadamente mala", "extrem schlecht", "extrêmement mauvais", "estremamente scadente", "極めて悪い", "极差"],
  pollen_none: ["none", "ninguno", "keiner", "aucun", "nessuno", "なし", "无"], pollen_low: ["low", "bajo", "niedrig", "faible", "basso", "少ない", "低"], pollen_moderate: ["moderate", "moderado", "mäßig", "modéré", "moderato", "中程度", "中等"],
  pollen_high: ["high", "alto", "hoch", "élevé", "alto", "多い", "高"], pollen_very_high: ["very high", "muy alto", "sehr hoch", "très élevé", "molto alto", "非常に多い", "很高"],
  moon_new: ["New moon", "Luna nueva", "Neumond", "Nouvelle lune", "Luna nuova", "新月", "新月"], moon_waxing_crescent: ["Waxing crescent", "Creciente", "Zunehmende Sichel", "Premier croissant", "Luna crescente", "三日月", "蛾眉月"],
  moon_first_quarter: ["First quarter", "Cuarto creciente", "Erstes Viertel", "Premier quartier", "Primo quarto", "上弦", "上弦月"], moon_waxing_gibbous: ["Waxing gibbous", "Gibosa creciente", "Zunehmender Mond", "Gibbeuse croissante", "Gibbosa crescente", "十三夜", "盈凸月"],
  moon_full: ["Full moon", "Luna llena", "Vollmond", "Pleine lune", "Luna piena", "満月", "满月"], moon_waning_gibbous: ["Waning gibbous", "Gibosa menguante", "Abnehmender Mond", "Gibbeuse décroissante", "Gibbosa calante", "寝待月", "亏凸月"],
  moon_last_quarter: ["Last quarter", "Cuarto menguante", "Letztes Viertel", "Dernier quartier", "Ultimo quarto", "下弦", "下弦月"], moon_waning_crescent: ["Waning crescent", "Menguante", "Abnehmende Sichel", "Dernier croissant", "Luna calante", "有明月", "残月"],
  wx_clear: ["Clear", "Despejado", "Klar", "Dégagé", "Sereno", "快晴", "晴"], wx_mostly_clear: ["Mostly clear", "Poco nuboso", "Überwiegend klar", "Peu nuageux", "Poco nuvoloso", "おおむね晴れ", "大部晴朗"], wx_partly_cloudy: ["Partly cloudy", "Parcialmente nuboso", "Teilweise bewölkt", "Partiellement nuageux", "Parzialmente nuvoloso", "一部曇り", "局部多云"],
  wx_overcast: ["Overcast", "Cubierto", "Bedeckt", "Couvert", "Coperto", "曇り", "阴"], wx_fog: ["Fog", "Niebla", "Nebel", "Brouillard", "Nebbia", "霧", "雾"], wx_rime_fog: ["Freezing fog", "Niebla engelante", "Reifnebel", "Brouillard givrant", "Nebbia gelata", "着氷霧", "雾凇"],
  wx_drizzle_light: ["Light drizzle", "Llovizna ligera", "Leichter Nieselregen", "Bruine légère", "Pioggerella leggera", "弱い霧雨", "小毛毛雨"], wx_drizzle: ["Drizzle", "Llovizna", "Nieselregen", "Bruine", "Pioggerella", "霧雨", "毛毛雨"], wx_drizzle_heavy: ["Heavy drizzle", "Llovizna intensa", "Starker Nieselregen", "Bruine forte", "Pioggerella intensa", "強い霧雨", "大毛毛雨"],
  wx_freezing_drizzle: ["Freezing drizzle", "Llovizna helada", "Gefrierender Nieselregen", "Bruine verglaçante", "Pioggerella gelata", "着氷性の霧雨", "冻毛毛雨"], wx_freezing_drizzle_heavy: ["Heavy freezing drizzle", "Llovizna helada intensa", "Starker gefrierender Nieselregen", "Forte bruine verglaçante", "Forte pioggerella gelata", "強い着氷性の霧雨", "强冻毛毛雨"],
  wx_rain_light: ["Light rain", "Lluvia ligera", "Leichter Regen", "Pluie faible", "Pioggia leggera", "弱い雨", "小雨"], wx_rain: ["Rain", "Lluvia", "Regen", "Pluie", "Pioggia", "雨", "中雨"], wx_rain_heavy: ["Heavy rain", "Lluvia intensa", "Starkregen", "Pluie forte", "Pioggia intensa", "強い雨", "大雨"],
  wx_freezing_rain: ["Freezing rain", "Lluvia helada", "Gefrierender Regen", "Pluie verglaçante", "Pioggia gelata", "着氷性の雨", "冻雨"], wx_freezing_rain_heavy: ["Heavy freezing rain", "Lluvia helada intensa", "Starker gefrierender Regen", "Forte pluie verglaçante", "Forte pioggia gelata", "強い着氷性の雨", "强冻雨"],
  wx_snow_light: ["Light snow", "Nieve ligera", "Leichter Schneefall", "Neige faible", "Neve leggera", "弱い雪", "小雪"], wx_snow: ["Snow", "Nieve", "Schneefall", "Neige", "Neve", "雪", "中雪"], wx_snow_heavy: ["Heavy snow", "Nieve intensa", "Starker Schneefall", "Forte neige", "Neve intensa", "強い雪", "大雪"],
  wx_snow_grains: ["Snow grains", "Cinarra", "Schneegriesel", "Grains de neige", "Granuli di neve", "霧雪", "米雪"], wx_showers_light: ["Light showers", "Chubascos ligeros", "Leichte Schauer", "Averses faibles", "Rovesci leggeri", "弱いにわか雨", "小阵雨"], wx_showers: ["Showers", "Chubascos", "Schauer", "Averses", "Rovesci", "にわか雨", "阵雨"],
  wx_showers_violent: ["Violent showers", "Chubascos violentos", "Heftige Schauer", "Averses violentes", "Rovesci violenti", "激しいにわか雨", "强阵雨"], wx_snow_showers_light: ["Light snow showers", "Chubascos de nieve ligeros", "Leichte Schneeschauer", "Averses de neige faibles", "Rovesci di neve leggeri", "弱いにわか雪", "小阵雪"],
  wx_snow_showers_heavy: ["Heavy snow showers", "Chubascos de nieve intensos", "Starke Schneeschauer", "Fortes averses de neige", "Forti rovesci di neve", "強いにわか雪", "强阵雪"], wx_thunder: ["Thunderstorm", "Tormenta", "Gewitter", "Orage", "Temporale", "雷雨", "雷暴"],
  wx_thunder_hail: ["Thunderstorm with hail", "Tormenta con granizo", "Gewitter mit Hagel", "Orage avec grêle", "Temporale con grandine", "雹を伴う雷雨", "雷暴伴冰雹"], wx_thunder_hail_heavy: ["Thunderstorm with heavy hail", "Tormenta con granizo fuerte", "Gewitter mit starkem Hagel", "Orage avec forte grêle", "Temporale con forte grandine", "大粒の雹を伴う雷雨", "雷暴伴强冰雹"], wx_unknown: ["Unknown", "Desconocido", "Unbekannt", "Inconnu", "Sconosciuto", "不明", "未知"],
  wxByCoordinates: ["Or enter the coordinates", "O escribe las coordenadas", "Oder Koordinaten eingeben", "Ou saisir les coordonnées", "Oppure inserisci le coordinate", "または座標を入力", "或输入坐标"],
  wxPlaceName: ["Name of the place", "Nombre del lugar", "Name des Ortes", "Nom du lieu", "Nome del luogo", "場所の名前", "地点名称"],
  wxLatitude: ["Latitude (e.g. 38.6137)", "Latitud (p. ej. 38,6137)", "Breitengrad (z. B. 38,6137)", "Latitude (ex. 38,6137)", "Latitudine (es. 38,6137)", "緯度（例 38.6137）", "纬度（例如 38.6137）"],
  wxLongitude: ["Longitude (e.g. -1.1147)", "Longitud (p. ej. -1,1147)", "Längengrad (z. B. -1,1147)", "Longitude (ex. -1,1147)", "Longitudine (es. -1,1147)", "経度（例 -1.1147）", "经度（例如 -1.1147）"],
  wxUseCoordinates: ["Use these coordinates", "Usar estas coordenadas", "Diese Koordinaten verwenden", "Utiliser ces coordonnées", "Usa queste coordinate", "この座標を使う", "使用这些坐标"],
};

export const weatherCatalogues = cataloguesFromRows(ROWS);
